.rn '' }`
''' $RCSfile$$Revision$$Date$
'''
''' $Log$
'''
.de Sh
.br
.if t .Sp
.ne 5
.PP
\fB\\$1\fR
.PP
..
.de Sp
.if t .sp .5v
.if n .sp
..
.de Ip
.br
.ie \\n(.$>=3 .ne \\$3
.el .ne 3
.IP "\\$1" \\$2
..
.de Vb
.ft CW
.nf
.ne \\$1
..
.de Ve
.ft R

.fi
..
'''
'''
'''     Set up \*(-- to give an unbreakable dash;
'''     string Tr holds user defined translation string.
'''     Bell System Logo is used as a dummy character.
'''
.tr \(*W-|\(bv\*(Tr
.ie n \{\
.ds -- \(*W-
.ds PI pi
.if (\n(.H=4u)&(1m=24u) .ds -- \(*W\h'-12u'\(*W\h'-12u'-\" diablo 10 pitch
.if (\n(.H=4u)&(1m=20u) .ds -- \(*W\h'-12u'\(*W\h'-8u'-\" diablo 12 pitch
.ds L" ""
.ds R" ""
'''   \*(M", \*(S", \*(N" and \*(T" are the equivalent of
'''   \*(L" and \*(R", except that they are used on ".xx" lines,
'''   such as .IP and .SH, which do another additional levels of
'''   double-quote interpretation
.ds M" """
.ds S" """
.ds N" """""
.ds T" """""
.ds L' '
.ds R' '
.ds M' '
.ds S' '
.ds N' '
.ds T' '
'br\}
.el\{\
.ds -- \(em\|
.tr \*(Tr
.ds L" ``
.ds R" ''
.ds M" ``
.ds S" ''
.ds N" ``
.ds T" ''
.ds L' `
.ds R' '
.ds M' `
.ds S' '
.ds N' `
.ds T' '
.ds PI \(*p
'br\}
.\"	If the F register is turned on, we'll generate
.\"	index entries out stderr for the following things:
.\"		TH	Title 
.\"		SH	Header
.\"		Sh	Subsection 
.\"		Ip	Item
.\"		X<>	Xref  (embedded
.\"	Of course, you have to process the output yourself
.\"	in some meaninful fashion.
.if \nF \{
.de IX
.tm Index:\\$1\t\\n%\t"\\$2"
..
.nr % 0
.rr F
.\}
.TH A2P 1 "perl 5.004, patch 01" "10/Apr/97" "Perl Programmers Reference Guide"
.IX Title "A2P 1"
.UC
.IX Name "a2p - Awk to Perl translator"
.if n .hy 0
.if n .na
.ds C+ C\v'-.1v'\h'-1p'\s-2+\h'-1p'+\s0\v'.1v'\h'-1p'
.de CQ          \" put $1 in typewriter font
.ft CW
'if n "\c
'if t \\&\\$1\c
'if n \\&\\$1\c
'if n \&"
\\&\\$2 \\$3 \\$4 \\$5 \\$6 \\$7
'.ft R
..
.\" @(#)ms.acc 1.5 88/02/08 SMI; from UCB 4.2
.	\" AM - accent mark definitions
.bd B 3
.	\" fudge factors for nroff and troff
.if n \{\
.	ds #H 0
.	ds #V .8m
.	ds #F .3m
.	ds #[ \f1
.	ds #] \fP
.\}
.if t \{\
.	ds #H ((1u-(\\\\n(.fu%2u))*.13m)
.	ds #V .6m
.	ds #F 0
.	ds #[ \&
.	ds #] \&
.\}
.	\" simple accents for nroff and troff
.if n \{\
.	ds ' \&
.	ds ` \&
.	ds ^ \&
.	ds , \&
.	ds ~ ~
.	ds ? ?
.	ds ! !
.	ds /
.	ds q
.\}
.if t \{\
.	ds ' \\k:\h'-(\\n(.wu*8/10-\*(#H)'\'\h"|\\n:u"
.	ds ` \\k:\h'-(\\n(.wu*8/10-\*(#H)'\`\h'|\\n:u'
.	ds ^ \\k:\h'-(\\n(.wu*10/11-\*(#H)'^\h'|\\n:u'
.	ds , \\k:\h'-(\\n(.wu*8/10)',\h'|\\n:u'
.	ds ~ \\k:\h'-(\\n(.wu-\*(#H-.1m)'~\h'|\\n:u'
.	ds ? \s-2c\h'-\w'c'u*7/10'\u\h'\*(#H'\zi\d\s+2\h'\w'c'u*8/10'
.	ds ! \s-2\(or\s+2\h'-\w'\(or'u'\v'-.8m'.\v'.8m'
.	ds / \\k:\h'-(\\n(.wu*8/10-\*(#H)'\z\(sl\h'|\\n:u'
.	ds q o\h'-\w'o'u*8/10'\s-4\v'.4m'\z\(*i\v'-.4m'\s+4\h'\w'o'u*8/10'
.\}
.	\" troff and (daisy-wheel) nroff accents
.ds : \\k:\h'-(\\n(.wu*8/10-\*(#H+.1m+\*(#F)'\v'-\*(#V'\z.\h'.2m+\*(#F'.\h'|\\n:u'\v'\*(#V'
.ds 8 \h'\*(#H'\(*b\h'-\*(#H'
.ds v \\k:\h'-(\\n(.wu*9/10-\*(#H)'\v'-\*(#V'\*(#[\s-4v\s0\v'\*(#V'\h'|\\n:u'\*(#]
.ds _ \\k:\h'-(\\n(.wu*9/10-\*(#H+(\*(#F*2/3))'\v'-.4m'\z\(hy\v'.4m'\h'|\\n:u'
.ds . \\k:\h'-(\\n(.wu*8/10)'\v'\*(#V*4/10'\z.\v'-\*(#V*4/10'\h'|\\n:u'
.ds 3 \*(#[\v'.2m'\s-2\&3\s0\v'-.2m'\*(#]
.ds o \\k:\h'-(\\n(.wu+\w'\(de'u-\*(#H)/2u'\v'-.3n'\*(#[\z\(de\v'.3n'\h'|\\n:u'\*(#]
.ds d- \h'\*(#H'\(pd\h'-\w'~'u'\v'-.25m'\f2\(hy\fP\v'.25m'\h'-\*(#H'
.ds D- D\\k:\h'-\w'D'u'\v'-.11m'\z\(hy\v'.11m'\h'|\\n:u'
.ds th \*(#[\v'.3m'\s+1I\s-1\v'-.3m'\h'-(\w'I'u*2/3)'\s-1o\s+1\*(#]
.ds Th \*(#[\s+2I\s-2\h'-\w'I'u*3/5'\v'-.3m'o\v'.3m'\*(#]
.ds ae a\h'-(\w'a'u*4/10)'e
.ds Ae A\h'-(\w'A'u*4/10)'E
.ds oe o\h'-(\w'o'u*4/10)'e
.ds Oe O\h'-(\w'O'u*4/10)'E
.	\" corrections for vroff
.if v .ds ~ \\k:\h'-(\\n(.wu*9/10-\*(#H)'\s-2\u~\d\s+2\h'|\\n:u'
.if v .ds ^ \\k:\h'-(\\n(.wu*10/11-\*(#H)'\v'-.4m'^\v'.4m'\h'|\\n:u'
.	\" for low resolution devices (crt and lpr)
.if \n(.H>23 .if \n(.V>19 \
\{\
.	ds : e
.	ds 8 ss
.	ds v \h'-1'\o'\(aa\(ga'
.	ds _ \h'-1'^
.	ds . \h'-1'.
.	ds 3 3
.	ds o a
.	ds d- d\h'-1'\(ga
.	ds D- D\h'-1'\(hy
.	ds th \o'bp'
.	ds Th \o'LP'
.	ds ae ae
.	ds Ae AE
.	ds oe oe
.	ds Oe OE
.\}
.rm #[ #] #H #V #F C
.SH "NAME"
.IX Header "NAME"
a2p \- Awk to Perl translator
.SH "SYNOPSIS"
.IX Header "SYNOPSIS"
\fBa2p [options] filename\fR
.SH "DESCRIPTION"
.IX Header "DESCRIPTION"
\fIA2p\fR takes an awk script specified on the command line (or from
standard input) and produces a comparable \fIperl\fR script on the
standard output.
.Sh "Options"
.IX Subsection "Options"
Options include:
.Ip "\fB\-D<number>\fR" 5
.IX Item "\fB\-D<number>\fR"
sets debugging flags.
.Ip "\fB\-F<character>\fR" 5
.IX Item "\fB\-F<character>\fR"
tells a2p that this awk script is always invoked with this \fB\-F\fR
switch.
.Ip "\fB\-n<fieldlist>\fR" 5
.IX Item "\fB\-n<fieldlist>\fR"
specifies the names of the input fields if input does not have to be
split into an array.  If you were translating an awk script that
processes the password file, you might say:
.Sp
.Vb 1
\&        a2p -7 -nlogin.password.uid.gid.gcos.shell.home
.Ve
Any delimiter can be used to separate the field names.
.Ip "\fB\-<number>\fR" 5
.IX Item "\fB\-<number>\fR"
causes a2p to assume that input will always have that many fields.
.Ip "\fB\-o\fR" 5
.IX Item "\fB\-o\fR"
tells a2p to use old awk behavior.  For now, the only difference is
that old awk always has a line loop, even if there are no line
actions, whereas new awk does not.
.Sh "\*(M"Considerations\*(S""
.IX Subsection "\*(M"Considerations\*(S""
A2p cannot do as good a job translating as a human would, but it
usually does pretty well.  There are some areas where you may want to
examine the perl script produced and tweak it some.  Here are some of
them, in no particular order.
.PP
There is an awk idiom of putting \fIint()\fR around a string expression to
force numeric interpretation, even though the argument is always
integer anyway.  This is generally unneeded in perl, but a2p can't
tell if the argument is always going to be integer, so it leaves it
in.  You may wish to remove it.
.PP
Perl differentiates numeric comparison from string comparison.  Awk
has one operator for both that decides at run time which comparison to
do.  A2p does not try to do a complete job of awk emulation at this
point.  Instead it guesses which one you want.  It's almost always
right, but it can be spoofed.  All such guesses are marked with the
comment \*(L"\f(CW#???\fR\*(R".  You should go through and check them.  You might
want to run at least once with the \fB\-w\fR switch to perl, which will
warn you if you use == where you should have used eq.
.PP
Perl does not attempt to emulate the behavior of awk in which
nonexistent array elements spring into existence simply by being
referenced.  If somehow you are relying on this mechanism to create
null entries for a subsequent for...in, they won't be there in perl.
.PP
If a2p makes a split line that assigns to a list of variables that
looks like (Fld1, Fld2, Fld3...) you may want to rerun a2p using the
\fB\-n\fR option mentioned above.  This will let you name the fields
throughout the script.  If it splits to an array instead, the script
is probably referring to the number of fields somewhere.
.PP
The exit statement in awk doesn't necessarily exit; it goes to the \s-1END\s0
block if there is one.  Awk scripts that do contortions within the \s-1END\s0
block to bypass the block under such circumstances can be simplified
by removing the conditional in the \s-1END\s0 block and just exiting directly
from the perl script.
.PP
Perl has two kinds of array, numerically-indexed and associative.
Perl associative arrays are called \*(L"hashes\*(R".  Awk arrays are usually
translated to hashes, but if you happen to know that the index is
always going to be numeric you could change the {...} to [...].
Iteration over a hash is done using the \fIkeys()\fR function, but iteration
over an array is \s-1NOT\s0.  You might need to modify any loop that iterates
over such an array.
.PP
Awk starts by assuming \s-1OFMT\s0 has the value %.6g.  Perl starts by
assuming its equivalent, $#, to have the value %.20g.  You'll want to
set $# explicitly if you use the default value of \s-1OFMT\s0.
.PP
Near the top of the line loop will be the split operation that is
implicit in the awk script.  There are times when you can move this
down past some conditionals that test the entire record so that the
split is not done as often.
.PP
For aesthetic reasons you may wish to change the array base $[ from 1
back to perl's default of 0, but remember to change all array
subscripts \s-1AND\s0 all \fIsubstr()\fR and \fIindex()\fR operations to match.
.PP
Cute comments that say \*(L"# Here is a workaround because awk is dumb\*(R"
are passed through unmodified.
.PP
Awk scripts are often embedded in a shell script that pipes stuff into
and out of awk.  Often the shell script wrapper can be incorporated
into the perl script, since perl can start up pipes into and out of
itself, and can do other things that awk can't do by itself.
.PP
Scripts that refer to the special variables \s-1RSTART\s0 and \s-1RLENGTH\s0 can
often be simplified by referring to the variables $`, $& and $\*(R', as
long as they are within the scope of the pattern match that sets them.
.PP
The produced perl script may have subroutines defined to deal with
awk's semantics regarding getline and print.  Since a2p usually picks
correctness over efficiency.  it is almost always possible to rewrite
such code to be more efficient by discarding the semantic sugar.
.PP
For efficiency, you may wish to remove the keyword from any return
statement that is the last statement executed in a subroutine.  A2p
catches the most common case, but doesn't analyze embedded blocks for
subtler cases.
.PP
\s-1ARGV\s0[0] translates to \f(CW$ARGV0\fR, but \s-1ARGV\s0[n] translates to \f(CW$ARGV\fR[$n].  A
loop that tries to iterate over \s-1ARGV\s0[0] won't find it.
.SH "ENVIRONMENT"
.IX Header "ENVIRONMENT"
A2p uses no environment variables.
.SH "AUTHOR"
.IX Header "AUTHOR"
Larry Wall <\fIlarry@wall.org\fR>
.SH "FILES"
.IX Header "FILES"
.SH "SEE ALSO"
.IX Header "SEE ALSO"
.PP
.Vb 3
\& perl   The perl compiler/interpreter
\& 
\& s2p    sed to perl translator
.Ve
.SH "DIAGNOSTICS"
.IX Header "DIAGNOSTICS"
.SH "BUGS"
.IX Header "BUGS"
It would be possible to emulate awk's behavior in selecting string
versus numeric operations at run time by inspection of the operands,
but it would be gross and inefficient.  Besides, a2p almost always
guesses right.
.PP
Storage for the awk syntax tree is currently static, and can run out.

.rn }` ''
