.rn '' }`
''' $RCSfile$$Revision$$Date$
'''
''' $Log$
'''
.de Sh
.br
.if t .Sp
.ne 5
.PP
\fB\\$1\fR
.PP
..
.de Sp
.if t .sp .5v
.if n .sp
..
.de Ip
.br
.ie \\n(.$>=3 .ne \\$3
.el .ne 3
.IP "\\$1" \\$2
..
.de Vb
.ft CW
.nf
.ne \\$1
..
.de Ve
.ft R

.fi
..
'''
'''
'''     Set up \*(-- to give an unbreakable dash;
'''     string Tr holds user defined translation string.
'''     Bell System Logo is used as a dummy character.
'''
.tr \(*W-|\(bv\*(Tr
.ie n \{\
.ds -- \(*W-
.ds PI pi
.if (\n(.H=4u)&(1m=24u) .ds -- \(*W\h'-12u'\(*W\h'-12u'-\" diablo 10 pitch
.if (\n(.H=4u)&(1m=20u) .ds -- \(*W\h'-12u'\(*W\h'-8u'-\" diablo 12 pitch
.ds L" ""
.ds R" ""
'''   \*(M", \*(S", \*(N" and \*(T" are the equivalent of
'''   \*(L" and \*(R", except that they are used on ".xx" lines,
'''   such as .IP and .SH, which do another additional levels of
'''   double-quote interpretation
.ds M" """
.ds S" """
.ds N" """""
.ds T" """""
.ds L' '
.ds R' '
.ds M' '
.ds S' '
.ds N' '
.ds T' '
'br\}
.el\{\
.ds -- \(em\|
.tr \*(Tr
.ds L" ``
.ds R" ''
.ds M" ``
.ds S" ''
.ds N" ``
.ds T" ''
.ds L' `
.ds R' '
.ds M' `
.ds S' '
.ds N' `
.ds T' '
.ds PI \(*p
'br\}
.\"	If the F register is turned on, we'll generate
.\"	index entries out stderr for the following things:
.\"		TH	Title 
.\"		SH	Header
.\"		Sh	Subsection 
.\"		Ip	Item
.\"		X<>	Xref  (embedded
.\"	Of course, you have to process the output yourself
.\"	in some meaninful fashion.
.if \nF \{
.de IX
.tm Index:\\$1\t\\n%\t"\\$2"
..
.nr % 0
.rr F
.\}
.TH PERLLOL 1 "perl 5.005, patch 53" "14/Jun/98" "Perl Programmers Reference Guide"
.UC
.if n .hy 0
.if n .na
.ds C+ C\v'-.1v'\h'-1p'\s-2+\h'-1p'+\s0\v'.1v'\h'-1p'
.de CQ          \" put $1 in typewriter font
.ft CW
'if n "\c
'if t \\&\\$1\c
'if n \\&\\$1\c
'if n \&"
\\&\\$2 \\$3 \\$4 \\$5 \\$6 \\$7
'.ft R
..
.\" @(#)ms.acc 1.5 88/02/08 SMI; from UCB 4.2
.	\" AM - accent mark definitions
.bd B 3
.	\" fudge factors for nroff and troff
.if n \{\
.	ds #H 0
.	ds #V .8m
.	ds #F .3m
.	ds #[ \f1
.	ds #] \fP
.\}
.if t \{\
.	ds #H ((1u-(\\\\n(.fu%2u))*.13m)
.	ds #V .6m
.	ds #F 0
.	ds #[ \&
.	ds #] \&
.\}
.	\" simple accents for nroff and troff
.if n \{\
.	ds ' \&
.	ds ` \&
.	ds ^ \&
.	ds , \&
.	ds ~ ~
.	ds ? ?
.	ds ! !
.	ds /
.	ds q
.\}
.if t \{\
.	ds ' \\k:\h'-(\\n(.wu*8/10-\*(#H)'\'\h"|\\n:u"
.	ds ` \\k:\h'-(\\n(.wu*8/10-\*(#H)'\`\h'|\\n:u'
.	ds ^ \\k:\h'-(\\n(.wu*10/11-\*(#H)'^\h'|\\n:u'
.	ds , \\k:\h'-(\\n(.wu*8/10)',\h'|\\n:u'
.	ds ~ \\k:\h'-(\\n(.wu-\*(#H-.1m)'~\h'|\\n:u'
.	ds ? \s-2c\h'-\w'c'u*7/10'\u\h'\*(#H'\zi\d\s+2\h'\w'c'u*8/10'
.	ds ! \s-2\(or\s+2\h'-\w'\(or'u'\v'-.8m'.\v'.8m'
.	ds / \\k:\h'-(\\n(.wu*8/10-\*(#H)'\z\(sl\h'|\\n:u'
.	ds q o\h'-\w'o'u*8/10'\s-4\v'.4m'\z\(*i\v'-.4m'\s+4\h'\w'o'u*8/10'
.\}
.	\" troff and (daisy-wheel) nroff accents
.ds : \\k:\h'-(\\n(.wu*8/10-\*(#H+.1m+\*(#F)'\v'-\*(#V'\z.\h'.2m+\*(#F'.\h'|\\n:u'\v'\*(#V'
.ds 8 \h'\*(#H'\(*b\h'-\*(#H'
.ds v \\k:\h'-(\\n(.wu*9/10-\*(#H)'\v'-\*(#V'\*(#[\s-4v\s0\v'\*(#V'\h'|\\n:u'\*(#]
.ds _ \\k:\h'-(\\n(.wu*9/10-\*(#H+(\*(#F*2/3))'\v'-.4m'\z\(hy\v'.4m'\h'|\\n:u'
.ds . \\k:\h'-(\\n(.wu*8/10)'\v'\*(#V*4/10'\z.\v'-\*(#V*4/10'\h'|\\n:u'
.ds 3 \*(#[\v'.2m'\s-2\&3\s0\v'-.2m'\*(#]
.ds o \\k:\h'-(\\n(.wu+\w'\(de'u-\*(#H)/2u'\v'-.3n'\*(#[\z\(de\v'.3n'\h'|\\n:u'\*(#]
.ds d- \h'\*(#H'\(pd\h'-\w'~'u'\v'-.25m'\f2\(hy\fP\v'.25m'\h'-\*(#H'
.ds D- D\\k:\h'-\w'D'u'\v'-.11m'\z\(hy\v'.11m'\h'|\\n:u'
.ds th \*(#[\v'.3m'\s+1I\s-1\v'-.3m'\h'-(\w'I'u*2/3)'\s-1o\s+1\*(#]
.ds Th \*(#[\s+2I\s-2\h'-\w'I'u*3/5'\v'-.3m'o\v'.3m'\*(#]
.ds ae a\h'-(\w'a'u*4/10)'e
.ds Ae A\h'-(\w'A'u*4/10)'E
.ds oe o\h'-(\w'o'u*4/10)'e
.ds Oe O\h'-(\w'O'u*4/10)'E
.	\" corrections for vroff
.if v .ds ~ \\k:\h'-(\\n(.wu*9/10-\*(#H)'\s-2\u~\d\s+2\h'|\\n:u'
.if v .ds ^ \\k:\h'-(\\n(.wu*10/11-\*(#H)'\v'-.4m'^\v'.4m'\h'|\\n:u'
.	\" for low resolution devices (crt and lpr)
.if \n(.H>23 .if \n(.V>19 \
\{\
.	ds : e
.	ds 8 ss
.	ds v \h'-1'\o'\(aa\(ga'
.	ds _ \h'-1'^
.	ds . \h'-1'.
.	ds 3 3
.	ds o a
.	ds d- d\h'-1'\(ga
.	ds D- D\h'-1'\(hy
.	ds th \o'bp'
.	ds Th \o'LP'
.	ds ae ae
.	ds Ae AE
.	ds oe oe
.	ds Oe OE
.\}
.rm #[ #] #H #V #F C
.SH "NAME"
perlLoL \- Manipulating Lists of Lists in Perl
.SH "DESCRIPTION"
.SH "Declaration and Access of Lists of Lists"
The simplest thing to build is a list of lists (sometimes called an array
of arrays).  It's reasonably easy to understand, and almost everything
that applies here will also be applicable later on with the fancier data
structures.
.PP
A list of lists, or an array of an array if you would, is just a regular
old array \f(CW@LoL\fR that you can get at with two subscripts, like \f(CW$LoL[3][2]\fR.  Here's
a declaration of the array:
.PP
.Vb 6
\&    # assign to our array a list of list references
\&    @LoL = (
\&           [ "fred", "barney" ],
\&           [ "george", "jane", "elroy" ],
\&           [ "homer", "marge", "bart" ],
\&    );
.Ve
.Vb 2
\&    print $LoL[2][2];
\&  bart
.Ve
Now you should be very careful that the outer bracket type
is a round one, that is, a parenthesis.  That's because you're assigning to
an \f(CW@list\fR, so you need parentheses.  If you wanted there \fInot\fR to be an \f(CW@LoL\fR,
but rather just a reference to it, you could do something more like this:
.PP
.Vb 6
\&    # assign a reference to list of list references
\&    $ref_to_LoL = [
\&        [ "fred", "barney", "pebbles", "bambam", "dino", ],
\&        [ "homer", "bart", "marge", "maggie", ],
\&        [ "george", "jane", "alroy", "judy", ],
\&    ];
.Ve
.Vb 1
\&    print $ref_to_LoL->[2][2];
.Ve
Notice that the outer bracket type has changed, and so our access syntax
has also changed.  That's because unlike C, in perl you can't freely
interchange arrays and references thereto.  \f(CW$ref_to_LoL\fR is a reference to an
array, whereas \f(CW@LoL\fR is an array proper.  Likewise, \f(CW$LoL[2]\fR is not an
array, but an array ref.  So how come you can write these:
.PP
.Vb 2
\&    $LoL[2][2]
\&    $ref_to_LoL->[2][2]
.Ve
instead of having to write these:
.PP
.Vb 2
\&    $LoL[2]->[2]
\&    $ref_to_LoL->[2]->[2]
.Ve
Well, that's because the rule is that on adjacent brackets only (whether
square or curly), you are free to omit the pointer dereferencing arrow.
But you cannot do so for the very first one if it's a scalar containing
a reference, which means that \f(CW$ref_to_LoL\fR always needs it.
.SH "Growing Your Own"
That's all well and good for declaration of a fixed data structure,
but what if you wanted to add new elements on the fly, or build
it up entirely from scratch?
.PP
First, let's look at reading it in from a file.  This is something like
adding a row at a time.  We'll assume that there's a flat file in which
each line is a row and each word an element.  If you're trying to develop an
\f(CW@LoL\fR list containing all these, here's the right way to do that:
.PP
.Vb 4
\&    while (<>) {
\&        @tmp = split;
\&        push @LoL, [ @tmp ];
\&    }
.Ve
You might also have loaded that from a function:
.PP
.Vb 3
\&    for $i ( 1 .. 10 ) {
\&        $LoL[$i] = [ somefunc($i) ];
\&    }
.Ve
Or you might have had a temporary variable sitting around with the
list in it.
.PP
.Vb 4
\&    for $i ( 1 .. 10 ) {
\&        @tmp = somefunc($i);
\&        $LoL[$i] = [ @tmp ];
\&    }
.Ve
It's very important that you make sure to use the \f(CW[]\fR list reference
constructor.  That's because this will be very wrong:
.PP
.Vb 1
\&    $LoL[$i] = @tmp;
.Ve
You see, assigning a named list like that to a scalar just counts the
number of elements in \f(CW@tmp\fR, which probably isn't what you want.
.PP
If you are running under \f(CWuse strict\fR, you'll have to add some
declarations to make it happy:
.PP
.Vb 6
\&    use strict;
\&    my(@LoL, @tmp);
\&    while (<>) {
\&        @tmp = split;
\&        push @LoL, [ @tmp ];
\&    }
.Ve
Of course, you don't need the temporary array to have a name at all:
.PP
.Vb 3
\&    while (<>) {
\&        push @LoL, [ split ];
\&    }
.Ve
You also don't have to use \fIpush()\fR.  You could just make a direct assignment
if you knew where you wanted to put it:
.PP
.Vb 5
\&    my (@LoL, $i, $line);
\&    for $i ( 0 .. 10 ) {
\&        $line = <>;
\&        $LoL[$i] = [ split ' ', $line ];
\&    }
.Ve
or even just
.PP
.Vb 4
\&    my (@LoL, $i);
\&    for $i ( 0 .. 10 ) {
\&        $LoL[$i] = [ split ' ', <> ];
\&    }
.Ve
You should in general be leery of using potential list functions
in a scalar context without explicitly stating such.
This would be clearer to the casual reader:
.PP
.Vb 4
\&    my (@LoL, $i);
\&    for $i ( 0 .. 10 ) {
\&        $LoL[$i] = [ split ' ', scalar(<>) ];
\&    }
.Ve
If you wanted to have a \f(CW$ref_to_LoL\fR variable as a reference to an array,
you'd have to do something like this:
.PP
.Vb 3
\&    while (<>) {
\&        push @$ref_to_LoL, [ split ];
\&    }
.Ve
Now you can add new rows.  What about adding new columns?  If you're
dealing with just matrices, it's often easiest to use simple assignment:
.PP
.Vb 5
\&    for $x (1 .. 10) {
\&        for $y (1 .. 10) {
\&            $LoL[$x][$y] = func($x, $y);
\&        }
\&    }
.Ve
.Vb 3
\&    for $x ( 3, 7, 9 ) {
\&        $LoL[$x][20] += func2($x);
\&    }
.Ve
It doesn't matter whether those elements are already
there or not: it'll gladly create them for you, setting
intervening elements to \f(CWundef\fR as need be.
.PP
If you wanted just to append to a row, you'd have
to do something a bit funnier looking:
.PP
.Vb 2
\&    # add new columns to an existing row
\&    push @{ $LoL[0] }, "wilma", "betty";
.Ve
Notice that I \fIcouldn't\fR say just:
.PP
.Vb 1
\&    push $LoL[0], "wilma", "betty";  # WRONG!
.Ve
In fact, that wouldn't even compile.  How come?  Because the argument
to \fIpush()\fR must be a real array, not just a reference to such.
.SH "Access and Printing"
Now it's time to print your data structure out.  How
are you going to do that?  Well, if you want only one
of the elements, it's trivial:
.PP
.Vb 1
\&    print $LoL[0][0];
.Ve
If you want to print the whole thing, though, you can't
say
.PP
.Vb 1
\&    print @LoL;         # WRONG
.Ve
because you'll get just references listed, and perl will never
automatically dereference things for you.  Instead, you have to
roll yourself a loop or two.  This prints the whole structure,
using the shell-style \fIfor()\fR construct to loop across the outer
set of subscripts.
.PP
.Vb 3
\&    for $aref ( @LoL ) {
\&        print "\et [ @$aref ],\en";
\&    }
.Ve
If you wanted to keep track of subscripts, you might do this:
.PP
.Vb 3
\&    for $i ( 0 .. $#LoL ) {
\&        print "\et elt $i is [ @{$LoL[$i]} ],\en";
\&    }
.Ve
or maybe even this.  Notice the inner loop.
.PP
.Vb 5
\&    for $i ( 0 .. $#LoL ) {
\&        for $j ( 0 .. $#{$LoL[$i]} ) {
\&            print "elt $i $j is $LoL[$i][$j]\en";
\&        }
\&    }
.Ve
As you can see, it's getting a bit complicated.  That's why
sometimes is easier to take a temporary on your way through:
.PP
.Vb 6
\&    for $i ( 0 .. $#LoL ) {
\&        $aref = $LoL[$i];
\&        for $j ( 0 .. $#{$aref} ) {
\&            print "elt $i $j is $LoL[$i][$j]\en";
\&        }
\&    }
.Ve
Hmm... that's still a bit ugly.  How about this:
.PP
.Vb 7
\&    for $i ( 0 .. $#LoL ) {
\&        $aref = $LoL[$i];
\&        $n = @$aref - 1;
\&        for $j ( 0 .. $n ) {
\&            print "elt $i $j is $LoL[$i][$j]\en";
\&        }
\&    }
.Ve
.SH "Slices"
If you want to get at a slice (part of a row) in a multidimensional
array, you're going to have to do some fancy subscripting.  That's
because while we have a nice synonym for single elements via the
pointer arrow for dereferencing, no such convenience exists for slices.
(Remember, of course, that you can always write a loop to do a slice
operation.)
.PP
Here's how to do one operation using a loop.  We'll assume an \f(CW@LoL\fR
variable as before.
.PP
.Vb 5
\&    @part = ();
\&    $x = 4;
\&    for ($y = 7; $y < 13; $y++) {
\&        push @part, $LoL[$x][$y];
\&    }
.Ve
That same loop could be replaced with a slice operation:
.PP
.Vb 1
\&    @part = @{ $LoL[4] } [ 7..12 ];
.Ve
but as you might well imagine, this is pretty rough on the reader.
.PP
Ah, but what if you wanted a \fItwo-dimensional slice\fR, such as having
\f(CW$x\fR run from 4..8 and \f(CW$y\fR run from 7 to 12?  Hmm... here's the simple way:
.PP
.Vb 6
\&    @newLoL = ();
\&    for ($startx = $x = 4; $x <= 8; $x++) {
\&        for ($starty = $y = 7; $y <= 12; $y++) {
\&            $newLoL[$x - $startx][$y - $starty] = $LoL[$x][$y];
\&        }
\&    }
.Ve
We can reduce some of the looping through slices
.PP
.Vb 3
\&    for ($x = 4; $x <= 8; $x++) {
\&        push @newLoL, [ @{ $LoL[$x] } [ 7..12 ] ];
\&    }
.Ve
If you were into Schwartzian Transforms, you would probably
have selected map for that
.PP
.Vb 1
\&    @newLoL = map { [ @{ $LoL[$_] } [ 7..12 ] ] } 4 .. 8;
.Ve
Although if your manager accused of seeking job security (or rapid
insecurity) through inscrutable code, it would be hard to argue. :\-)
If I were you, I'd put that in a function:
.PP
.Vb 5
\&    @newLoL = splice_2D( \e@LoL, 4 => 8, 7 => 12 );
\&    sub splice_2D {
\&        my $lrr = shift;        # ref to list of list refs!
\&        my ($x_lo, $x_hi,
\&            $y_lo, $y_hi) = @_;
.Ve
.Vb 4
\&        return map {
\&            [ @{ $lrr->[$_] } [ $y_lo .. $y_hi ] ]
\&        } $x_lo .. $x_hi;
\&    }
.Ve
.SH "SEE ALSO"
\fIperldata\fR\|(1), \fIperlref\fR\|(1), \fIperldsc\fR\|(1)
.SH "AUTHOR"
Tom Christiansen <\fItchrist@perl.com\fR>
.PP
Last update: Thu Jun  4 16:16:23 MDT 1998

.rn }` ''
.IX Title "PERLLOL 1"
.IX Name "perlLoL - Manipulating Lists of Lists in Perl"

.IX Header "NAME"

.IX Header "DESCRIPTION"

.IX Header "Declaration and Access of Lists of Lists"

.IX Header "Growing Your Own"

.IX Header "Access and Printing"

.IX Header "Slices"

.IX Header "SEE ALSO"

.IX Header "AUTHOR"

