.rn '' }`
''' $RCSfile$$Revision$$Date$
'''
''' $Log$
'''
.de Sh
.br
.if t .Sp
.ne 5
.PP
\fB\\$1\fR
.PP
..
.de Sp
.if t .sp .5v
.if n .sp
..
.de Ip
.br
.ie \\n(.$>=3 .ne \\$3
.el .ne 3
.IP "\\$1" \\$2
..
.de Vb
.ft CW
.nf
.ne \\$1
..
.de Ve
.ft R

.fi
..
'''
'''
'''     Set up \*(-- to give an unbreakable dash;
'''     string Tr holds user defined translation string.
'''     Bell System Logo is used as a dummy character.
'''
.tr \(*W-|\(bv\*(Tr
.ie n \{\
.ds -- \(*W-
.ds PI pi
.if (\n(.H=4u)&(1m=24u) .ds -- \(*W\h'-12u'\(*W\h'-12u'-\" diablo 10 pitch
.if (\n(.H=4u)&(1m=20u) .ds -- \(*W\h'-12u'\(*W\h'-8u'-\" diablo 12 pitch
.ds L" ""
.ds R" ""
.ds L' '
.ds R' '
'br\}
.el\{\
.ds -- \(em\|
.tr \*(Tr
.ds L" ``
.ds R" ''
.ds L' `
.ds R' '
.ds PI \(*p
'br\}
.\"	If the F register is turned on, we'll generate
.\"	index entries out stderr for the following things:
.\"		TH	Title 
.\"		SH	Header
.\"		Sh	Subsection 
.\"		Ip	Item
.\"		X<>	Xref  (embedded
.\"	Of course, you have to process the output yourself
.\"	in some meaninful fashion.
.if \nF \{
.de IX
.tm Index:\\$1\t\\n%\t"\\$2"
..
.nr % 0
.rr F
.\}
.TH PERLTRAP 1 "perl 5.003, patch 05" "9/Sep/96" "Perl Programmers Reference Guide"
.IX Title "PERLTRAP 1"
.UC
.IX Name "perltrap - Perl traps for the unwary"
.if n .hy 0
.if n .na
.ds C+ C\v'-.1v'\h'-1p'\s-2+\h'-1p'+\s0\v'.1v'\h'-1p'
.de CQ          \" put $1 in typewriter font
.ft CW
'if n "\c
'if t \\&\\$1\c
'if n \\&\\$1\c
'if n \&"
\\&\\$2 \\$3 \\$4 \\$5 \\$6 \\$7
'.ft R
..
.\" @(#)ms.acc 1.5 88/02/08 SMI; from UCB 4.2
.	\" AM - accent mark definitions
.bd B 3
.	\" fudge factors for nroff and troff
.if n \{\
.	ds #H 0
.	ds #V .8m
.	ds #F .3m
.	ds #[ \f1
.	ds #] \fP
.\}
.if t \{\
.	ds #H ((1u-(\\\\n(.fu%2u))*.13m)
.	ds #V .6m
.	ds #F 0
.	ds #[ \&
.	ds #] \&
.\}
.	\" simple accents for nroff and troff
.if n \{\
.	ds ' \&
.	ds ` \&
.	ds ^ \&
.	ds , \&
.	ds ~ ~
.	ds ? ?
.	ds ! !
.	ds /
.	ds q
.\}
.if t \{\
.	ds ' \\k:\h'-(\\n(.wu*8/10-\*(#H)'\'\h"|\\n:u"
.	ds ` \\k:\h'-(\\n(.wu*8/10-\*(#H)'\`\h'|\\n:u'
.	ds ^ \\k:\h'-(\\n(.wu*10/11-\*(#H)'^\h'|\\n:u'
.	ds , \\k:\h'-(\\n(.wu*8/10)',\h'|\\n:u'
.	ds ~ \\k:\h'-(\\n(.wu-\*(#H-.1m)'~\h'|\\n:u'
.	ds ? \s-2c\h'-\w'c'u*7/10'\u\h'\*(#H'\zi\d\s+2\h'\w'c'u*8/10'
.	ds ! \s-2\(or\s+2\h'-\w'\(or'u'\v'-.8m'.\v'.8m'
.	ds / \\k:\h'-(\\n(.wu*8/10-\*(#H)'\z\(sl\h'|\\n:u'
.	ds q o\h'-\w'o'u*8/10'\s-4\v'.4m'\z\(*i\v'-.4m'\s+4\h'\w'o'u*8/10'
.\}
.	\" troff and (daisy-wheel) nroff accents
.ds : \\k:\h'-(\\n(.wu*8/10-\*(#H+.1m+\*(#F)'\v'-\*(#V'\z.\h'.2m+\*(#F'.\h'|\\n:u'\v'\*(#V'
.ds 8 \h'\*(#H'\(*b\h'-\*(#H'
.ds v \\k:\h'-(\\n(.wu*9/10-\*(#H)'\v'-\*(#V'\*(#[\s-4v\s0\v'\*(#V'\h'|\\n:u'\*(#]
.ds _ \\k:\h'-(\\n(.wu*9/10-\*(#H+(\*(#F*2/3))'\v'-.4m'\z\(hy\v'.4m'\h'|\\n:u'
.ds . \\k:\h'-(\\n(.wu*8/10)'\v'\*(#V*4/10'\z.\v'-\*(#V*4/10'\h'|\\n:u'
.ds 3 \*(#[\v'.2m'\s-2\&3\s0\v'-.2m'\*(#]
.ds o \\k:\h'-(\\n(.wu+\w'\(de'u-\*(#H)/2u'\v'-.3n'\*(#[\z\(de\v'.3n'\h'|\\n:u'\*(#]
.ds d- \h'\*(#H'\(pd\h'-\w'~'u'\v'-.25m'\f2\(hy\fP\v'.25m'\h'-\*(#H'
.ds D- D\\k:\h'-\w'D'u'\v'-.11m'\z\(hy\v'.11m'\h'|\\n:u'
.ds th \*(#[\v'.3m'\s+1I\s-1\v'-.3m'\h'-(\w'I'u*2/3)'\s-1o\s+1\*(#]
.ds Th \*(#[\s+2I\s-2\h'-\w'I'u*3/5'\v'-.3m'o\v'.3m'\*(#]
.ds ae a\h'-(\w'a'u*4/10)'e
.ds Ae A\h'-(\w'A'u*4/10)'E
.ds oe o\h'-(\w'o'u*4/10)'e
.ds Oe O\h'-(\w'O'u*4/10)'E
.	\" corrections for vroff
.if v .ds ~ \\k:\h'-(\\n(.wu*9/10-\*(#H)'\s-2\u~\d\s+2\h'|\\n:u'
.if v .ds ^ \\k:\h'-(\\n(.wu*10/11-\*(#H)'\v'-.4m'^\v'.4m'\h'|\\n:u'
.	\" for low resolution devices (crt and lpr)
.if \n(.H>23 .if \n(.V>19 \
\{\
.	ds : e
.	ds 8 ss
.	ds v \h'-1'\o'\(aa\(ga'
.	ds _ \h'-1'^
.	ds . \h'-1'.
.	ds 3 3
.	ds o a
.	ds d- d\h'-1'\(ga
.	ds D- D\h'-1'\(hy
.	ds th \o'bp'
.	ds Th \o'LP'
.	ds ae ae
.	ds Ae AE
.	ds oe oe
.	ds Oe OE
.\}
.rm #[ #] #H #V #F C
.SH "NAME"
.IX Header "NAME"
perltrap \- Perl traps for the unwary
.SH "DESCRIPTION"
.IX Header "DESCRIPTION"
The biggest trap of all is forgetting to use the \fB\-w\fR switch; see
the \fIperlrun\fR manpage.  The second biggest trap is not making your entire program
runnable under \f(CWuse strict\fR.
.Sh "Awk Traps"
.IX Subsection "Awk Traps"
Accustomed \fBawk\fR users should take special note of the following:
.Ip "\(bu" 4
.IX Item "\(bu"
The English module, loaded via
.Sp
.Vb 1
\&    use English;
.Ve
allows you to refer to special variables (like \f(CW$RS\fR) as 
though they were in \fBawk\fR; see the \fIperlvar\fR manpage for details.
.Ip "\(bu" 4
.IX Item "\(bu"
Semicolons are required after all simple statements in Perl (except
at the end of a block).  Newline is not a statement delimiter.
.Ip "\(bu" 4
.IX Item "\(bu"
Curly brackets are required on \f(CWif\fRs and \f(CWwhile\fRs.
.Ip "\(bu" 4
.IX Item "\(bu"
Variables begin with \*(L"$\*(R" or \*(L"@\*(R" in Perl.
.Ip "\(bu" 4
.IX Item "\(bu"
Arrays index from 0.  Likewise string positions in \fIsubstr()\fR and
\fIindex()\fR.
.Ip "\(bu" 4
.IX Item "\(bu"
You have to decide whether your array has numeric or string indices.
.Ip "\(bu" 4
.IX Item "\(bu"
Associative array values do not spring into existence upon mere
reference.
.Ip "\(bu" 4
.IX Item "\(bu"
You have to decide whether you want to use string or numeric
comparisons.
.Ip "\(bu" 4
.IX Item "\(bu"
Reading an input line does not split it for you.  You get to split it
yourself to an array.  And the \fIsplit()\fR operator has different
arguments.
.Ip "\(bu" 4
.IX Item "\(bu"
The current input line is normally in \f(CW$_\fR, not \f(CW$0\fR.  It generally does
not have the newline stripped.  ($0 is the name of the program
executed.)  See the \fIperlvar\fR manpage.
.Ip "\(bu" 4
.IX Item "\(bu"
$<\fIdigit\fR> does not refer to fields\*(--it refers to substrings matched by
the last match pattern.
.Ip "\(bu" 4
.IX Item "\(bu"
The \fIprint()\fR statement does not add field and record separators unless
you set \f(CW$,\fR and \f(CW$.\fR.  You can set \f(CW$OFS\fR and \f(CW$ORS\fR if you're using
the English module.
.Ip "\(bu" 4
.IX Item "\(bu"
You must open your files before you print to them.
.Ip "\(bu" 4
.IX Item "\(bu"
The range operator is \*(L"..\*(R", not comma.  The comma operator works as in
C.
.Ip "\(bu" 4
.IX Item "\(bu"
The match operator is \*(L"=~\*(R", not \*(L"~\*(R".  ("~\*(R" is the one's complement
operator, as in C.)
.Ip "\(bu" 4
.IX Item "\(bu"
The exponentiation operator is \*(L"**\*(R", not \*(L"^\*(R".  \*(L"^\*(R" is the \s-1XOR\s0
operator, as in C.  (You know, one could get the feeling that \fBawk\fR is
basically incompatible with C.)
.Ip "\(bu" 4
.IX Item "\(bu"
The concatenation operator is \*(L".\*(R", not the null string.  (Using the
null string would render \f(CW/pat/ /pat/\fR unparsable, since the third slash
would be interpreted as a division operator\*(--the tokener is in fact
slightly context sensitive for operators like \*(L"/\*(R", \*(L"?\*(R", and \*(L">\*(R".
And in fact, \*(L".\*(R" itself can be the beginning of a number.)
.Ip "\(bu" 4
.IX Item "\(bu"
The \f(CWnext\fR, \f(CWexit\fR, and \f(CWcontinue\fR keywords work differently.
.Ip "\(bu" 4
.IX Item "\(bu"
The following variables work differently:
.Sp
.Vb 15
\&      Awk       Perl
\&      ARGC      $#ARGV or scalar @ARGV
\&      ARGV[0]   $0
\&      FILENAME  $ARGV
\&      FNR       $. - something
\&      FS        (whatever you like)
\&      NF        $#Fld, or some such
\&      NR        $.
\&      OFMT      $#
\&      OFS       $,
\&      ORS       $\e
\&      RLENGTH   length($&)
\&      RS        $/
\&      RSTART    length($`)
\&      SUBSEP    $;
.Ve
.Ip "\(bu" 4
.IX Item "\(bu"
You cannot set \f(CW$RS\fR to a pattern, only a string.
.Ip "\(bu" 4
.IX Item "\(bu"
When in doubt, run the \fBawk\fR construct through \fBa2p\fR and see what it
gives you.
.Sh "C Traps"
.IX Subsection "C Traps"
Cerebral C programmers should take note of the following:
.Ip "\(bu" 4
.IX Item "\(bu"
Curly brackets are required on \f(CWif\fR's and \f(CWwhile\fR's.
.Ip "\(bu" 4
.IX Item "\(bu"
You must use \f(CWelsif\fR rather than \f(CWelse if\fR.
.Ip "\(bu" 4
.IX Item "\(bu"
The \f(CWbreak\fR and \f(CWcontinue\fR keywords from C become in 
Perl \f(CWlast\fR and \f(CWnext\fR, respectively.
Unlike in C, these do \fI\s-1NOT\s0\fR work within a \f(CWdo { } while\fR construct.
.Ip "\(bu" 4
.IX Item "\(bu"
There's no switch statement.  (But it's easy to build one on the fly.)
.Ip "\(bu" 4
.IX Item "\(bu"
Variables begin with \*(L"$\*(R" or \*(L"@\*(R" in Perl.
.Ip "\(bu" 4
.IX Item "\(bu"
\f(CWprintf()\fR does not implement the \*(L"*\*(R" format for interpolating
field widths, but it's trivial to use interpolation of double-quoted
strings to achieve the same effect.
.Ip "\(bu" 4
.IX Item "\(bu"
Comments begin with \*(L"#\*(R", not \*(L"/*\*(R".
.Ip "\(bu" 4
.IX Item "\(bu"
You can't take the address of anything, although a similar operator
in Perl 5 is the backslash, which creates a reference.
.Ip "\(bu" 4
.IX Item "\(bu"
\f(CWARGV\fR must be capitalized.  \f(CW$ARGV[0]\fR is C's \f(CWargv[1]\fR, and \f(CWargv[0]\fR
ends up in \f(CW$0\fR.
.Ip "\(bu" 4
.IX Item "\(bu"
System calls such as \fIlink()\fR, \fIunlink()\fR, \fIrename()\fR, etc. return nonzero for
success, not 0.
.Ip "\(bu" 4
.IX Item "\(bu"
Signal handlers deal with signal names, not numbers.  Use \f(CWkill -l\fR
to find their names on your system.
.Sh "Sed Traps"
.IX Subsection "Sed Traps"
Seasoned \fBsed\fR programmers should take note of the following:
.Ip "\(bu" 4
.IX Item "\(bu"
Backreferences in substitutions use \*(L"$\*(R" rather than \*(L"\e\*(R".
.Ip "\(bu" 4
.IX Item "\(bu"
The pattern matching metacharacters \*(L"(\*(R", \*(L")\*(R", and \*(L"|\*(R" do not have backslashes
in front.
.Ip "\(bu" 4
.IX Item "\(bu"
The range operator is \f(CW...\fR, rather than comma.
.Sh "Shell Traps"
.IX Subsection "Shell Traps"
Sharp shell programmers should take note of the following:
.Ip "\(bu" 4
.IX Item "\(bu"
The backtick operator does variable interpolation without regard to
the presence of single quotes in the command.
.Ip "\(bu" 4
.IX Item "\(bu"
The backtick operator does no translation of the return value, unlike \fBcsh\fR.
.Ip "\(bu" 4
.IX Item "\(bu"
Shells (especially \fBcsh\fR) do several levels of substitution on each
command line.  Perl does substitution only in certain constructs
such as double quotes, backticks, angle brackets, and search patterns.
.Ip "\(bu" 4
.IX Item "\(bu"
Shells interpret scripts a little bit at a time.  Perl compiles the
entire program before executing it (except for \f(CWBEGIN\fR blocks, which
execute at compile time).
.Ip "\(bu" 4
.IX Item "\(bu"
The arguments are available via \f(CW@ARGV\fR, not \f(CW$1\fR, \f(CW$2\fR, etc.
.Ip "\(bu" 4
.IX Item "\(bu"
The environment is not automatically made available as separate scalar
variables.
.Sh "Perl Traps"
.IX Subsection "Perl Traps"
Practicing Perl Programmers should take note of the following:
.Ip "\(bu" 4
.IX Item "\(bu"
Remember that many operations behave differently in a list
context than they do in a scalar one.  See the \fIperldata\fR manpage for details.
.Ip "\(bu" 4
.IX Item "\(bu"
Avoid barewords if you can, especially all lower-case ones.
You can't tell just by looking at it whether a bareword is 
a function or a string.  By using quotes on strings and 
parens on function calls, you won't ever get them confused.
.Ip "\(bu" 4
.IX Item "\(bu"
You cannot discern from mere inspection which built-ins
are unary operators (like \fIchop()\fR and \fIchdir()\fR) 
and which are list operators (like \fIprint()\fR and \fIunlink()\fR).
(User-defined subroutines can \fBonly\fR be list operators, never
unary ones.)  See the \fIperlop\fR manpage.
.Ip "\(bu" 4
.IX Item "\(bu"
People have a hard time remembering that some functions
default to \f(CW$_\fR, or \f(CW@ARGV\fR, or whatever, but that others which
you might expect to do not.  
.Ip "\(bu" 4
.IX Item "\(bu"
The <\s-1FH\s0> construct is not the name of the filehandle, it is a readline
operation on that handle.  The data read is only assigned to \f(CW$_\fR if the
file read is the sole condition in a while loop:
.Sp
.Vb 3
\&    while (<FH>)      { }
\&    while ($_ = <FH>) { }..
\&    <FH>;  # data discarded!
.Ve
.Ip "\(bu" 4
.IX Item "\(bu"
Remember not to use \*(L"\f(CW=\fR\*(R" when you need \*(L"\f(CW=~\fR\*(R";
these two constructs are quite different:
.Sp
.Vb 2
\&    $x =  /foo/;
\&    $x =~ /foo/;
.Ve
.Ip "\(bu" 4
.IX Item "\(bu"
The \f(CWdo {}\fR construct isn't a real loop that you can use 
loop control on.
.Ip "\(bu" 4
.IX Item "\(bu"
Use \f(CWmy()\fR for local variables whenever you can get away with 
it (but see the \fIperlform\fR manpage for where you can't).  
Using \f(CWlocal()\fR actually gives a local value to a global 
variable, which leaves you open to unforeseen side-effects
of dynamic scoping.
.Ip "\(bu" 4
.IX Item "\(bu"
If you localize an exported variable in a module, its exported value will
not change.  The local name becomes an alias to a new value but the
external name is still an alias for the original.
.Sh "Perl4 to Perl5  Traps"
.IX Subsection "Perl4 to Perl5  Traps"
Practicing Perl4 Programmers should take note of the following 
Perl4-to-Perl5 specific traps.
.PP
They're crudely ordered according to the following list:
.Ip "Discontinuance, Deprecation, and BugFix traps" 4
.IX Item "Discontinuance, Deprecation, and BugFix traps"
Anything that's been fixed as a perl4 bug, removed as a perl4 feature
or deprecated as a perl4 feature with the intent to encourage usage of
some other perl5 feature.
.Ip "Parsing Traps" 4
.IX Item "Parsing Traps"
Traps that appear to stem from the new parser.
.Ip "Numerical Traps" 4
.IX Item "Numerical Traps"
Traps having to do with numerical or mathematical operators.
.Ip "General data type traps" 4
.IX Item "General data type traps"
Traps involving perl standard data types.
.Ip "Context Traps \- scalar, list contexts" 4
.IX Item "Context Traps \- scalar, list contexts"
Traps related to context within lists, scalar statements/declarations.
.Ip "Precedence Traps" 4
.IX Item "Precedence Traps"
Traps related to the precedence of parsing, evaluation, and execution of
code.
.Ip "General Regular Expression Traps using s///, etc." 4
.IX Item "General Regular Expression Traps using s///, etc."
Traps related to the use of pattern matching.
.Ip "Subroutine, Signal, Sorting Traps" 4
.IX Item "Subroutine, Signal, Sorting Traps"
Traps related to the use of signals and signal handlers, general subroutines,
and sorting, along with sorting subroutines.
.Ip "\s-1OS\s0 Traps" 4
.IX Item "\s-1OS\s0 Traps"
\s-1OS\s0\-specific traps.
.Ip "\s-1DBM\s0 Traps" 4
.IX Item "\s-1DBM\s0 Traps"
Traps specific to the use of \f(CWdbmopen()\fR, and specific dbm implementations.
.Ip "Unclassified Traps" 4
.IX Item "Unclassified Traps"
Everything else.
.PP
If you find an example of a conversion trap that is not listed here,
please submit it to Bill Middleton \fIwjm@best.com\fR for inclusion.
Also note that at least some of these can be caught with \f(CW-w\fR.
.Sh "Discontinuance, Deprecation, and BugFix traps"
.IX Subsection "Discontinuance, Deprecation, and BugFix traps"
Anything that has been discontinued, deprecated, or fixed as
a bug from perl4.  
.Ip "\(bu Discontinuance " 4
.IX Item "\(bu Discontinuance "
Symbols starting with \*(L"_\*(R" are no longer forced into package main, except
for \f(CW$_\fR itself (and \f(CW@_\fR, etc.).
.Sp
.Vb 2
\&    package test;
\&    $_legacy = 1;
.Ve
.Vb 5
\&    package main;
\&    print "\e$_legacy is ",$_legacy,"\en";
\& 
\&    # perl4 prints: $_legacy is 1
\&    # perl5 prints: $_legacy is
.Ve
.Ip "\(bu Deprecation " 4
.IX Item "\(bu Deprecation "
Double-colon is now a valid package separator in a variable name.  Thus these
behave differently in perl4 vs. perl5, since the packages don't exist.
.Sp
.Vb 6
\&    $a=1;$b=2;$c=3;$var=4;
\&    print "$a::$b::$c ";
\&    print "$var::abc::xyz\en";
\& 
\&    # perl4 prints: 1::2::3 4::abc::xyz
\&    # perl5 prints: 3
.Ve
Given that \f(CW::\fR is now the preferred package delimiter, it is debatable
whether this should be classed as a bug or not.
(The older package delimiter, \*(L' ,is used here)
.Sp
.Vb 5
\&    $x = 10 ;
\&    print "x=${'x}\en" ;
\& 
\&    # perl4 prints: x=10
\&    # perl5 prints: Can't find string terminator "'" anywhere before EOF
.Ve
Also see precedence traps, for parsing \f(CW$:\fR. 
.Ip "\(bu BugFix" 4
.IX Item "\(bu BugFix"
The second and third arguments of \f(CWsplice()\fR are now evaluated in scalar
context (as the Camel says) rather than list context.
.Sp
.Vb 8
\&    sub sub1{return(0,2) }          # return a 2-elem array
\&    sub sub2{ return(1,2,3)}        # return a 3-elem array
\&    @a1 = ("a","b","c","d","e"); 
\&    @a2 = splice(@a1,&sub1,&sub2);
\&    print join(' ',@a2),"\en";
\& 
\&    # perl4 prints: a b
\&    # perl5 prints: c d e 
.Ve
.Ip "\(bu Discontinuance " 4
.IX Item "\(bu Discontinuance "
You can't do a \f(CWgoto\fR into a block that is optimized away.  Darn.
.Sp
.Vb 1
\&    goto marker1;
.Ve
.Vb 7
\&    for(1){         
\&    marker1:
\&        print "Here I is!\en";
\&    } 
\& 
\&    # perl4 prints: Here I is!
\&    # perl5 dumps core (SEGV)
.Ve
.Ip "\(bu Discontinuance " 4
.IX Item "\(bu Discontinuance "
It is no longer syntactically legal to use whitespace as the name
of a variable, or as a delimiter for any kind of quote construct.
Double darn. 
.Sp
.Vb 6
\&    $a = ("foo bar");
\&    $b = q baz ;
\&    print "a is $a, b is $b\en";
\& 
\&    # perl4 prints: a is foo bar, b is baz
\&    # perl5 errors: Bare word found where operator expected
.Ve
.Ip "\(bu Discontinuance" 4
.IX Item "\(bu Discontinuance"
The archaic while/if \s-1BLOCK\s0 \s-1BLOCK\s0 syntax is no longer supported.
.Sp
.Vb 9
\&    if { 1 } {
\&        print "True!";
\&    }
\&    else {
\&        print "False!";
\&    }
\& 
\&    # perl4 prints: True!
\&    # perl5 errors: syntax error at test.pl line 1, near "if {"
.Ve
.Ip "\(bu BugFix" 4
.IX Item "\(bu BugFix"
The \f(CW**\fR operator now binds more tightly than unary minus.
It was documented to work this way before, but didn't.
.Sp
.Vb 4
\&    print -4**2,"\en";
\& 
\&    # perl4 prints: 16
\&    # perl5 prints: -16
.Ve
.Ip "\(bu Discontinuance " 4
.IX Item "\(bu Discontinuance "
The meaning of \f(CWforeach{}\fR has changed slightly when it is iterating over a
list which is not an array.  This used to assign the list to a
temporary array, but no longer does so (for efficiency).  This means
that you'll now be iterating over the actual values, not over copies of
the values.  Modifications to the loop variable can change the original
values.
.Sp
.Vb 8
\&    @list = ('ab','abc','bcd','def');
\&    foreach $var (grep(/ab/,@list)){
\&        $var = 1;
\&    }
\&    print (join(':',@list));
\& 
\&    # perl4 prints: ab:abc:bcd:def
\&    # perl5 prints: 1:1:bcd:def
.Ve
To retain Perl4 semantics you need to assign your list
explicitly to a temporary array and then iterate over that.  For 
example, you might need to change
.Sp
.Vb 1
\&    foreach $var (grep(/ab/,@list)){
.Ve
to
.Sp
.Vb 1
\&    foreach $var (@tmp = grep(/ab/,@list)){
.Ve
Otherwise changing \f(CW$var\fR will clobber the values of \f(CW@list\fR.  (This most often
happens when you use \f(CW$_\fR for the loop variable, and call subroutines in
the loop that don't properly localize \f(CW$_\fR.)
.Ip "\(bu Discontinuance" 4
.IX Item "\(bu Discontinuance"
\f(CWsplit\fR with no arguments now behaves like \f(CWsplit ' '\fR (which doesn't
return an initial null field if \f(CW$_\fR starts with whitespace), it used to
behave like \f(CWsplit /\es+/\fR (which does).
.Sp
.Vb 2
\&    $_ = ' hi mom';
\&    print join(':', split);
.Ve
.Vb 2
\&    # perl4 prints: :hi:mom
\&    # perl5 prints: hi:mom
.Ve
.Ip "\(bu Deprecation" 4
.IX Item "\(bu Deprecation"
Some error messages will be different.
.Ip "\(bu Discontinuance " 4
.IX Item "\(bu Discontinuance "
Some bugs may have been inadvertently removed.  :\-)
.Sh "Parsing Traps"
.IX Subsection "Parsing Traps"
Perl4-to-Perl5 traps from having to do with parsing.
.Ip "\(bu Parsing" 4
.IX Item "\(bu Parsing"
Note the space between . and =
.Sp
.Vb 5
\&    $string . = "more string";
\&    print $string;
\& 
\&    # perl4 prints: more string
\&    # perl5 prints: syntax error at - line 1, near ". ="
.Ve
.Ip "\(bu Parsing" 4
.IX Item "\(bu Parsing"
Better parsing in perl 5
.Sp
.Vb 6
\&    sub foo {}
\&    &foo
\&    print("hello, world\en");
\& 
\&    # perl4 prints: hello, world
\&    # perl5 prints: syntax error
.Ve
.Ip "\(bu Parsing" 4
.IX Item "\(bu Parsing"
\*(L"if it looks like a function, it is a function\*(R" rule.
.Sp
.Vb 5
\&  print
\&    ($foo == 1) ? "is one\en" : "is zero\en";
\& 
\&    # perl4 prints: is zero
\&    # perl5 warns: "Useless use of a constant in void context" if using -w
.Ve
.Sh "Numerical Traps"
.IX Subsection "Numerical Traps"
Perl4-to-Perl5 traps having to do with numerical operators,
operands, or output from same.
.Ip "\(bu Numerical" 5
.IX Item "\(bu Numerical"
Formatted output and significant digits
.Sp
.Vb 10
\&    print 7.373504 - 0, "\en";
\&    printf "%20.18f\en", 7.373504 - 0; 
\& 
\&    # Perl4 prints:
\&    7.375039999999996141
\&    7.37503999999999614
\& 
\&    # Perl5 prints:
\&    7.373504
\&    7.37503999999999614
.Ve
.Ip "\(bu Numerical" 5
.IX Item "\(bu Numerical"
This specific item has been deleted.  It demonstrated how the autoincrement
operator would not catch when a number went over the signed int limit.  Fixed
in 5.003_04.  But always be wary when using large ints.  If in doubt:
.Sp
.Vb 1
\&   use Math::BigInt;
.Ve
.Ip "\(bu Numerical  " 5
.IX Item "\(bu Numerical  "
Assignment of return values from numeric equality tests
does not work in perl5 when the test evaluates to false (0).
Logical tests now return an null, instead of 0
 
    \f(CW$p\fR = ($test == 1);
    print \f(CW$p\fR,\*(R"\en\*(R";
  
    # perl4 prints: 0
    # perl5 prints:
.Sp
Also see the the section on \fIGeneral Regular Expression Traps\fR tests for another example 
of this new feature...
.Sh "General data type traps"
.IX Subsection "General data type traps"
Perl4-to-Perl5 traps involving most data-types, and their usage
within certain expressions and/or context.
.Ip "\(bu (Arrays)" 5
.IX Item "\(bu (Arrays)"
Negative array subscripts now count from the end of the array.
.Sp
.Vb 5
\&    @a = (1, 2, 3, 4, 5);
\&    print "The third element of the array is $a[3] also expressed as $a[-2] \en";
\&  
\&    # perl4 prints: The third element of the array is 4 also expressed as
\&    # perl5 prints: The third element of the array is 4 also expressed as 4
.Ve
.Ip "\(bu (Arrays)" 5
.IX Item "\(bu (Arrays)"
Setting \f(CW$#array\fR lower now discards array elements, and makes them
impossible to recover.
.Sp
.Vb 9
\&    @a = (a,b,c,d,e); 
\&    print "Before: ",join('',@a);
\&    $#a =1; 
\&    print ", After: ",join('',@a);
\&    $#a =3;
\&    print ", Recovered: ",join('',@a),"\en";
\&  
\&    # perl4 prints: Before: abcde, After: ab, Recovered: abcd
\&    # perl5 prints: Before: abcde, After: ab, Recovered: ab
.Ve
.Ip "\(bu (Hashes)" 5
.IX Item "\(bu (Hashes)"
Hashes get defined before use
.Sp
.Vb 7
\&    local($s,@a,%h); 
\&    die "scalar \e$s defined" if defined($s);
\&    die "array \e@a defined" if defined(@a);
\&    die "hash \e%h defined" if defined(%h);
\& 
\&    # perl4 prints:
\&    # perl5 dies: hash %h defined
.Ve
.Ip "\(bu (Globs)" 5
.IX Item "\(bu (Globs)"
glob assignment from variable to variable will fail if the assigned
variable is localized subsequent to the assignment
.Sp
.Vb 17
\&    @a = ("This is Perl 4");
\&    *b = *a;
\&    local(@a);
\&    print @b,"\en";
\& 
\&    # perl4 prints: This is Perl 4
\&    # perl5 prints:
\& 
\&    # Another example
\& 
\&    *fred = *barney; # fred is aliased to barney
\&    @barney = (1, 2, 4);
\&    # @fred;
\&    print "@fred";  # should print "1, 2, 4"
\& 
\&    # perl4 prints: 1 2 4
\&    # perl5 prints: Literal @fred now requires backslash 
.Ve
.Ip "\(bu (Scalar String)" 5
.IX Item "\(bu (Scalar String)"
Changes in unary negation (of strings)
This change effects both the return value and what it
does to \fIauto\fR\|(magic)increment.
.Sp
.Vb 7
\&    $x = "aaa";
\&    print ++$x," : ";
\&    print -$x," : ";
\&    print ++$x,"\en";
\& 
\&    # perl4 prints: aab : -0 : 1
\&    # perl5 prints: aab : -aab : aac
.Ve
.Ip "\(bu (Constants)" 5
.IX Item "\(bu (Constants)"
perl 4 lets you modify constants:
.Sp
.Vb 21
\&    $foo = "x";
\&    &mod($foo);
\&    for ($x = 0; $x < 3; $x++) {
\&        &mod("a");
\&    }
\&    sub mod {
\&        print "before: $_[0]";
\&        $_[0] = "m";
\&        print "  after: $_[0]\en";
\&    }
\& 
\&    # perl4:
\&    # before: x  after: m
\&    # before: a  after: m
\&    # before: m  after: m
\&    # before: m  after: m
\& 
\&    # Perl5:
\&    # before: x  after: m
\&    # Modification of a read-only value attempted at foo.pl line 12.
\&    # before: a
.Ve
.Ip "\(bu (Scalars)" 5
.IX Item "\(bu (Scalars)"
The behavior is slightly different for:
.Sp
.Vb 4
\&    print "$x", defined $x
\&  
\&    # perl 4: 1
\&    # perl 5: <no output, $x is not called into existence>
.Ve
.Ip "\(bu (Variable Suicide)" 5
.IX Item "\(bu (Variable Suicide)"
Variable suicide behavior is more consistent under Perl 5.
Perl5 exhibits the same behavior for associative arrays and scalars,
that perl4 exhibits only for scalars.
.Sp
.Vb 4
\&    $aGlobal{ "aKey" } = "global value";
\&    print "MAIN:", $aGlobal{"aKey"}, "\en";
\&    $GlobalLevel = 0;
\&    &test( *aGlobal );
.Ve
.Vb 25
\&    sub test {
\&        local( *theArgument ) = @_;
\&        local( %aNewLocal ); # perl 4 != 5.001l,m
\&        $aNewLocal{"aKey"} = "this should never appear";  
\&        print "SUB: ", $theArgument{"aKey"}, "\en";
\&        $aNewLocal{"aKey"} = "level $GlobalLevel";   # what should print
\&        $GlobalLevel++;
\&        if( $GlobalLevel<4 ) {
\&            &test( *aNewLocal );
\&        }
\&    }
\& 
\&    # Perl4:
\&    # MAIN:global value
\&    # SUB: global value
\&    # SUB: level 0
\&    # SUB: level 1
\&    # SUB: level 2
\& 
\&    # Perl5:
\&    # MAIN:global value
\&    # SUB: global value
\&    # SUB: this should never appear
\&    # SUB: this should never appear
\&    # SUB: this should never appear
.Ve
.Sh "Context Traps \- scalar, list contexts"
.IX Subsection "Context Traps \- scalar, list contexts"
.Ip "\(bu (list context)" 5
.IX Item "\(bu (list context)"
The elements of argument lists for formats are now evaluated in list
context.  This means you can interpolate list values now.
.Sp
.Vb 9
\&    @fmt = ("foo","bar","baz");
\&    format STDOUT=
\&    @<<<<< @||||| @>>>>>
\&    @fmt;
\&    .
\&    write;  
\& 
\&    # perl4 errors:  Please use commas to separate fields in file
\&    # perl5 prints: foo     bar      baz
.Ve
.Ip "\(bu (scalar context)" 5
.IX Item "\(bu (scalar context)"
The \f(CWcaller()\fR function now returns a false value in a scalar context 
if there is no caller.  This lets library files determine if they're 
being required.
.Sp
.Vb 4
\&    caller() ? (print "You rang?\en") : (print "Got a 0\en");
\&  
\&    # perl4 errors: There is no caller
\&    # perl5 prints: Got a 0
.Ve
.Ip "\(bu (scalar context)" 5
.IX Item "\(bu (scalar context)"
The comma operator in a scalar context is now guaranteed to give a
scalar context to its arguments.
.Sp
.Vb 6
\&    @y= ('a','b','c');
\&    $x = (1, 2, @y);
\&    print "x = $x\en";
\& 
\&    # Perl4 prints:  x = c   # Thinks list context interpolates list
\&    # Perl5 prints:  x = 3   # Knows scalar uses length of list
.Ve
.Ip "\(bu (list, builtin)" 5
.IX Item "\(bu (list, builtin)"
\f(CWsprintf()\fR funkiness (array argument converted to scalar array count)
This test could be added to t/op/sprintf.t
.Sp
.Vb 6
\&    @z = ('%s%s', 'foo', 'bar');
\&    $x = sprintf(@z);
\&    if ($x eq 'foobar') {print "ok 2\en";} else {print "not ok 2 '$x'\en";}
\& 
\&    # perl4 prints: ok 2
\&    # perl5 prints: not ok 2
.Ve
\f(CWprintf()\fR works fine, though:
.Sp
.Vb 5
\&    printf STDOUT (@z);
\&    print "\en"; 
\& 
\&    # perl4 prints: foobar
\&    # perl5 prints: foobar
.Ve
Probably a bug.
.Sh "Precedence Traps"
.IX Subsection "Precedence Traps"
Perl4-to-Perl5 traps involving precedence order.
.Ip "\(bu Precedence" 5
.IX Item "\(bu Precedence"
\s-1LHS\s0 vs. \s-1RHS\s0 when both sides are getting an op.
.Sp
.Vb 3
\&    @arr = ( 'left', 'right' );
\&    $a{shift @arr} = shift @arr;
\&    print join( ' ', keys %a );
.Ve
.Vb 2
\&    # perl4 prints: left
\&    # perl5 prints: right
.Ve
.Ip "\(bu Precedence" 5
.IX Item "\(bu Precedence"
These are now semantic errors because of precedence:
.Sp
.Vb 9
\&    @list = (1,2,3,4,5);
\&    %map = ("a",1,"b",2,"c",3,"d",4);
\&    $n = shift @list + 2;   # first item in list plus 2
\&    print "n is $n, ";
\&    $m = keys %map + 2;     # number of items in hash plus 2
\&    print "m is $m\en";
\& 
\&    # perl4 prints: n is 3, m is 6
\&    # perl5 errors and fails to compile
.Ve
.Ip "\(bu Precedence" 5
.IX Item "\(bu Precedence"
The precedence of assignment operators is now the same as the precedence
of assignment.  Perl 4 mistakenly gave them the precedence of the associated
operator.  So you now must parenthesize them in expressions like
.Sp
.Vb 3
\&    /foo/ ? ($a += 2) : ($a -= 2);
\&    
\&Otherwise
.Ve
.Vb 1
\&    /foo/ ? $a += 2 : $a -= 2
.Ve
would be erroneously parsed as
.Sp
.Vb 1
\&    (/foo/ ? $a += 2 : $a) -= 2;
.Ve
On the other hand,
.Sp
.Vb 1
\&    $a += /foo/ ? 1 : 2; 
.Ve
now works as a C programmer would expect.
.Ip "\(bu Precedence" 5
.IX Item "\(bu Precedence"
.Sp
.Vb 1
\&    open FOO || die;
.Ve
is now incorrect.  You need parens around the filehandle.
Otherwise, perl5 leaves the statement as it's default precedence:
.Sp
.Vb 4
\&    open(FOO || die);
\& 
\&    # perl4 opens or dies
\&    # perl5 errors: Precedence problem: open FOO should be open(FOO)
.Ve
.Ip "\(bu Precedence" 5
.IX Item "\(bu Precedence"
perl4 gives the special variable, \f(CW$:\fR precedence, where perl5
treats \f(CW$::\fR as main \f(CWpackage\fR
.Sp
.Vb 4
\&    $a = "x"; print "$::a";
\&     
\&    # perl 4 prints: -:a
\&    # perl 5 prints: x
.Ve
.Ip "\(bu Precedence" 5
.IX Item "\(bu Precedence"
concatenation precedence over filetest operator?  
.Sp
.Vb 4
\&    -e $foo .= "q" 
\&  
\&    # perl4 prints: no output
\&    # perl5 prints: Can't modify -e in concatenation
.Ve
.Ip "\(bu Precedence" 5
.IX Item "\(bu Precedence"
Assignment to value takes precedence over assignment to key in
perl5 when using the shift operator on both sides.
.Sp
.Vb 3
\&    @arr = ( 'left', 'right' );
\&    $a{shift @arr} = shift @arr;
\&    print join( ' ', keys %a );
.Ve
.Vb 2
\&    # perl4 prints: left
\&    # perl5 prints: right
.Ve
.Sh "General Regular Expression Traps using s///, etc."
.IX Subsection "General Regular Expression Traps using s///, etc."
All types of \s-1RE\s0 traps.
.Ip "\(bu Regular Expression" 5
.IX Item "\(bu Regular Expression"
\f(CWs'$lhs'$rhs'\fR now does no interpolation on either side.  It used to
interpolate \f(CW$lhs\fR but not \f(CW$rhs\fR.  (And still does not match a literal 
\*(L'$\*(R' in string)
.Sp
.Vb 7
\&    $a=1;$b=2;
\&    $string = '1 2 $a $b';
\&    $string =~ s'$a'$b';
\&    print $string,"\en";
\& 
\&    # perl4 prints: $b 2 $a $b
\&    # perl5 prints: 1 2 $a $b
.Ve
.Ip "\(bu Regular Expression" 5
.IX Item "\(bu Regular Expression"
\f(CWm//g\fR now attaches its state to the searched string rather than the
regular expression.  (Once the scope of a block is left for the sub, the
state of the searched string is lost)
.Sp
.Vb 8
\&    $_ = "ababab";
\&    while(m/ab/g){
\&        &doit("blah");
\&    }
\&    sub doit{local($_) = shift; print "Got $_ "}
\& 
\&    # perl4 prints: blah blah blah
\&    # perl5 prints: infinite loop blah...
.Ve
.Ip "\(bu Regular Expression" 5
.IX Item "\(bu Regular Expression"
If no parentheses are used in a match, Perl4 sets \f(CW$+\fR to
the whole match, just like \f(CW$&\fR. Perl5 does not.
.Sp
.Vb 5
\&    "abcdef" =~ /b.*e/;
\&    print "\e$+ = $+\en";
\& 
\&    # perl4 prints: bcde
\&    # perl5 prints:
.Ve
.Ip "\(bu Regular Expression" 5
.IX Item "\(bu Regular Expression"
substitution now returns the null string if it fails
.Sp
.Vb 6
\&    $string = "test";
\&    $value = ($string =~ s/foo//);
\&    print $value, "\en";
\& 
\&    # perl4 prints: 0
\&    # perl5 prints:
.Ve
Also see the section on \fINumerical Traps\fR for another example of this new feature.
.Ip "\(bu Regular Expression" 5
.IX Item "\(bu Regular Expression"
\f(CWs`lhs`rhs`\fR (using backticks) is now a normal substitution, with no 
backtick expansion
.Sp
.Vb 6
\&    $string = "";
\&    $string =~ s`^`hostname`;
\&    print $string, "\en";
\& 
\&    # perl4 prints: <the local hostname>
\&    # perl5 prints: hostname
.Ve
.Ip "\(bu Regular Expression" 5
.IX Item "\(bu Regular Expression"
Stricter parsing of variables used in regular expressions
.Sp
.Vb 4
\&    s/^([^$grpc]*$grpc[$opt$plus$rep]?)//o;
\& 
\&    # perl4: compiles w/o error
\&    # perl5: with Scalar found where operator expected ..., near "$opt$plus"
.Ve
an added component of this example, apparently from the same script, is
the actual value of the s'd string after the substitution.
\f(CW[$opt]\fR is a character class in perl4 and an array subscript in perl5
.Sp
.Vb 8
\&    $grpc = 'a'; 
\&    $opt  = 'r';
\&    $_ = 'bar';
\&    s/^([^$grpc]*$grpc[$opt]?)/foo/;
\&    print ;
\& 
\&    # perl4 prints: foo
\&    # perl5 prints: foobar
.Ve
.Ip "\(bu Regular Expression" 5
.IX Item "\(bu Regular Expression"
Under perl5, \f(CWm?x?\fR matches only once, like \f(CW?x?\fR. Under perl4, it matched
repeatedly, like \f(CW/x/\fR or \f(CWm!x!\fR.
.Sp
.Vb 13
\&    $test = "once";
\&    sub match { $test =~ m?once?; }
\&    &match();
\&    if( &match() ) {
\&        # m?x? matches more then once
\&        print "perl4\en";
\&    } else { 
\&        # m?x? matches only once
\&        print "perl5\en"; 
\&    }
\& 
\&    # perl4 prints: perl4
\&    # perl5 prints: perl5
.Ve
.Sh "Subroutine, Signal, Sorting Traps"
.IX Subsection "Subroutine, Signal, Sorting Traps"
The general group of Perl4-to-Perl5 traps having to do with
Signals, Sorting, and their related subroutines, as well as
general subroutine traps.  Includes some \s-1OS\s0\-Specific traps.
.Ip "\(bu (Signals)" 5
.IX Item "\(bu (Signals)"
Barewords that used to look like strings to Perl will now look like subroutine
calls if a subroutine by that name is defined before the compiler sees them.
.Sp
.Vb 6
\&    sub SeeYa { warn"Hasta la vista, baby!" }
\&    $SIG{'TERM'} = SeeYa;
\&    print "SIGTERM is now $SIG{'TERM'}\en";
\& 
\&    # perl4 prints: SIGTERM is main'SeeYa
\&    # perl5 prints: SIGTERM is now main::1
.Ve
Use \fB\-w\fR to catch this one
.Ip "\(bu (Sort Subroutine)" 5
.IX Item "\(bu (Sort Subroutine)"
reverse is no longer allowed as the name of a sort subroutine.
.Sp
.Vb 5
\&    sub reverse{ print "yup "; $a <=> $b }
\&    print sort reverse a,b,c;  
\& 
\&    # perl4 prints: yup yup yup yup abc
\&    # perl5 prints: abc 
.Ve
.Ip "\(bu warn() specifically implies \s-1STDERR\s0" 5
.IX Item "\(bu warn() specifically implies \s-1STDERR\s0"
.Sp
.Vb 1
\&    warn STDERR "Foo!";
.Ve
.Vb 2
\&    # perl4 prints: Foo!
\&    # perl5 prints: String found where operator expected 
.Ve
.Sh "\s-1OS\s0 Traps"
.IX Subsection "\s-1OS\s0 Traps"
.Ip "\(bu (SysV)" 5
.IX Item "\(bu (SysV)"
Under \s-1HPUX\s0, and some other SysV \s-1OS\s0's, one had to reset any signal handler, 
within  the signal handler function, each time a signal was handled with 
perl4.  With perl5, the reset is now done correctly.  Any code relying 
on the handler _not_ being reset will have to be reworked.
.Sp
5.002 and beyond uses \fIsigaction()\fR under SysV
.Sp
.Vb 17
\&    sub gotit {
\&        print "Got @_... "; 
\&    }  
\&    $SIG{'INT'} = 'gotit';
\&   
\&    $| = 1;
\&    $pid = fork;
\&    if ($pid) {
\&        kill('INT', $pid);
\&        sleep(1);
\&        kill('INT', $pid);
\&    } else { 
\&        while (1) {sleep(10);}
\&    } 
\& 
\&    # perl4 (HPUX) prints: Got INT...
\&    # perl5 (HPUX) prints: Got INT... Got INT...
.Ve
.Ip "\(bu (SysV)" 5
.IX Item "\(bu (SysV)"
Under SysV \s-1OS\s0's, \f(CWseek()\fR on a file opened to append \f(CW>>\fR now does 
the right thing w.r.t. the \fIfopen()\fR man page. e.g. \- When a file is opened
for append,  it  is  impossible to overwrite information already in
the file.
.Sp
.Vb 11
\&    open(TEST,">>seek.test");
\&    $start = tell TEST ;  
\&    foreach(1 .. 9){
\&        print TEST "$_ ";
\&    }
\&    $end = tell TEST ;
\&    seek(TEST,$start,0);
\&    print TEST "18 characters here";
\& 
\&    # perl4 (solaris) seek.test has: 18 characters here
\&    # perl5 (solaris) seek.test has: 1 2 3 4 5 6 7 8 9 18 characters here
.Ve
.Sh "Interpolation Traps"
.IX Subsection "Interpolation Traps"
.Ip "\(bu Interpolation" 5
.IX Item "\(bu Interpolation"
@ now always interpolates an array in double-quotish strings.
.Sp
.Vb 4
\&    print "To: someone@somewhere.com\en"; 
\& 
\&    # perl4 prints: To:someone@somewhere.com
\&    # perl5 errors : Literal @somewhere now requires backslash
.Ve
.Ip "\(bu Interpolation" 5
.IX Item "\(bu Interpolation"
Perl4-to-Perl5 traps having to do with how things get interpolated
within certain expressions, statements, contexts, or whatever.
.Sp
Double-quoted strings may no longer end with an unescaped $ or @.
.Sp
.Vb 6
\&    $foo = "foo$";
\&    $bar = "bar@";
\&    print "foo is $foo, bar is $bar\en";
\&     
\&    # perl4 prints: foo is foo$, bar is bar@
\&    # perl5 errors: Final $ should be \e$ or $name
.Ve
Note: perl5 \s-1DOES\s0 \s-1NOT\s0 error on the terminating @ in \f(CW$bar\fR
.Ip "\(bu Interpolation" 5
.IX Item "\(bu Interpolation"
The construct \*(L"this is $$x\*(R" used to interpolate the pid at that
point, but now apparently tries to dereference \f(CW$x\fR.  \f(CW$$\fR by itself still
works fine, however.
.Sp
.Vb 1
\&    print "this is $$x\en";
.Ve
.Vb 2
\&    # perl4 prints: this is XXXx   (XXX is the current pid)
\&    # perl5 prints: this is
.Ve
.Ip "\(bu Interpolation" 5
.IX Item "\(bu Interpolation"
Creation of hashes on the fly with \f(CWeval "EXPR"\fR now requires either both 
\f(CW$\fR's to be protected in the specification of the hash name, or both curlies 
to be protected.  If both curlies are protected, the result will be compatible
with perl4 and perl5.  This is a very common practice, and should be changed
to use the block form of \f(CWeval{}\fR  if possible.
.Sp
.Vb 5
\&    $hashname = "foobar";
\&    $key = "baz";
\&    $value = 1234;
\&    eval "\e$$hashname{'$key'} = q|$value|";
\&    (defined($foobar{'baz'})) ?  (print "Yup") : (print "Nope");
.Ve
.Vb 2
\&    # perl4 prints: Yup
\&    # perl5 prints: Nope
.Ve
Changing
.Sp
.Vb 1
\&    eval "\e$$hashname{'$key'} = q|$value|";
.Ve
to
.Sp
.Vb 1
\&    eval "\e$\e$hashname{'$key'} = q|$value|";
.Ve
causes the following result:
.Sp
.Vb 2
\&    # perl4 prints: Nope
\&    # perl5 prints: Yup
.Ve
or, changing to
.Sp
.Vb 1
\&    eval "\e$$hashname\e{'$key'\e} = q|$value|";
.Ve
causes the following result:
.Sp
.Vb 3
\&    # perl4 prints: Yup
\&    # perl5 prints: Yup
\&    # and is compatible for both versions
.Ve
.Ip "\(bu Interpolation" 5
.IX Item "\(bu Interpolation"
perl4 programs which unconsciously rely on the bugs in earlier perl versions.
.Sp
.Vb 4
\&    perl -e '$bar=q/not/; print "This is $foo{$bar} perl5"'
\&     
\&    # perl4 prints: This is not perl5
\&    # perl5 prints: This is perl5
.Ve
.Ip "\(bu Interpolation" 5
.IX Item "\(bu Interpolation"
You also have to be careful about array references.  
.Sp
.Vb 1
\&    print "$foo{"
.Ve
.Vb 2
\&    perl 4 prints: {
\&    perl 5 prints: syntax error
.Ve
.Ip "\(bu Interpolation" 5
.IX Item "\(bu Interpolation"
Similarly, watch out for:
.Sp
.Vb 5
\&    $foo = "array";
\&    print "\e$$foo{bar}\en";
\&  
\&    # perl4 prints: $array{bar}
\&    # perl5 prints: $
.Ve
Perl 5 is looking for \f(CW$array{bar}\fR which doesn't exist, but perl 4 is
happy just to expand \f(CW$foo\fR to \*(L"array\*(R" by itself.  Watch out for this
especially in \f(CWeval\fR's.
.Ip "\(bu Interpolation" 5
.IX Item "\(bu Interpolation"
\f(CWqq()\fR string passed to \f(CWeval\fR
.Sp
.Vb 8
\&    eval qq(
\&        foreach \e$y (keys %\e$x\e) {
\&            \e$count++;
\&        }
\&    );
\&  
\&    # perl4 runs this ok
\&    # perl5 prints: Can't find string terminator ")" 
.Ve
.Sh "\s-1DBM\s0 Traps"
.IX Subsection "\s-1DBM\s0 Traps"
General \s-1DBM\s0 traps.
.Ip "\(bu \s-1DBM\s0" 5
.IX Item "\(bu \s-1DBM\s0"
Existing dbm databases created under perl4 (or any other dbm/ndbm tool)
may cause the same script, run under perl5, to fail.  The build of perl5
must have been linked with the same dbm/ndbm as the default for \f(CWdbmopen()\fR
to function properly without \f(CWtie\fR'ing to an extension dbm implementation.
.Sp
.Vb 2
\&    dbmopen (%dbm, "file", undef);
\&    print "ok\en";
.Ve
.Vb 2
\&    # perl4 prints: ok
\&    # perl5 prints: ok (IFF linked with -ldbm or -lndbm)
.Ve
.Ip "\(bu \s-1DBM\s0" 5
.IX Item "\(bu \s-1DBM\s0"
Existing dbm databases created under perl4 (or any other dbm/ndbm tool)
may cause the same script, run under perl5, to fail.  The error generated
when exceeding the limit on the key/value size will cause perl5 to exit
immediately.
.Sp
.Vb 3
\&    dbmopen(DB, "testdb",0600) || die "couldn't open db! $!";
\&    $DB{'trap'} = "x" x 1024;  # value too large for most dbm/ndbm
\&    print "YUP\en";
.Ve
.Vb 3
\&    # perl4 prints:
\&    dbm store returned -1, errno 28, key "trap" at - line 3.
\&    YUP
.Ve
.Vb 2
\&    # perl5 prints:
\&    dbm store returned -1, errno 28, key "trap" at - line 3.
.Ve
.Sh "Unclassified Traps"
.IX Subsection "Unclassified Traps"
Everything else.
.Ip "\(bu Unclassified" 5
.IX Item "\(bu Unclassified"
\f(CWrequire\fR/\f(CWdo\fR trap using returned value
.Sp
If the file doit.pl has:
.Sp
.Vb 5
\&    sub foo {
\&        $rc = do "./do.pl";
\&        return 8;
\&    } 
\&    print &foo, "\en";
.Ve
And the do.pl file has the following single line:
.Sp
.Vb 1
\&    return 3;
.Ve
Running doit.pl gives the following:
.Sp
.Vb 2
\&    # perl 4 prints: 3 (aborts the subroutine early)
\&    # perl 5 prints: 8 
.Ve
Same behavior if you replace \f(CWdo\fR with \f(CWrequire\fR.
.PP
As always, if any of these are ever officially declared as bugs, 
they'll be fixed and removed.

.rn }` ''
