.rn '' }`
''' $RCSfile$$Revision$$Date$
'''
''' $Log$
'''
.de Sh
.br
.if t .Sp
.ne 5
.PP
\fB\\$1\fR
.PP
..
.de Sp
.if t .sp .5v
.if n .sp
..
.de Ip
.br
.ie \\n(.$>=3 .ne \\$3
.el .ne 3
.IP "\\$1" \\$2
..
.de Vb
.ft CW
.nf
.ne \\$1
..
.de Ve
.ft R

.fi
..
'''
'''
'''     Set up \*(-- to give an unbreakable dash;
'''     string Tr holds user defined translation string.
'''     Bell System Logo is used as a dummy character.
'''
.tr \(*W-|\(bv\*(Tr
.ie n \{\
.ds -- \(*W-
.ds PI pi
.if (\n(.H=4u)&(1m=24u) .ds -- \(*W\h'-12u'\(*W\h'-12u'-\" diablo 10 pitch
.if (\n(.H=4u)&(1m=20u) .ds -- \(*W\h'-12u'\(*W\h'-8u'-\" diablo 12 pitch
.ds L" ""
.ds R" ""
'''   \*(M", \*(S", \*(N" and \*(T" are the equivalent of
'''   \*(L" and \*(R", except that they are used on ".xx" lines,
'''   such as .IP and .SH, which do another additional levels of
'''   double-quote interpretation
.ds M" """
.ds S" """
.ds N" """""
.ds T" """""
.ds L' '
.ds R' '
.ds M' '
.ds S' '
.ds N' '
.ds T' '
'br\}
.el\{\
.ds -- \(em\|
.tr \*(Tr
.ds L" ``
.ds R" ''
.ds M" ``
.ds S" ''
.ds N" ``
.ds T" ''
.ds L' `
.ds R' '
.ds M' `
.ds S' '
.ds N' `
.ds T' '
.ds PI \(*p
'br\}
.\"	If the F register is turned on, we'll generate
.\"	index entries out stderr for the following things:
.\"		TH	Title 
.\"		SH	Header
.\"		Sh	Subsection 
.\"		Ip	Item
.\"		X<>	Xref  (embedded
.\"	Of course, you have to process the output yourself
.\"	in some meaninful fashion.
.if \nF \{
.de IX
.tm Index:\\$1\t\\n%\t"\\$2"
..
.nr % 0
.rr F
.\}
.TH PERLSUB 1 "perl 5.005, patch 53" "20/Jul/98" "Perl Programmers Reference Guide"
.UC
.if n .hy 0
.if n .na
.ds C+ C\v'-.1v'\h'-1p'\s-2+\h'-1p'+\s0\v'.1v'\h'-1p'
.de CQ          \" put $1 in typewriter font
.ft CW
'if n "\c
'if t \\&\\$1\c
'if n \\&\\$1\c
'if n \&"
\\&\\$2 \\$3 \\$4 \\$5 \\$6 \\$7
'.ft R
..
.\" @(#)ms.acc 1.5 88/02/08 SMI; from UCB 4.2
.	\" AM - accent mark definitions
.bd B 3
.	\" fudge factors for nroff and troff
.if n \{\
.	ds #H 0
.	ds #V .8m
.	ds #F .3m
.	ds #[ \f1
.	ds #] \fP
.\}
.if t \{\
.	ds #H ((1u-(\\\\n(.fu%2u))*.13m)
.	ds #V .6m
.	ds #F 0
.	ds #[ \&
.	ds #] \&
.\}
.	\" simple accents for nroff and troff
.if n \{\
.	ds ' \&
.	ds ` \&
.	ds ^ \&
.	ds , \&
.	ds ~ ~
.	ds ? ?
.	ds ! !
.	ds /
.	ds q
.\}
.if t \{\
.	ds ' \\k:\h'-(\\n(.wu*8/10-\*(#H)'\'\h"|\\n:u"
.	ds ` \\k:\h'-(\\n(.wu*8/10-\*(#H)'\`\h'|\\n:u'
.	ds ^ \\k:\h'-(\\n(.wu*10/11-\*(#H)'^\h'|\\n:u'
.	ds , \\k:\h'-(\\n(.wu*8/10)',\h'|\\n:u'
.	ds ~ \\k:\h'-(\\n(.wu-\*(#H-.1m)'~\h'|\\n:u'
.	ds ? \s-2c\h'-\w'c'u*7/10'\u\h'\*(#H'\zi\d\s+2\h'\w'c'u*8/10'
.	ds ! \s-2\(or\s+2\h'-\w'\(or'u'\v'-.8m'.\v'.8m'
.	ds / \\k:\h'-(\\n(.wu*8/10-\*(#H)'\z\(sl\h'|\\n:u'
.	ds q o\h'-\w'o'u*8/10'\s-4\v'.4m'\z\(*i\v'-.4m'\s+4\h'\w'o'u*8/10'
.\}
.	\" troff and (daisy-wheel) nroff accents
.ds : \\k:\h'-(\\n(.wu*8/10-\*(#H+.1m+\*(#F)'\v'-\*(#V'\z.\h'.2m+\*(#F'.\h'|\\n:u'\v'\*(#V'
.ds 8 \h'\*(#H'\(*b\h'-\*(#H'
.ds v \\k:\h'-(\\n(.wu*9/10-\*(#H)'\v'-\*(#V'\*(#[\s-4v\s0\v'\*(#V'\h'|\\n:u'\*(#]
.ds _ \\k:\h'-(\\n(.wu*9/10-\*(#H+(\*(#F*2/3))'\v'-.4m'\z\(hy\v'.4m'\h'|\\n:u'
.ds . \\k:\h'-(\\n(.wu*8/10)'\v'\*(#V*4/10'\z.\v'-\*(#V*4/10'\h'|\\n:u'
.ds 3 \*(#[\v'.2m'\s-2\&3\s0\v'-.2m'\*(#]
.ds o \\k:\h'-(\\n(.wu+\w'\(de'u-\*(#H)/2u'\v'-.3n'\*(#[\z\(de\v'.3n'\h'|\\n:u'\*(#]
.ds d- \h'\*(#H'\(pd\h'-\w'~'u'\v'-.25m'\f2\(hy\fP\v'.25m'\h'-\*(#H'
.ds D- D\\k:\h'-\w'D'u'\v'-.11m'\z\(hy\v'.11m'\h'|\\n:u'
.ds th \*(#[\v'.3m'\s+1I\s-1\v'-.3m'\h'-(\w'I'u*2/3)'\s-1o\s+1\*(#]
.ds Th \*(#[\s+2I\s-2\h'-\w'I'u*3/5'\v'-.3m'o\v'.3m'\*(#]
.ds ae a\h'-(\w'a'u*4/10)'e
.ds Ae A\h'-(\w'A'u*4/10)'E
.ds oe o\h'-(\w'o'u*4/10)'e
.ds Oe O\h'-(\w'O'u*4/10)'E
.	\" corrections for vroff
.if v .ds ~ \\k:\h'-(\\n(.wu*9/10-\*(#H)'\s-2\u~\d\s+2\h'|\\n:u'
.if v .ds ^ \\k:\h'-(\\n(.wu*10/11-\*(#H)'\v'-.4m'^\v'.4m'\h'|\\n:u'
.	\" for low resolution devices (crt and lpr)
.if \n(.H>23 .if \n(.V>19 \
\{\
.	ds : e
.	ds 8 ss
.	ds v \h'-1'\o'\(aa\(ga'
.	ds _ \h'-1'^
.	ds . \h'-1'.
.	ds 3 3
.	ds o a
.	ds d- d\h'-1'\(ga
.	ds D- D\h'-1'\(hy
.	ds th \o'bp'
.	ds Th \o'LP'
.	ds ae ae
.	ds Ae AE
.	ds oe oe
.	ds Oe OE
.\}
.rm #[ #] #H #V #F C
.SH "NAME"
perlsub \- Perl subroutines
.SH "SYNOPSIS"
To declare subroutines:
.PP
.Vb 2
\&    sub NAME;             # A "forward" declaration.
\&    sub NAME(PROTO);      #  ditto, but with prototypes
.Ve
.Vb 2
\&    sub NAME BLOCK        # A declaration and a definition.
\&    sub NAME(PROTO) BLOCK #  ditto, but with prototypes
.Ve
To define an anonymous subroutine at runtime:
.PP
.Vb 2
\&    $subref = sub BLOCK;            # no proto
\&    $subref = sub (PROTO) BLOCK;    # with proto
.Ve
To import subroutines:
.PP
.Vb 1
\&    use PACKAGE qw(NAME1 NAME2 NAME3);
.Ve
To call subroutines:
.PP
.Vb 3
\&    NAME(LIST);    # & is optional with parentheses.
\&    NAME LIST;     # Parentheses optional if predeclared/imported.
\&    &NAME;         # Makes current @_ visible to called subroutine.
.Ve
.SH "DESCRIPTION"
Like many languages, Perl provides for user-defined subroutines.  These
may be located anywhere in the main program, loaded in from other files
via the \f(CWdo\fR, \f(CWrequire\fR, or \f(CWuse\fR keywords, or even generated on the
fly using \f(CWeval\fR or anonymous subroutines (closures).  You can even call
a function indirectly using a variable containing its name or a CODE reference
to it.
.PP
The Perl model for function call and return values is simple: all
functions are passed as parameters one single flat list of scalars, and
all functions likewise return to their caller one single flat list of
scalars.  Any arrays or hashes in these call and return lists will
collapse, losing their identities\*(--but you may always use
pass-by-reference instead to avoid this.  Both call and return lists may
contain as many or as few scalar elements as you'd like.  (Often a
function without an explicit return statement is called a subroutine, but
there's really no difference from the language's perspective.)
.PP
Any arguments passed to the routine come in as the array \f(CW@_\fR.  Thus if you
called a function with two arguments, those would be stored in \f(CW$_[0]\fR
and \f(CW$_[1]\fR.  The array \f(CW@_\fR is a local array, but its elements are
aliases for the actual scalar parameters.  In particular, if an element
\f(CW$_[0]\fR is updated, the corresponding argument is updated (or an error
occurs if it is not updatable).  If an argument is an array or hash
element which did not exist when the function was called, that element is
created only when (and if) it is modified or if a reference to it is
taken.  (Some earlier versions of Perl created the element whether or not
it was assigned to.)  Note that assigning to the whole array \f(CW@_\fR removes
the aliasing, and does not update any arguments.
.PP
The return value of the subroutine is the value of the last expression
evaluated.  Alternatively, a \f(CWreturn\fR statement may be used to exit the
subroutine, optionally specifying the returned value, which will be
evaluated in the appropriate context (list, scalar, or void) depending
on the context of the subroutine call.  If you specify no return value,
the subroutine will return an empty list in a list context, an undefined
value in a scalar context, or nothing in a void context.  If you return
one or more arrays and/or hashes, these will be flattened together into
one large indistinguishable list.
.PP
Perl does not have named formal parameters, but in practice all you do is
assign to a \f(CWmy()\fR list of these.  Any variables you use in the function
that aren't declared private are global variables.  For the gory details
on creating private variables, see
the section on \fIPrivate Variables via my()\fR and the section on \fITemporary Values via local()\fR.
To create protected environments for a set of functions in a separate
package (and probably a separate file), see the section on \fIPackages\fR in the \fIperlmod\fR manpage.
.PP
Example:
.PP
.Vb 8
\&    sub max {
\&        my $max = shift(@_);
\&        foreach $foo (@_) {
\&            $max = $foo if $max < $foo;
\&        }
\&        return $max;
\&    }
\&    $bestday = max($mon,$tue,$wed,$thu,$fri);
.Ve
Example:
.PP
.Vb 2
\&    # get a line, combining continuation lines
\&    #  that start with whitespace
.Ve
.Vb 12
\&    sub get_line {
\&        $thisline = $lookahead;  # GLOBAL VARIABLES!!
\&        LINE: while (defined($lookahead = <STDIN>)) {
\&            if ($lookahead =~ /^[ \et]/) {
\&                $thisline .= $lookahead;
\&            }
\&            else {
\&                last LINE;
\&            }
\&        }
\&        $thisline;
\&    }
.Ve
.Vb 4
\&    $lookahead = <STDIN>;       # get first line
\&    while ($_ = get_line()) {
\&        ...
\&    }
.Ve
Use array assignment to a local list to name your formal arguments:
.PP
.Vb 4
\&    sub maybeset {
\&        my($key, $value) = @_;
\&        $Foo{$key} = $value unless $Foo{$key};
\&    }
.Ve
This also has the effect of turning call-by-reference into call-by-value,
because the assignment copies the values.  Otherwise a function is free to
do in-place modifications of \f(CW@_\fR and change its caller's values.
.PP
.Vb 4
\&    upcase_in($v1, $v2);  # this changes $v1 and $v2
\&    sub upcase_in {
\&        for (@_) { tr/a-z/A-Z/ }
\&    }
.Ve
You aren't allowed to modify constants in this way, of course.  If an
argument were actually literal and you tried to change it, you'd take a
(presumably fatal) exception.   For example, this won't work:
.PP
.Vb 1
\&    upcase_in("frederick");
.Ve
It would be much safer if the \f(CWupcase_in()\fR function
were written to return a copy of its parameters instead
of changing them in place:
.PP
.Vb 7
\&    ($v3, $v4) = upcase($v1, $v2);  # this doesn't
\&    sub upcase {
\&        return unless defined wantarray;  # void context, do nothing
\&        my @parms = @_;
\&        for (@parms) { tr/a-z/A-Z/ }
\&        return wantarray ? @parms : $parms[0];
\&    }
.Ve
Notice how this (unprototyped) function doesn't care whether it was passed
real scalars or arrays.  Perl will see everything as one big long flat \f(CW@_\fR
parameter list.  This is one of the ways where Perl's simple
argument-passing style shines.  The \f(CWupcase()\fR function would work perfectly
well without changing the \f(CWupcase()\fR definition even if we fed it things
like this:
.PP
.Vb 2
\&    @newlist   = upcase(@list1, @list2);
\&    @newlist   = upcase( split /:/, $var );
.Ve
Do not, however, be tempted to do this:
.PP
.Vb 1
\&    (@a, @b)   = upcase(@list1, @list2);
.Ve
Because like its flat incoming parameter list, the return list is also
flat.  So all you have managed to do here is stored everything in \f(CW@a\fR and
made \f(CW@b\fR an empty list.  See the section on \fIPass by Reference\fR for alternatives.
.PP
A subroutine may be called using the \*(L"\f(CW&\fR\*(R" prefix.  The \*(L"\f(CW&\fR\*(R" is optional
in modern Perls, and so are the parentheses if the subroutine has been
predeclared.  (Note, however, that the \*(L"\f(CW&\fR\*(R" is \fINOT\fR optional when
you're just naming the subroutine, such as when it's used as an
argument to \f(CWdefined()\fR or \f(CWundef()\fR.  Nor is it optional when you want to
do an indirect subroutine call with a subroutine name or reference
using the \f(CW&$subref()\fR or \f(CW&{$subref}()\fR constructs.  See the \fIperlref\fR manpage
for more on that.)
.PP
Subroutines may be called recursively.  If a subroutine is called using
the \*(L"\f(CW&\fR\*(R" form, the argument list is optional, and if omitted, no \f(CW@_\fR array is
set up for the subroutine: the \f(CW@_\fR array at the time of the call is
visible to subroutine instead.  This is an efficiency mechanism that
new users may wish to avoid.
.PP
.Vb 2
\&    &foo(1,2,3);        # pass three arguments
\&    foo(1,2,3);         # the same
.Ve
.Vb 2
\&    foo();              # pass a null list
\&    &foo();             # the same
.Ve
.Vb 2
\&    &foo;               # foo() get current args, like foo(@_) !!
\&    foo;                # like foo() IFF sub foo predeclared, else "foo"
.Ve
Not only does the \*(L"\f(CW&\fR\*(R" form make the argument list optional, but it also
disables any prototype checking on the arguments you do provide.  This
is partly for historical reasons, and partly for having a convenient way
to cheat if you know what you're doing.  See the section on Prototypes below.
.PP
Function whose names are in all upper case are reserved to the Perl core,
just as are modules whose names are in all lower case.  A function in
all capitals is a loosely-held convention meaning it will be called
indirectly by the run-time system itself.  Functions that do special,
pre-defined things are \f(CWBEGIN\fR, \f(CWEND\fR, \f(CWAUTOLOAD\fR, and \f(CWDESTROY\fR--plus all the
functions mentioned in the \fIperltie\fR manpage.  The 5.005 release adds \f(CWINIT\fR
to this list.
.Sh "Private Variables via \f(CWmy()\fR"
Synopsis:
.PP
.Vb 4
\&    my $foo;            # declare $foo lexically local
\&    my (@wid, %get);    # declare list of variables local
\&    my $foo = "flurp";  # declare $foo lexical, and init it
\&    my @oof = @bar;     # declare @oof lexical, and init it
.Ve
A \*(L"\f(CWmy\fR\*(R" declares the listed variables to be confined (lexically) to the
enclosing block, conditional (\f(CWif/unless/elsif/else\fR), loop
(\f(CWfor/foreach/while/until/continue\fR), subroutine, \f(CWeval\fR, or
\f(CWdo/require/use\fR'd file.  If more than one value is listed, the list
must be placed in parentheses.  All listed elements must be legal lvalues.
Only alphanumeric identifiers may be lexically scoped\*(--magical
builtins like \f(CW$/\fR must currently be \f(CWlocal\fRize with \*(L"\f(CWlocal\fR\*(R" instead.
.PP
Unlike dynamic variables created by the \*(L"\f(CWlocal\fR\*(R" operator, lexical
variables declared with \*(L"\f(CWmy\fR\*(R" are totally hidden from the outside world,
including any called subroutines (even if it's the same subroutine called
from itself or elsewhere\*(--every call gets its own copy).
.PP
This doesn't mean that a \f(CWmy()\fR variable declared in a statically
\fIenclosing\fR lexical scope would be invisible.  Only the dynamic scopes
are cut off.   For example, the \f(CWbumpx()\fR function below has access to the
lexical \f(CW$x\fR variable because both the my and the sub occurred at the same
scope, presumably the file scope.
.PP
.Vb 2
\&    my $x = 10;
\&    sub bumpx { $x++ } 
.Ve
(An \f(CWeval()\fR, however, can see the lexical variables of the scope it is
being evaluated in so long as the names aren't hidden by declarations within
the \f(CWeval()\fR itself.  See the \fIperlref\fR manpage.)
.PP
The parameter list to \f(CWmy()\fR may be assigned to if desired, which allows you
to initialize your variables.  (If no initializer is given for a
particular variable, it is created with the undefined value.)  Commonly
this is used to name the parameters to a subroutine.  Examples:
.PP
.Vb 4
\&    $arg = "fred";        # "global" variable
\&    $n = cube_root(27);
\&    print "$arg thinks the root is $n\en";
\& fred thinks the root is 3
.Ve
.Vb 5
\&    sub cube_root {
\&        my $arg = shift;  # name doesn't matter
\&        $arg **= 1/3;
\&        return $arg;
\&    }
.Ve
The \*(L"\f(CWmy\fR\*(R" is simply a modifier on something you might assign to.  So when
you do assign to the variables in its argument list, the \*(L"\f(CWmy\fR\*(R" doesn't
change whether those variables are viewed as a scalar or an array.  So
.PP
.Vb 2
\&    my ($foo) = <STDIN>;                # WRONG?
\&    my @FOO = <STDIN>;
.Ve
both supply a list context to the right-hand side, while
.PP
.Vb 1
\&    my $foo = <STDIN>;
.Ve
supplies a scalar context.  But the following declares only one variable:
.PP
.Vb 1
\&    my $foo, $bar = 1;                  # WRONG
.Ve
That has the same effect as
.PP
.Vb 2
\&    my $foo;
\&    $bar = 1;
.Ve
The declared variable is not introduced (is not visible) until after
the current statement.  Thus,
.PP
.Vb 1
\&    my $x = $x;
.Ve
can be used to initialize the new \f(CW$x\fR with the value of the old \f(CW$x\fR, and
the expression
.PP
.Vb 1
\&    my $x = 123 and $x == 123
.Ve
is false unless the old \f(CW$x\fR happened to have the value \f(CW123\fR.
.PP
Lexical scopes of control structures are not bounded precisely by the
braces that delimit their controlled blocks; control expressions are
part of the scope, too.  Thus in the loop
.PP
.Vb 5
\&    while (defined(my $line = <>)) {
\&        $line = lc $line;
\&    } continue {
\&        print $line;
\&    }
.Ve
the scope of \f(CW$line\fR extends from its declaration throughout the rest of
the loop construct (including the \f(CWcontinue\fR clause), but not beyond
it.  Similarly, in the conditional
.PP
.Vb 8
\&    if ((my $answer = <STDIN>) =~ /^yes$/i) {
\&        user_agrees();
\&    } elsif ($answer =~ /^no$/i) {
\&        user_disagrees();
\&    } else {
\&        chomp $answer;
\&        die "'$answer' is neither 'yes' nor 'no'";
\&    }
.Ve
the scope of \f(CW$answer\fR extends from its declaration throughout the rest
of the conditional (including \f(CWelsif\fR and \f(CWelse\fR clauses, if any),
but not beyond it.
.PP
(None of the foregoing applies to \f(CWif/unless\fR or \f(CWwhile/until\fR
modifiers appended to simple statements.  Such modifiers are not
control structures and have no effect on scoping.)
.PP
The \f(CWforeach\fR loop defaults to scoping its index variable dynamically
(in the manner of \f(CWlocal\fR; see below).  However, if the index
variable is prefixed with the keyword \*(L"\f(CWmy\fR\*(R", then it is lexically
scoped instead.  Thus in the loop
.PP
.Vb 3
\&    for my $i (1, 2, 3) {
\&        some_function();
\&    }
.Ve
the scope of \f(CW$i\fR extends to the end of the loop, but not beyond it, and
so the value of \f(CW$i\fR is unavailable in \f(CWsome_function()\fR.
.PP
Some users may wish to encourage the use of lexically scoped variables.
As an aid to catching implicit references to package variables,
if you say
.PP
.Vb 1
\&    use strict 'vars';
.Ve
then any variable reference from there to the end of the enclosing
block must either refer to a lexical variable, or must be fully
qualified with the package name.  A compilation error results
otherwise.  An inner block may countermand this with \*(L"\f(CWno strict 'vars'\fR\*(R".
.PP
A \f(CWmy()\fR has both a compile-time and a run-time effect.  At compile time,
the compiler takes notice of it; the principle usefulness of this is to
quiet \*(L"\f(CWuse strict 'vars'\fR\*(R".  The actual initialization is delayed until
run time, so it gets executed appropriately; every time through a loop,
for example.
.PP
Variables declared with \*(L"\f(CWmy\fR\*(R" are not part of any package and are therefore
never fully qualified with the package name.  In particular, you're not
allowed to try to make a package variable (or other global) lexical:
.PP
.Vb 2
\&    my $pack::var;      # ERROR!  Illegal syntax
\&    my $_;              # also illegal (currently)
.Ve
In fact, a dynamic variable (also known as package or global variables)
are still accessible using the fully qualified \f(CW::\fR notation even while a
lexical of the same name is also visible:
.PP
.Vb 4
\&    package main;
\&    local $x = 10;
\&    my    $x = 20;
\&    print "$x and $::x\en";
.Ve
That will print out \f(CW20\fR and \f(CW10\fR.
.PP
You may declare \*(L"\f(CWmy\fR\*(R" variables at the outermost scope of a file to hide
any such identifiers totally from the outside world.  This is similar
to C's static variables at the file level.  To do this with a subroutine
requires the use of a closure (anonymous function with lexical access).
If a block (such as an \f(CWeval()\fR, function, or \f(CWpackage\fR) wants to create
a private subroutine that cannot be called from outside that block,
it can declare a lexical variable containing an anonymous sub reference:
.PP
.Vb 3
\&    my $secret_version = '1.001-beta';
\&    my $secret_sub = sub { print $secret_version };
\&    &$secret_sub();
.Ve
As long as the reference is never returned by any function within the
module, no outside module can see the subroutine, because its name is not in
any package's symbol table.  Remember that it's not \fI\s-1REALLY\s0\fR called
\f(CW$some_pack::secret_version\fR or anything; it's just \f(CW$secret_version\fR,
unqualified and unqualifiable.
.PP
This does not work with object methods, however; all object methods have
to be in the symbol table of some package to be found.
.Sh "Peristent Private Variables"
Just because a lexical variable is lexically (also called statically)
scoped to its enclosing block, \f(CWeval\fR, or \f(CWdo\fR \s-1FILE\s0, this doesn't mean that
within a function it works like a C static.  It normally works more
like a C auto, but with implicit garbage collection.  
.PP
Unlike local variables in C or \*(C+, Perl's lexical variables don't
necessarily get recycled just because their scope has exited.
If something more permanent is still aware of the lexical, it will
stick around.  So long as something else references a lexical, that
lexical won't be freed\*(--which is as it should be.  You wouldn't want
memory being free until you were done using it, or kept around once you
were done.  Automatic garbage collection takes care of this for you.
.PP
This means that you can pass back or save away references to lexical
variables, whereas to return a pointer to a C auto is a grave error.
It also gives us a way to simulate C's function statics.  Here's a
mechanism for giving a function private variables with both lexical
scoping and a static lifetime.  If you do want to create something like
C's static variables, just enclose the whole function in an extra block,
and put the static variable outside the function but in the block.
.PP
.Vb 8
\&    {
\&        my $secret_val = 0;
\&        sub gimme_another {
\&            return ++$secret_val;
\&        }
\&    }
\&    # $secret_val now becomes unreachable by the outside
\&    # world, but retains its value between calls to gimme_another
.Ve
If this function is being sourced in from a separate file
via \f(CWrequire\fR or \f(CWuse\fR, then this is probably just fine.  If it's
all in the main program, you'll need to arrange for the \f(CWmy()\fR
to be executed early, either by putting the whole block above
your main program, or more likely, placing merely a \f(CWBEGIN\fR
sub around it to make sure it gets executed before your program
starts to run:
.PP
.Vb 6
\&    sub BEGIN {
\&        my $secret_val = 0;
\&        sub gimme_another {
\&            return ++$secret_val;
\&        }
\&    }
.Ve
See the section on \fIPackage Constructors and Destructors\fR in the \fIperlmod\fR manpage about the \f(CWBEGIN\fR function.
.PP
If declared at the outermost scope, the file scope, then lexicals work
someone like C's file statics.  They are available to all functions in
that same file declared below them, but are inaccessible from outside of
the file.  This is sometimes used in modules to create private variables
for the whole module.
.Sh "Temporary Values via \fIlocal()\fR"
\fB\s-1NOTE\s0\fR: In general, you should be using \*(L"\f(CWmy\fR\*(R" instead of \*(L"\f(CWlocal\fR\*(R", because
it's faster and safer.  Exceptions to this include the global punctuation
variables, filehandles and formats, and direct manipulation of the Perl
symbol table itself.  Format variables often use \*(L"\f(CWlocal\fR\*(R" though, as do
other variables whose current value must be visible to called
subroutines.
.PP
Synopsis:
.PP
.Vb 4
\&    local $foo;                 # declare $foo dynamically local
\&    local (@wid, %get);         # declare list of variables local
\&    local $foo = "flurp";       # declare $foo dynamic, and init it
\&    local @oof = @bar;          # declare @oof dynamic, and init it
.Ve
.Vb 5
\&    local *FH;                  # localize $FH, @FH, %FH, &FH  ...
\&    local *merlyn = *randal;    # now $merlyn is really $randal, plus
\&                                #     @merlyn is really @randal, etc
\&    local *merlyn = 'randal';   # SAME THING: promote 'randal' to *randal
\&    local *merlyn = \e$randal;   # just alias $merlyn, not @merlyn etc
.Ve
A \f(CWlocal()\fR modifies its listed variables to be \*(L"local\*(R" to the enclosing
block, \f(CWeval\fR, or \f(CWdo FILE\fR--and to \fIany subroutine called from within that block\fR.
A \f(CWlocal()\fR just gives temporary values to global (meaning package)
variables.  It does \fBnot\fR create a local variable.  This is known as
dynamic scoping.  Lexical scoping is done with \*(L"\f(CWmy\fR\*(R", which works more
like C's auto declarations.
.PP
If more than one variable is given to \f(CWlocal()\fR, they must be placed in
parentheses.  All listed elements must be legal lvalues.  This operator works
by saving the current values of those variables in its argument list on a
hidden stack and restoring them upon exiting the block, subroutine, or
eval.  This means that called subroutines can also reference the local
variable, but not the global one.  The argument list may be assigned to if
desired, which allows you to initialize your local variables.  (If no
initializer is given for a particular variable, it is created with an
undefined value.)  Commonly this is used to name the parameters to a
subroutine.  Examples:
.PP
.Vb 5
\&    for $i ( 0 .. 9 ) {
\&        $digits{$i} = $i;
\&    }
\&    # assume this function uses global %digits hash
\&    parse_num();
.Ve
.Vb 7
\&    # now temporarily add to %digits hash
\&    if ($base12) {
\&        # (NOTE: not claiming this is efficient!)
\&        local %digits  = (%digits, 't' => 10, 'e' => 11);
\&        parse_num();  # parse_num gets this new %digits!
\&    }
\&    # old %digits restored here
.Ve
Because \f(CWlocal()\fR is a run-time command, it gets executed every time
through a loop.  In releases of Perl previous to 5.0, this used more stack
storage each time until the loop was exited.  Perl now reclaims the space
each time through, but it's still more efficient to declare your variables
outside the loop.
.PP
A \f(CWlocal\fR is simply a modifier on an lvalue expression.  When you assign to
a \f(CWlocal\fRized variable, the \f(CWlocal\fR doesn't change whether its list is viewed
as a scalar or an array.  So
.PP
.Vb 2
\&    local($foo) = <STDIN>;
\&    local @FOO = <STDIN>;
.Ve
both supply a list context to the right-hand side, while
.PP
.Vb 1
\&    local $foo = <STDIN>;
.Ve
supplies a scalar context.
.PP
A note about \f(CWlocal()\fR and composite types is in order.  Something
like \f(CWlocal(%foo)\fR works by temporarily placing a brand new hash in
the symbol table.  The old hash is left alone, but is hidden \*(L"behind\*(R"
the new one.
.PP
This means the old variable is completely invisible via the symbol
table (i.e. the hash entry in the \f(CW*foo\fR typeglob) for the duration
of the dynamic scope within which the \f(CWlocal()\fR was seen.  This
has the effect of allowing one to temporarily occlude any magic on
composite types.  For instance, this will briefly alter a tied
hash to some other implementation:
.PP
.Vb 12
\&    tie %ahash, 'APackage';
\&    [...]
\&    {
\&       local %ahash;
\&       tie %ahash, 'BPackage';
\&       [..called code will see %ahash tied to 'BPackage'..]
\&       {
\&          local %ahash;
\&          [..%ahash is a normal (untied) hash here..]
\&       }
\&    }
\&    [..%ahash back to its initial tied self again..]
.Ve
As another example, a custom implementation of \f(CW%ENV\fR might look
like this:
.PP
.Vb 6
\&    {
\&        local %ENV;
\&        tie %ENV, 'MyOwnEnv';
\&        [..do your own fancy %ENV manipulation here..]
\&    }
\&    [..normal %ENV behavior here..]
.Ve
It's also worth taking a moment to explain what happens when you
\f(CWlocal\fRize a member of a composite type (i.e. an array or hash element).
In this case, the element is \f(CWlocal\fRized \fIby name\fR. This means that
when the scope of the \f(CWlocal()\fR ends, the saved value will be
restored to the hash element whose key was named in the \f(CWlocal()\fR, or
the array element whose index was named in the \f(CWlocal()\fR.  If that
element was deleted while the \f(CWlocal()\fR was in effect (e.g. by a
\f(CWdelete()\fR from a hash or a \f(CWshift()\fR of an array), it will spring
back into existence, possibly extending an array and filling in the
skipped elements with \f(CWundef\fR.  For instance, if you say
.PP
.Vb 17
\&    %hash = ( 'This' => 'is', 'a' => 'test' );
\&    @ary  = ( 0..5 );
\&    {
\&         local($ary[5]) = 6;
\&         local($hash{'a'}) = 'drill';
\&         while (my $e = pop(@ary)) {
\&             print "$e . . .\en";
\&             last unless $e > 3;
\&         }
\&         if (@ary) {
\&             $hash{'only a'} = 'test';
\&             delete $hash{'a'};
\&         }
\&    }
\&    print join(' ', map { "$_ $hash{$_}" } sort keys %hash),".\en";
\&    print "The array has ",scalar(@ary)," elements: ",
\&          join(', ', map { defined $_ ? $_ : 'undef' } @ary),"\en";
.Ve
Perl will print
.PP
.Vb 5
\&    6 . . .
\&    4 . . .
\&    3 . . .
\&    This is a test only a test.
\&    The array has 6 elements: 0, 1, 2, undef, undef, 5
.Ve
.Sh "Passing Symbol Table Entries (typeglobs)"
[Note:  The mechanism described in this section was originally the only
way to simulate pass-by-reference in older versions of Perl.  While it
still works fine in modern versions, the new reference mechanism is
generally easier to work with.  See below.]
.PP
Sometimes you don't want to pass the value of an array to a subroutine
but rather the name of it, so that the subroutine can modify the global
copy of it rather than working with a local copy.  In perl you can
refer to all objects of a particular name by prefixing the name
with a star: \f(CW*foo\fR.  This is often known as a \*(L"typeglob\*(R", because the
star on the front can be thought of as a wildcard match for all the
funny prefix characters on variables and subroutines and such.
.PP
When evaluated, the typeglob produces a scalar value that represents
all the objects of that name, including any filehandle, format, or
subroutine.  When assigned to, it causes the name mentioned to refer to
whatever \*(L"\f(CW*\fR\*(R" value was assigned to it.  Example:
.PP
.Vb 8
\&    sub doubleary {
\&        local(*someary) = @_;
\&        foreach $elem (@someary) {
\&            $elem *= 2;
\&        }
\&    }
\&    doubleary(*foo);
\&    doubleary(*bar);
.Ve
Note that scalars are already passed by reference, so you can modify
scalar arguments without using this mechanism by referring explicitly
to \f(CW$_[0]\fR etc.  You can modify all the elements of an array by passing
all the elements as scalars, but you have to use the \f(CW*\fR mechanism (or
the equivalent reference mechanism) to \f(CWpush\fR, \f(CWpop\fR, or change the size of
an array.  It will certainly be faster to pass the typeglob (or reference).
.PP
Even if you don't want to modify an array, this mechanism is useful for
passing multiple arrays in a single \s-1LIST\s0, because normally the \s-1LIST\s0
mechanism will merge all the array values so that you can't extract out
the individual arrays.  For more on typeglobs, see
the section on \fITypeglobs and Filehandles\fR in the \fIperldata\fR manpage.
.Sh "When to Still Use \fIlocal()\fR"
Despite the existence of \f(CWmy()\fR, there are still three places where the
\f(CWlocal()\fR operator still shines.  In fact, in these three places, you
\fImust\fR use \f(CWlocal\fR instead of \f(CWmy\fR.
.Ip "1. You need to give a global variable a temporary value, especially \f(CW$_\fR." 5
The global variables, like \f(CW@ARGV\fR or the punctuation variables, must be 
\f(CWlocal\fRized with \f(CWlocal()\fR.  This block reads in \fI/etc/motd\fR, and splits
it up into chunks separated by lines of equal signs, which are placed
in \f(CW@Fields\fR.
.Sp
.Vb 6
\&    {
\&        local @ARGV = ("/etc/motd");
\&        local $/ = undef;
\&        local $_ = <>;  
\&        @Fields = split /^\es*=+\es*$/;
\&    } 
.Ve
It particular, it's important to \f(CWlocal\fRize \f(CW$_\fR in any routine that assigns
to it.  Look out for implicit assignments in \f(CWwhile\fR conditionals.
.Ip "2. You need to create a local file or directory handle or a local function." 5
A function that needs a filehandle of its own must use \f(CWlocal()\fR uses
\f(CWlocal()\fR on complete typeglob.   This can be used to create new symbol
table entries:
.Sp
.Vb 6
\&    sub ioqueue {
\&        local  (*READER, *WRITER);    # not my!
\&        pipe    (READER,  WRITER);    or die "pipe: $!";
\&        return (*READER, *WRITER);
\&    }
\&    ($head, $tail) = ioqueue();
.Ve
See the Symbol module for a way to create anonymous symbol table
entries.
.Sp
Because assignment of a reference to a typeglob creates an alias, this
can be used to create what is effectively a local function, or at least,
a local alias.
.Sp
.Vb 6
\&    {
\&        local *grow = \e&shrink; # only until this block exists
\&        grow();                 # really calls shrink()
\&        move();                 # if move() grow()s, it shrink()s too
\&    }
\&    grow();                     # get the real grow() again
.Ve
See the section on \fIFunction Templates\fR in the \fIperlref\fR manpage for more about manipulating
functions by name in this way.
.Ip "3. You want to temporarily change just one element of an array or hash." 5
You can \f(CWlocal\fRize just one element of an aggregate.  Usually this
is done on dynamics:
.Sp
.Vb 5
\&    {
\&        local $SIG{INT} = 'IGNORE';
\&        funct();                            # uninterruptible
\&    } 
\&    # interruptibility automatically restored here
.Ve
But it also works on lexically declared aggregates.  Prior to 5.005,
this operation could on occasion misbehave.
.Sh "Pass by Reference"
If you want to pass more than one array or hash into a function\*(--or
return them from it\*(--and have them maintain their integrity, then
you're going to have to use an explicit pass-by-reference.  Before you
do that, you need to understand references as detailed in the \fIperlref\fR manpage.
This section may not make much sense to you otherwise.
.PP
Here are a few simple examples.  First, let's pass in several
arrays to a function and have it \f(CWpop\fR all of then, return a new
list of all their former last elements:
.PP
.Vb 1
\&    @tailings = popmany ( \e@a, \e@b, \e@c, \e@d );
.Ve
.Vb 8
\&    sub popmany {
\&        my $aref;
\&        my @retlist = ();
\&        foreach $aref ( @_ ) {
\&            push @retlist, pop @$aref;
\&        }
\&        return @retlist;
\&    }
.Ve
Here's how you might write a function that returns a
list of keys occurring in all the hashes passed to it:
.PP
.Vb 10
\&    @common = inter( \e%foo, \e%bar, \e%joe );
\&    sub inter {
\&        my ($k, $href, %seen); # locals
\&        foreach $href (@_) {
\&            while ( $k = each %$href ) {
\&                $seen{$k}++;
\&            }
\&        }
\&        return grep { $seen{$_} == @_ } keys %seen;
\&    }
.Ve
So far, we're using just the normal list return mechanism.
What happens if you want to pass or return a hash?  Well,
if you're using only one of them, or you don't mind them
concatenating, then the normal calling convention is ok, although
a little expensive.
.PP
Where people get into trouble is here:
.PP
.Vb 3
\&    (@a, @b) = func(@c, @d);
\&or
\&    (%a, %b) = func(%c, %d);
.Ve
That syntax simply won't work.  It sets just \f(CW@a\fR or \f(CW%a\fR and clears the \f(CW@b\fR or
\f(CW%b\fR.  Plus the function didn't get passed into two separate arrays or
hashes: it got one long list in \f(CW@_\fR, as always.
.PP
If you can arrange for everyone to deal with this through references, it's
cleaner code, although not so nice to look at.  Here's a function that
takes two array references as arguments, returning the two array elements
in order of how many elements they have in them:
.PP
.Vb 10
\&    ($aref, $bref) = func(\e@c, \e@d);
\&    print "@$aref has more than @$bref\en";
\&    sub func {
\&        my ($cref, $dref) = @_;
\&        if (@$cref > @$dref) {
\&            return ($cref, $dref);
\&        } else {
\&            return ($dref, $cref);
\&        }
\&    }
.Ve
It turns out that you can actually do this also:
.PP
.Vb 10
\&    (*a, *b) = func(\e@c, \e@d);
\&    print "@a has more than @b\en";
\&    sub func {
\&        local (*c, *d) = @_;
\&        if (@c > @d) {
\&            return (\e@c, \e@d);
\&        } else {
\&            return (\e@d, \e@c);
\&        }
\&    }
.Ve
Here we're using the typeglobs to do symbol table aliasing.  It's
a tad subtle, though, and also won't work if you're using \f(CWmy()\fR
variables, because only globals (well, and \f(CWlocal()\fRs) are in the symbol table.
.PP
If you're passing around filehandles, you could usually just use the bare
typeglob, like \f(CW*STDOUT\fR, but typeglobs references would be better because
they'll still work properly under \f(CWuse strict 'refs'\fR.  For example:
.PP
.Vb 5
\&    splutter(\e*STDOUT);
\&    sub splutter {
\&        my $fh = shift;
\&        print $fh "her um well a hmmm\en";
\&    }
.Ve
.Vb 5
\&    $rec = get_rec(\e*STDIN);
\&    sub get_rec {
\&        my $fh = shift;
\&        return scalar <$fh>;
\&    }
.Ve
Another way to do this is using \f(CW*HANDLE{IO}\fR, see the \fIperlref\fR manpage for usage
and caveats.
.PP
If you're planning on generating new filehandles, you could do this:
.PP
.Vb 5
\&    sub openit {
\&        my $name = shift;
\&        local *FH;
\&        return open (FH, $path) ? *FH : undef;
\&    }
.Ve
Although that will actually produce a small memory leak.  See the bottom
of the \f(CWopen()\fR entry in the \fIperlfunc\fR manpage for a somewhat cleaner way using the \f(CWIO::Handle\fR
package.
.Sh "Prototypes"
As of the 5.002 release of perl, if you declare
.PP
.Vb 1
\&    sub mypush (\e@@)
.Ve
then \f(CWmypush()\fR takes arguments exactly like \f(CWpush()\fR does.  The declaration
of the function to be called must be visible at compile time.  The prototype
affects only the interpretation of new-style calls to the function, where
new-style is defined as not using the \f(CW&\fR character.  In other words,
if you call it like a builtin function, then it behaves like a builtin
function.  If you call it like an old-fashioned subroutine, then it
behaves like an old-fashioned subroutine.  It naturally falls out from
this rule that prototypes have no influence on subroutine references
like \f(CW\e&foo\fR or on indirect subroutine calls like \f(CW&{$subref}\fR.
.PP
Method calls are not influenced by prototypes either, because the
function to be called is indeterminate at compile time, because it depends
on inheritance.
.PP
Because the intent is primarily to let you define subroutines that work
like builtin commands, here are the prototypes for some other functions
that parse almost exactly like the corresponding builtins.
.PP
.Vb 1
\&    Declared as                 Called as
.Ve
.Vb 14
\&    sub mylink ($$)          mylink $old, $new
\&    sub myvec ($$$)          myvec $var, $offset, 1
\&    sub myindex ($$;$)       myindex &getstring, "substr"
\&    sub mysyswrite ($$$;$)   mysyswrite $buf, 0, length($buf) - $off, $off
\&    sub myreverse (@)        myreverse $a, $b, $c
\&    sub myjoin ($@)          myjoin ":", $a, $b, $c
\&    sub mypop (\e@)           mypop @array
\&    sub mysplice (\e@$$@)     mysplice @array, @array, 0, @pushme
\&    sub mykeys (\e%)          mykeys %{$hashref}
\&    sub myopen (*;$)         myopen HANDLE, $name
\&    sub mypipe (**)          mypipe READHANDLE, WRITEHANDLE
\&    sub mygrep (&@)          mygrep { /foo/ } $a, $b, $c
\&    sub myrand ($)           myrand 42
\&    sub mytime ()            mytime
.Ve
Any backslashed prototype character represents an actual argument
that absolutely must start with that character.  The value passed
to the subroutine (as part of \f(CW@_\fR) will be a reference to the
actual argument given in the subroutine call, obtained by applying
\f(CW\e\fR to that argument.
.PP
Unbackslashed prototype characters have special meanings.  Any
unbackslashed \f(CW@\fR or \f(CW%\fR eats all the rest of the arguments, and forces
list context.  An argument represented by \f(CW$\fR forces scalar context.  An
\f(CW&\fR requires an anonymous subroutine, which, if passed as the first
argument, does not require the \*(L"\f(CWsub\fR\*(R" keyword or a subsequent comma.  A
\f(CW*\fR does whatever it has to do to turn the argument into a reference to a
symbol table entry.
.PP
A semicolon separates mandatory arguments from optional arguments.
(It is redundant before \f(CW@\fR or \f(CW%\fR.)
.PP
Note how the last three examples above are treated specially by the parser.
\f(CWmygrep()\fR is parsed as a true list operator, \f(CWmyrand()\fR is parsed as a
true unary operator with unary precedence the same as \f(CWrand()\fR, and
\f(CWmytime()\fR is truly without arguments, just like \f(CWtime()\fR.  That is, if you
say
.PP
.Vb 1
\&    mytime +2;
.Ve
you'll get \f(CWmytime() + 2\fR, not \f(CWmytime(2)\fR, which is how it would be parsed
without the prototype.
.PP
The interesting thing about \f(CW&\fR is that you can generate new syntax with it:
.PP
.Vb 9
\&    sub try (&@) {
\&        my($try,$catch) = @_;
\&        eval { &$try };
\&        if ($@) {
\&            local $_ = $@;
\&            &$catch;
\&        }
\&    }
\&    sub catch (&) { $_[0] }
.Ve
.Vb 5
\&    try {
\&        die "phooey";
\&    } catch {
\&        /phooey/ and print "unphooey\en";
\&    };
.Ve
That prints \f(CW"unphooey"\fR.  (Yes, there are still unresolved
issues having to do with the visibility of \f(CW@_\fR.  I'm ignoring that
question for the moment.  (But note that if we make \f(CW@_\fR lexically
scoped, those anonymous subroutines can act like closures... (Gee,
is this sounding a little Lispish?  (Never mind.))))
.PP
And here's a reimplementation of \f(CWgrep\fR:
.PP
.Vb 8
\&    sub mygrep (&@) {
\&        my $code = shift;
\&        my @result;
\&        foreach $_ (@_) {
\&            push(@result, $_) if &$code;
\&        }
\&        @result;
\&    }
.Ve
Some folks would prefer full alphanumeric prototypes.  Alphanumerics have
been intentionally left out of prototypes for the express purpose of
someday in the future adding named, formal parameters.  The current
mechanism's main goal is to let module writers provide better diagnostics
for module users.  Larry feels the notation quite understandable to Perl
programmers, and that it will not intrude greatly upon the meat of the
module, nor make it harder to read.  The line noise is visually
encapsulated into a small pill that's easy to swallow.
.PP
It's probably best to prototype new functions, not retrofit prototyping
into older ones.  That's because you must be especially careful about
silent impositions of differing list versus scalar contexts.  For example,
if you decide that a function should take just one parameter, like this:
.PP
.Vb 4
\&    sub func ($) {
\&        my $n = shift;
\&        print "you gave me $n\en";
\&    }
.Ve
and someone has been calling it with an array or expression
returning a list:
.PP
.Vb 2
\&    func(@foo);
\&    func( split /:/ );
.Ve
Then you've just supplied an automatic \f(CWscalar()\fR in front of their
argument, which can be more than a bit surprising.  The old \f(CW@foo\fR
which used to hold one thing doesn't get passed in.  Instead,
the \f(CWfunc()\fR now gets passed in \f(CW1\fR, that is, the number of elements
in \f(CW@foo\fR.  And the \f(CWsplit()\fR gets called in a scalar context and
starts scribbling on your \f(CW@_\fR parameter list.
.PP
This is all very powerful, of course, and should be used only in moderation
to make the world a better place.
.Sh "Constant Functions"
Functions with a prototype of \f(CW()\fR are potential candidates for
inlining.  If the result after optimization and constant folding is
either a constant or a lexically-scoped scalar which has no other
references, then it will be used in place of function calls made
without \f(CW&\fR or \f(CWdo\fR. Calls made using \f(CW&\fR or \f(CWdo\fR are never
inlined.  (See \fIconstant.pm\fR for an easy way to declare most
constants.)
.PP
The following functions would all be inlined:
.PP
.Vb 5
\&    sub pi ()           { 3.14159 }             # Not exact, but close.
\&    sub PI ()           { 4 * atan2 1, 1 }      # As good as it gets,
\&                                                # and it's inlined, too!
\&    sub ST_DEV ()       { 0 }
\&    sub ST_INO ()       { 1 }
.Ve
.Vb 3
\&    sub FLAG_FOO ()     { 1 << 8 }
\&    sub FLAG_BAR ()     { 1 << 9 }
\&    sub FLAG_MASK ()    { FLAG_FOO | FLAG_BAR }
.Ve
.Vb 9
\&    sub OPT_BAZ ()      { not (0x1B58 & FLAG_MASK) }
\&    sub BAZ_VAL () {
\&        if (OPT_BAZ) {
\&            return 23;
\&        }
\&        else {
\&            return 42;
\&        }
\&    }
.Ve
.Vb 6
\&    sub N () { int(BAZ_VAL) / 3 }
\&    BEGIN {
\&        my $prod = 1;
\&        for (1..N) { $prod *= $_ }
\&        sub N_FACTORIAL () { $prod }
\&    }
.Ve
If you redefine a subroutine that was eligible for inlining, you'll get
a mandatory warning.  (You can use this warning to tell whether or not a
particular subroutine is considered constant.)  The warning is
considered severe enough not to be optional because previously compiled
invocations of the function will still be using the old value of the
function.  If you need to be able to redefine the subroutine you need to
ensure that it isn't inlined, either by dropping the \f(CW()\fR prototype
(which changes the calling semantics, so beware) or by thwarting the
inlining mechanism in some other way, such as
.PP
.Vb 3
\&    sub not_inlined () {
\&        23 if $];
\&    }
.Ve
.Sh "Overriding Builtin Functions"
Many builtin functions may be overridden, though this should be tried
only occasionally and for good reason.  Typically this might be
done by a package attempting to emulate missing builtin functionality
on a non-Unix system.
.PP
Overriding may be done only by importing the name from a
module\*(--ordinary predeclaration isn't good enough.  However, the
\f(CWsubs\fR pragma (compiler directive) lets you, in effect, predeclare subs
via the import syntax, and these names may then override the builtin ones:
.PP
.Vb 3
\&    use subs 'chdir', 'chroot', 'chmod', 'chown';
\&    chdir $somewhere;
\&    sub chdir { ... }
.Ve
To unambiguously refer to the builtin form, one may precede the
builtin name with the special package qualifier \f(CWCORE::\fR.  For example,
saying \f(CWCORE::open()\fR will always refer to the builtin \f(CWopen()\fR, even
if the current package has imported some other subroutine called
\f(CW&open()\fR from elsewhere.
.PP
Library modules should not in general export builtin names like \*(L"\f(CWopen\fR\*(R"
or \*(L"\f(CWchdir\fR\*(R" as part of their default \f(CW@EXPORT\fR list, because these may
sneak into someone else's namespace and change the semantics unexpectedly.
Instead, if the module adds the name to the \f(CW@EXPORT_OK\fR list, then it's
possible for a user to import the name explicitly, but not implicitly.
That is, they could say
.PP
.Vb 1
\&    use Module 'open';
.Ve
and it would import the \f(CWopen\fR override, but if they said
.PP
.Vb 1
\&    use Module;
.Ve
they would get the default imports without the overrides.
.PP
The foregoing mechanism for overriding builtins is restricted, quite
deliberately, to the package that requests the import.  There is a second
method that is sometimes applicable when you wish to override a builtin
everywhere, without regard to namespace boundaries.  This is achieved by
importing a sub into the special namespace \f(CWCORE::GLOBAL::\fR.  Here is an
example that quite brazenly replaces the \f(CWglob\fR operator with something
that understands regular expressions.
.PP
.Vb 4
\&    package REGlob;
\&    require Exporter;
\&    @ISA = 'Exporter';
\&    @EXPORT_OK = 'glob';
.Ve
.Vb 7
\&    sub import {
\&        my $pkg = shift;
\&        return unless @_;
\&        my $sym = shift;
\&        my $where = ($sym =~ s/^GLOBAL_// ? 'CORE::GLOBAL' : caller(0));
\&        $pkg->export($where, $sym, @_);
\&    }
.Ve
.Vb 8
\&    sub glob {
\&        my $pat = shift;
\&        my @got;
\&        local(*D);
\&        if (opendir D, '.') { @got = grep /$pat/, readdir D; closedir D; }
\&        @got;
\&    }
\&    1;
.Ve
And here's how it could be (ab)used:
.PP
.Vb 4
\&    #use REGlob 'GLOBAL_glob';      # override glob() in ALL namespaces
\&    package Foo;
\&    use REGlob 'glob';              # override glob() in Foo:: only
\&    print for <^[a-z_]+\e.pm\e$>;     # show all pragmatic modules
.Ve
Note that the initial comment shows a contrived, even dangerous example.
By overriding \f(CWglob\fR globally, you would be forcing the new (and
subversive) behavior for the \f(CWglob\fR operator for \fBevery\fR namespace,
without the complete cognizance or cooperation of the modules that own
those namespaces.  Naturally, this should be done with extreme caution\*(--if
it must be done at all.
.PP
The \f(CWREGlob\fR example above does not implement all the support needed to
cleanly override perl's \f(CWglob\fR operator.  The builtin \f(CWglob\fR has
different behaviors depending on whether it appears in a scalar or list
context, but our \f(CWREGlob\fR doesn't.  Indeed, many perl builtins have such
context sensitive behaviors, and these must be adequately supported by
a properly written override.  For a fully functional example of overriding
\f(CWglob\fR, study the implementation of \f(CWFile::DosGlob\fR in the standard
library.
.Sh "Autoloading"
If you call a subroutine that is undefined, you would ordinarily get an
immediate fatal error complaining that the subroutine doesn't exist.
(Likewise for subroutines being used as methods, when the method
doesn't exist in any base class of the class package.) If,
however, there is an \f(CWAUTOLOAD\fR subroutine defined in the package or
packages that were searched for the original subroutine, then that
\f(CWAUTOLOAD\fR subroutine is called with the arguments that would have been
passed to the original subroutine.  The fully qualified name of the
original subroutine magically appears in the \f(CW$AUTOLOAD\fR variable in the
same package as the \f(CWAUTOLOAD\fR routine.  The name is not passed as an
ordinary argument because, er, well, just because, that's why...
.PP
Most \f(CWAUTOLOAD\fR routines will load in a definition for the subroutine in
question using eval, and then execute that subroutine using a special
form of \*(L"goto\*(R" that erases the stack frame of the \f(CWAUTOLOAD\fR routine
without a trace.  (See the standard \f(CWAutoLoader\fR module, for example.)
But an \f(CWAUTOLOAD\fR routine can also just emulate the routine and never
define it.   For example, let's pretend that a function that wasn't defined
should just call \f(CWsystem()\fR with those arguments.  All you'd do is this:
.PP
.Vb 8
\&    sub AUTOLOAD {
\&        my $program = $AUTOLOAD;
\&        $program =~ s/.*:://;
\&        system($program, @_);
\&    }
\&    date();
\&    who('am', 'i');
\&    ls('-l');
.Ve
In fact, if you predeclare the functions you want to call that way, you don't
even need the parentheses:
.PP
.Vb 4
\&    use subs qw(date who ls);
\&    date;
\&    who "am", "i";
\&    ls -l;
.Ve
A more complete example of this is the standard Shell module, which
can treat undefined subroutine calls as calls to Unix programs.
.PP
Mechanisms are available for modules writers to help split the modules
up into autoloadable files.  See the standard AutoLoader module
described in the \fIAutoLoader\fR manpage and in the \fIAutoSplit\fR manpage, the standard
SelfLoader modules in the \fISelfLoader\fR manpage, and the document on adding C
functions to perl code in the \fIperlxs\fR manpage.
.SH "SEE ALSO"
See the \fIperlref\fR manpage for more about references and closures.  See the \fIperlxs\fR manpage if
you'd like to learn about calling C subroutines from perl.  See the \fIperlmod\fR manpage
to learn about bundling up your functions in separate files.

.rn }` ''
.IX Title "PERLSUB 1"
.IX Name "perlsub - Perl subroutines"

.IX Header "NAME"

.IX Header "SYNOPSIS"

.IX Header "DESCRIPTION"

.IX Subsection "Private Variables via \f(CWmy()\fR"

.IX Subsection "Peristent Private Variables"

.IX Subsection "Temporary Values via \fIlocal()\fR"

.IX Subsection "Passing Symbol Table Entries (typeglobs)"

.IX Subsection "When to Still Use \fIlocal()\fR"

.IX Item "1. You need to give a global variable a temporary value, especially \f(CW$_\fR."

.IX Item "2. You need to create a local file or directory handle or a local function."

.IX Item "3. You want to temporarily change just one element of an array or hash."

.IX Subsection "Pass by Reference"

.IX Subsection "Prototypes"

.IX Subsection "Constant Functions"

.IX Subsection "Overriding Builtin Functions"

.IX Subsection "Autoloading"

.IX Header "SEE ALSO"

