.rn '' }`
''' $RCSfile$$Revision$$Date$
'''
''' $Log$
'''
.de Sh
.br
.if t .Sp
.ne 5
.PP
\fB\\$1\fR
.PP
..
.de Sp
.if t .sp .5v
.if n .sp
..
.de Ip
.br
.ie \\n(.$>=3 .ne \\$3
.el .ne 3
.IP "\\$1" \\$2
..
.de Vb
.ft CW
.nf
.ne \\$1
..
.de Ve
.ft R

.fi
..
'''
'''
'''     Set up \*(-- to give an unbreakable dash;
'''     string Tr holds user defined translation string.
'''     Bell System Logo is used as a dummy character.
'''
.tr \(*W-|\(bv\*(Tr
.ie n \{\
.ds -- \(*W-
.ds PI pi
.if (\n(.H=4u)&(1m=24u) .ds -- \(*W\h'-12u'\(*W\h'-12u'-\" diablo 10 pitch
.if (\n(.H=4u)&(1m=20u) .ds -- \(*W\h'-12u'\(*W\h'-8u'-\" diablo 12 pitch
.ds L" ""
.ds R" ""
.ds L' '
.ds R' '
'br\}
.el\{\
.ds -- \(em\|
.tr \*(Tr
.ds L" ``
.ds R" ''
.ds L' `
.ds R' '
.ds PI \(*p
'br\}
.\"	If the F register is turned on, we'll generate
.\"	index entries out stderr for the following things:
.\"		TH	Title 
.\"		SH	Header
.\"		Sh	Subsection 
.\"		Ip	Item
.\"		X<>	Xref  (embedded
.\"	Of course, you have to process the output yourself
.\"	in some meaninful fashion.
.if \nF \{
.de IX
.tm Index:\\$1\t\\n%\t"\\$2"
..
.nr % 0
.rr F
.\}
.TH PERLTOC 1 "perl 5.003, patch 05" "16/Aug/96" "Perl Programmers Reference Guide"
.IX Title "PERLTOC 1"
.UC
.IX Name "perltoc - perl documentation table of contents"
.if n .hy 0
.if n .na
.ds C+ C\v'-.1v'\h'-1p'\s-2+\h'-1p'+\s0\v'.1v'\h'-1p'
.de CQ          \" put $1 in typewriter font
.ft CW
'if n "\c
'if t \\&\\$1\c
'if n \\&\\$1\c
'if n \&"
\\&\\$2 \\$3 \\$4 \\$5 \\$6 \\$7
'.ft R
..
.\" @(#)ms.acc 1.5 88/02/08 SMI; from UCB 4.2
.	\" AM - accent mark definitions
.bd B 3
.	\" fudge factors for nroff and troff
.if n \{\
.	ds #H 0
.	ds #V .8m
.	ds #F .3m
.	ds #[ \f1
.	ds #] \fP
.\}
.if t \{\
.	ds #H ((1u-(\\\\n(.fu%2u))*.13m)
.	ds #V .6m
.	ds #F 0
.	ds #[ \&
.	ds #] \&
.\}
.	\" simple accents for nroff and troff
.if n \{\
.	ds ' \&
.	ds ` \&
.	ds ^ \&
.	ds , \&
.	ds ~ ~
.	ds ? ?
.	ds ! !
.	ds /
.	ds q
.\}
.if t \{\
.	ds ' \\k:\h'-(\\n(.wu*8/10-\*(#H)'\'\h"|\\n:u"
.	ds ` \\k:\h'-(\\n(.wu*8/10-\*(#H)'\`\h'|\\n:u'
.	ds ^ \\k:\h'-(\\n(.wu*10/11-\*(#H)'^\h'|\\n:u'
.	ds , \\k:\h'-(\\n(.wu*8/10)',\h'|\\n:u'
.	ds ~ \\k:\h'-(\\n(.wu-\*(#H-.1m)'~\h'|\\n:u'
.	ds ? \s-2c\h'-\w'c'u*7/10'\u\h'\*(#H'\zi\d\s+2\h'\w'c'u*8/10'
.	ds ! \s-2\(or\s+2\h'-\w'\(or'u'\v'-.8m'.\v'.8m'
.	ds / \\k:\h'-(\\n(.wu*8/10-\*(#H)'\z\(sl\h'|\\n:u'
.	ds q o\h'-\w'o'u*8/10'\s-4\v'.4m'\z\(*i\v'-.4m'\s+4\h'\w'o'u*8/10'
.\}
.	\" troff and (daisy-wheel) nroff accents
.ds : \\k:\h'-(\\n(.wu*8/10-\*(#H+.1m+\*(#F)'\v'-\*(#V'\z.\h'.2m+\*(#F'.\h'|\\n:u'\v'\*(#V'
.ds 8 \h'\*(#H'\(*b\h'-\*(#H'
.ds v \\k:\h'-(\\n(.wu*9/10-\*(#H)'\v'-\*(#V'\*(#[\s-4v\s0\v'\*(#V'\h'|\\n:u'\*(#]
.ds _ \\k:\h'-(\\n(.wu*9/10-\*(#H+(\*(#F*2/3))'\v'-.4m'\z\(hy\v'.4m'\h'|\\n:u'
.ds . \\k:\h'-(\\n(.wu*8/10)'\v'\*(#V*4/10'\z.\v'-\*(#V*4/10'\h'|\\n:u'
.ds 3 \*(#[\v'.2m'\s-2\&3\s0\v'-.2m'\*(#]
.ds o \\k:\h'-(\\n(.wu+\w'\(de'u-\*(#H)/2u'\v'-.3n'\*(#[\z\(de\v'.3n'\h'|\\n:u'\*(#]
.ds d- \h'\*(#H'\(pd\h'-\w'~'u'\v'-.25m'\f2\(hy\fP\v'.25m'\h'-\*(#H'
.ds D- D\\k:\h'-\w'D'u'\v'-.11m'\z\(hy\v'.11m'\h'|\\n:u'
.ds th \*(#[\v'.3m'\s+1I\s-1\v'-.3m'\h'-(\w'I'u*2/3)'\s-1o\s+1\*(#]
.ds Th \*(#[\s+2I\s-2\h'-\w'I'u*3/5'\v'-.3m'o\v'.3m'\*(#]
.ds ae a\h'-(\w'a'u*4/10)'e
.ds Ae A\h'-(\w'A'u*4/10)'E
.ds oe o\h'-(\w'o'u*4/10)'e
.ds Oe O\h'-(\w'O'u*4/10)'E
.	\" corrections for vroff
.if v .ds ~ \\k:\h'-(\\n(.wu*9/10-\*(#H)'\s-2\u~\d\s+2\h'|\\n:u'
.if v .ds ^ \\k:\h'-(\\n(.wu*10/11-\*(#H)'\v'-.4m'^\v'.4m'\h'|\\n:u'
.	\" for low resolution devices (crt and lpr)
.if \n(.H>23 .if \n(.V>19 \
\{\
.	ds : e
.	ds 8 ss
.	ds v \h'-1'\o'\(aa\(ga'
.	ds _ \h'-1'^
.	ds . \h'-1'.
.	ds 3 3
.	ds o a
.	ds d- d\h'-1'\(ga
.	ds D- D\h'-1'\(hy
.	ds th \o'bp'
.	ds Th \o'LP'
.	ds ae ae
.	ds Ae AE
.	ds oe oe
.	ds Oe OE
.\}
.rm #[ #] #H #V #F C
.SH "NAME"
.IX Header "NAME"
perltoc \- perl documentation table of contents
.SH "DESCRIPTION"
.IX Header "DESCRIPTION"
This page provides a brief table of contents for the rest of the Perl
documentation set.  It is meant to be be quickly scanned or grepped
through to locate the proper section you're looking for.
.SH "BASIC DOCUMENTATION"
.IX Header "BASIC DOCUMENTATION"
.Sh "perl \- Practical Extraction and Report Language"
.IX Subsection "perl \- Practical Extraction and Report Language"
.Ip "\s-1SYNOPSIS\s0" 0
.IX Item "\s-1SYNOPSIS\s0"
.Ip "\s-1DESCRIPTION\s0" 0
.IX Item "\s-1DESCRIPTION\s0"
Many usability enhancements, Simplified grammar, Lexical scoping,
Arbitrarily nested data structures, Modularity and reusability,
Object-oriented programming, Embeddable and Extensible, \s-1POSIX\s0
compliant, Package constructors and destructors, Multiple simultaneous
\s-1DBM\s0 implementations, Subroutine definitions may now be autoloaded,
Regular expression enhancements
.Ip "\s-1ENVIRONMENT\s0" 0
.IX Item "\s-1ENVIRONMENT\s0"
\s-1HOME\s0, \s-1LOGDIR\s0, \s-1PATH\s0, \s-1PERL5LIB\s0, \s-1PERL5DB\s0, \s-1PERLLIB\s0
.Ip "\s-1AUTHOR\s0" 0
.IX Item "\s-1AUTHOR\s0"
.Ip "\s-1FILES\s0" 0
.IX Item "\s-1FILES\s0"
.Ip "\s-1SEE\s0 \s-1ALSO\s0" 0
.IX Item "\s-1SEE\s0 \s-1ALSO\s0"
.Ip "\s-1DIAGNOSTICS\s0" 0
.IX Item "\s-1DIAGNOSTICS\s0"
.Ip "\s-1BUGS\s0" 0
.IX Item "\s-1BUGS\s0"
.Ip "\s-1NOTES\s0" 0
.IX Item "\s-1NOTES\s0"
.Sh "perldata \- Perl data types"
.IX Subsection "perldata \- Perl data types"
.Ip "\s-1DESCRIPTION\s0" 0
.IX Item "\s-1DESCRIPTION\s0"
.Ip "Variable names" 5
.IX Item "Variable names"
.Ip "Context" 5
.IX Item "Context"
.Ip "Scalar values" 5
.IX Item "Scalar values"
.Ip "Scalar value constructors" 5
.IX Item "Scalar value constructors"
.Ip "List value constructors" 5
.IX Item "List value constructors"
.Ip "Typeglobs and FileHandles" 5
.IX Item "Typeglobs and FileHandles"
.Sh "perlsyn \- Perl syntax"
.IX Subsection "perlsyn \- Perl syntax"
.Ip "\s-1DESCRIPTION\s0" 0
.IX Item "\s-1DESCRIPTION\s0"
.Ip "Declarations" 5
.IX Item "Declarations"
.Ip "Simple statements" 5
.IX Item "Simple statements"
.Ip "Compound statements" 5
.IX Item "Compound statements"
.Ip "Loop Control" 5
.IX Item "Loop Control"
.Ip "For Loops" 5
.IX Item "For Loops"
.Ip "Foreach Loops" 5
.IX Item "Foreach Loops"
.Ip "Basic BLOCKs and Switch Statements" 5
.IX Item "Basic BLOCKs and Switch Statements"
.Ip "Goto" 5
.IX Item "Goto"
.Ip "PODs: Embedded Documentation" 5
.IX Item "PODs: Embedded Documentation"
.Sh "perlop \- Perl operators and precedence"
.IX Subsection "perlop \- Perl operators and precedence"
.Ip "\s-1SYNOPSIS\s0" 0
.IX Item "\s-1SYNOPSIS\s0"
.Ip "\s-1DESCRIPTION\s0" 0
.IX Item "\s-1DESCRIPTION\s0"
.Ip "Terms and List Operators (Leftward)" 5
.IX Item "Terms and List Operators (Leftward)"
.Ip "The Arrow Operator" 5
.IX Item "The Arrow Operator"
.Ip "Autoincrement and Autodecrement" 5
.IX Item "Autoincrement and Autodecrement"
.Ip "Exponentiation" 5
.IX Item "Exponentiation"
.Ip "Symbolic Unary Operators" 5
.IX Item "Symbolic Unary Operators"
.Ip "Binding Operators" 5
.IX Item "Binding Operators"
.Ip "Multiplicative Operators" 5
.IX Item "Multiplicative Operators"
.Ip "Additive Operators" 5
.IX Item "Additive Operators"
.Ip "Shift Operators" 5
.IX Item "Shift Operators"
.Ip "Named Unary Operators" 5
.IX Item "Named Unary Operators"
.Ip "Relational Operators" 5
.IX Item "Relational Operators"
.Ip "Equality Operators" 5
.IX Item "Equality Operators"
.Ip "Bitwise And" 5
.IX Item "Bitwise And"
.Ip "Bitwise Or and Exclusive Or" 5
.IX Item "Bitwise Or and Exclusive Or"
.Ip "C\-style Logical And" 5
.IX Item "C\-style Logical And"
.Ip "C\-style Logical Or" 5
.IX Item "C\-style Logical Or"
.Ip "Range Operator" 5
.IX Item "Range Operator"
.Ip "Conditional Operator" 5
.IX Item "Conditional Operator"
.Ip "Assignment Operators" 5
.IX Item "Assignment Operators"
.Ip "Comma Operator" 5
.IX Item "Comma Operator"
.Ip "List Operators (Rightward)" 5
.IX Item "List Operators (Rightward)"
.Ip "Logical Not" 5
.IX Item "Logical Not"
.Ip "Logical And" 5
.IX Item "Logical And"
.Ip "Logical or and Exclusive Or" 5
.IX Item "Logical or and Exclusive Or"
.Ip "C Operators Missing From Perl" 5
.IX Item "C Operators Missing From Perl"
unary &, unary *, (\s-1TYPE\s0)
.Ip "Quote and Quotelike Operators" 5
.IX Item "Quote and Quotelike Operators"
.Ip "Regexp Quotelike Operators" 5
.IX Item "Regexp Quotelike Operators"
?\s-1PATTERN\s0?, m/\s-1PATTERN/\s0gimosx, /\s-1PATTERN/\s0gimosx, q/\s-1STRING\s0/, \f(CW'STRING'\fR,
qq/\s-1STRING\s0/, \*(L"\s-1STRING\s0\*(R", qx/\s-1STRING\s0/, `\s-1STRING\s0`, qw/\s-1STRING\s0/,
s/\s-1PATTERN/REPLACEMENT/\s0egimosx, tr/\s-1SEARCHLIST/REPLACEMENTLIST/\s0cds,
y/\s-1SEARCHLIST/REPLACEMENTLIST/\s0cds
.Ip "I/O Operators" 5
.IX Item "I/O Operators"
.Ip "Constant Folding" 5
.IX Item "Constant Folding"
.Ip "Integer arithmetic" 5
.IX Item "Integer arithmetic"
.Sh "perlre \- Perl regular expressions"
.IX Subsection "perlre \- Perl regular expressions"
.Ip "\s-1DESCRIPTION\s0" 0
.IX Item "\s-1DESCRIPTION\s0"
.Ip "Regular Expressions" 5
.IX Item "Regular Expressions"
(?#text), (?:regexp), (?=regexp), (?!regexp), (?imsx)
.Ip "Backtracking" 5
.IX Item "Backtracking"
.Ip "Version 8 Regular Expressions" 5
.IX Item "Version 8 Regular Expressions"
.Ip "\s-1WARNING\s0 on \e1 vs $1" 5
.IX Item "\s-1WARNING\s0 on \e1 vs $1"
.Sh "perlrun \- how to execute the Perl interpreter"
.IX Subsection "perlrun \- how to execute the Perl interpreter"
.Ip "\s-1SYNOPSIS\s0" 0
.IX Item "\s-1SYNOPSIS\s0"
.Ip "\s-1DESCRIPTION\s0" 0
.IX Item "\s-1DESCRIPTION\s0"
.Ip "Switches" 5
.IX Item "Switches"
\fB\-0\fR\fIdigits\fR, \fB\-a\fR, \fB\-c\fR, \fB\-d\fR, \fB\-d:foo\fR, \fB\-D\fR\fInumber\fR,
\fB\-D\fR\fIlist\fR, \fB\-e\fR \fIcommandline\fR, \fB\-F\fR\fIregexp\fR, \fB\-i\fR\fIextension\fR,
\fB\-I\fR\fIdirectory\fR, \fB\-l\fR\fIoctnum\fR, \fB\-m\fR\fImodule\fR, \fB\-M\fR\fImodule\fR,
\fB\-n\fR, \fB\-p\fR, \fB\-P\fR, \fB\-s\fR, \fB\-S\fR, \fB\-T\fR, \fB\-u\fR, \fB\-U\fR, \fB\-v\fR, \fB\-V\fR,
\fB\-V:name\fR, \fB\-w\fR, \fB\-x\fR \fIdirectory\fR
.Sh "perlfunc \- Perl builtin functions"
.IX Subsection "perlfunc \- Perl builtin functions"
.Ip "\s-1DESCRIPTION\s0" 0
.IX Item "\s-1DESCRIPTION\s0"
.Ip "Perl Functions by Category" 5
.IX Item "Perl Functions by Category"
Functions for SCALARs or strings, Regular expressions and pattern
matching, Numeric functions, Functions for real \f(CW@ARRAYs\fR, Functions for
list data, Functions for real \f(CW%HASHes\fR, Input and output functions,
Functions for fixed length data or records, Functions for filehandles,
files, or directories, Keywords related to the control flow of your
perl program, Keywords related to scoping, Miscellaneous functions,
Functions for processes and process groups, Keywords related to perl
modules, Keywords related to classes and object-orientedness, Low-level
socket functions, System V interprocess communication functions,
Fetching user and group info, Fetching network info, Time-related
functions
.Ip "Alphabetical Listing of Perl Functions" 5
.IX Item "Alphabetical Listing of Perl Functions"
-\fIX\fR \s-1FILEHANDLE\s0, \-\fIX\fR \s-1EXPR\s0, \-\fIX\fR, abs \s-1VALUE\s0, accept \s-1NEWSOCKET\s0,\s-1GENERICSOCKET\s0,
alarm \s-1SECONDS\s0, atan2 Y,X, bind \s-1SOCKET\s0,\s-1NAME\s0, binmode \s-1FILEHANDLE\s0, bless
\s-1REF\s0,\s-1CLASSNAME\s0, bless \s-1REF\s0, caller \s-1EXPR\s0, caller, chdir \s-1EXPR\s0, chmod \s-1LIST\s0,
chomp \s-1VARIABLE\s0, chomp \s-1LIST\s0, chomp, chop \s-1VARIABLE\s0, chop \s-1LIST\s0, chop,
chown \s-1LIST\s0, chr \s-1NUMBER\s0, chroot \s-1FILENAME\s0, close \s-1FILEHANDLE\s0, closedir
\s-1DIRHANDLE\s0, connect \s-1SOCKET\s0,\s-1NAME\s0, continue \s-1BLOCK\s0, cos \s-1EXPR\s0, crypt
\s-1PLAINTEXT\s0,\s-1SALT\s0, dbmclose \s-1ASSOC_ARRAY\s0, dbmopen \s-1ASSOC\s0,\s-1DBNAME\s0,\s-1MODE\s0,
defined \s-1EXPR\s0, delete \s-1EXPR\s0, die \s-1LIST\s0, do \s-1BLOCK\s0, do \fI\s-1SUBROUTINE\s0\fR\|(\s-1LIST\s0), do
\s-1EXPR\s0, dump \s-1LABEL\s0, each \s-1ASSOC_ARRAY\s0, eof \s-1FILEHANDLE\s0, eof (), eof, eval
\s-1EXPR\s0, eval \s-1BLOCK\s0, exec \s-1LIST\s0, exists \s-1EXPR\s0, exit \s-1EXPR\s0, exp \s-1EXPR\s0, fcntl
\s-1FILEHANDLE\s0,\s-1FUNCTION\s0,\s-1SCALAR\s0, fileno \s-1FILEHANDLE\s0, flock
\s-1FILEHANDLE\s0,\s-1OPERATION\s0, fork, format, formline \s-1PICTURE\s0, \s-1LIST\s0, getc
\s-1FILEHANDLE\s0, getc, getlogin, getpeername \s-1SOCKET\s0, getpgrp \s-1PID\s0, getppid,
getpriority \s-1WHICH\s0,\s-1WHO\s0, getpwnam \s-1NAME\s0, getgrnam \s-1NAME\s0, gethostbyname
\s-1NAME\s0, getnetbyname \s-1NAME\s0, getprotobyname \s-1NAME\s0, getpwuid \s-1UID\s0, getgrgid
\s-1GID\s0, getservb
.Sh "perlvar \- Perl predefined variables"
.IX Subsection "perlvar \- Perl predefined variables"
.Ip "\s-1DESCRIPTION\s0" 0
.IX Item "\s-1DESCRIPTION\s0"
.Ip "Predefined Names" 5
.IX Item "Predefined Names"
$\s-1ARG\s0, \f(CW$_\fR, $<\fIdigit\fR>, \f(CW$MATCH\fR, $&, \f(CW$PREMATCH\fR, $`, \f(CW$POSTMATCH\fR, $\*(R',
\f(CW$LAST_PAREN_MATCH\fR, $+, \f(CW$MULTILINE_MATCHING\fR, $*, input_line_number
\s-1HANDLE\s0 \s-1EXPR\s0, \f(CW$INPUT_LINE_NUMBER\fR, \f(CW$NR\fR, $, input_record_separator \s-1HANDLE\s0
\s-1EXPR\s0, \f(CW$INPUT_RECORD_SEPARATOR\fR, \f(CW$RS\fR, $/, autoflush \s-1HANDLE\s0 \s-1EXPR\s0,
\f(CW$OUTPUT_AUTOFLUSH\fR, $|, output_field_separator \s-1HANDLE\s0 \s-1EXPR\s0,
\f(CW$OUTPUT_FIELD_SEPARATOR\fR, \f(CW$OFS\fR, $,, output_record_separator \s-1HANDLE\s0 \s-1EXPR\s0,
\f(CW$OUTPUT_RECORD_SEPARATOR\fR, \f(CW$ORS\fR, $\e, \f(CW$LIST_SEPARATOR\fR, $\*(R",
\f(CW$SUBSCRIPT_SEPARATOR\fR, \f(CW$SUBSEP\fR, $;, \f(CW$OFMT\fR, $#, format_page_number \s-1HANDLE\s0
\s-1EXPR\s0, \f(CW$FORMAT_PAGE_NUMBER\fR, $%, format_lines_per_page \s-1HANDLE\s0 \s-1EXPR\s0,
\f(CW$FORMAT_LINES_PER_PAGE\fR, $=, format_lines_left \s-1HANDLE\s0 \s-1EXPR\s0,
\f(CW$FORMAT_LINES_LEFT\fR, $\-, format_name \s-1HANDLE\s0 \s-1EXPR\s0, \f(CW$FORMAT_NAME\fR, $~,
format_top_name \s-1HANDLE\s0 \s-1EXPR\s0, \f(CW$FORMAT_TOP_NAME\fR, $^,
format_line_break_characters \s-1HANDLE\s0 \s-1EXPR\s0,
\f(CW$FORMAT_LINE_BREAK_CHARACTERS\fR, \f(CW$:\fR, format_formfeed \s-1HANDLE\s0 \s-1EXPR\s0,
\f(CW$FORMAT_FORMFEED\fR, $^L, \f(CW$ACCUMULATOR\fR, $^A, \f(CW$CHILD_ERROR\fR, $?, \f(CW$OS_ERROR\fR,
\f(CW$ERRNO\fR, $!, \f(CW$EVAL_ERROR\fR, $@, \f(CW$PROCESS_ID\fR, \f(CW$PID\fR, $$, \f(CW$REAL_USER_ID\fR,
\f(CW$UID\fR, $<,
.Sh "perlsub \- Perl subroutines"
.IX Subsection "perlsub \- Perl subroutines"
.Ip "\s-1SYNOPSIS\s0" 0
.IX Item "\s-1SYNOPSIS\s0"
.Ip "\s-1DESCRIPTION\s0" 0
.IX Item "\s-1DESCRIPTION\s0"
.Ip "Private Variables via my()" 5
.IX Item "Private Variables via my()"
.Ip "Temporary Values via local()" 5
.IX Item "Temporary Values via local()"
.Ip "Passing Symbol Table Entries (typeglobs)" 5
.IX Item "Passing Symbol Table Entries (typeglobs)"
.Ip "Pass by Reference" 5
.IX Item "Pass by Reference"
.Ip "Prototypes" 5
.IX Item "Prototypes"
.Ip "Overriding Builtin Functions" 5
.IX Item "Overriding Builtin Functions"
.Ip "Autoloading" 5
.IX Item "Autoloading"
.Ip "\s-1SEE\s0 \s-1ALSO\s0" 0
.IX Item "\s-1SEE\s0 \s-1ALSO\s0"
.Sh "perlmod \- Perl modules (packages)"
.IX Subsection "perlmod \- Perl modules (packages)"
.Ip "\s-1DESCRIPTION\s0" 0
.IX Item "\s-1DESCRIPTION\s0"
.Ip "Packages" 5
.IX Item "Packages"
.Ip "Symbol Tables" 5
.IX Item "Symbol Tables"
.Ip "Package Constructors and Destructors" 5
.IX Item "Package Constructors and Destructors"
.Ip "Perl Classes" 5
.IX Item "Perl Classes"
.Ip "Perl Modules" 5
.IX Item "Perl Modules"
.Ip "\s-1NOTE\s0" 0
.IX Item "\s-1NOTE\s0"
.Ip "\s-1THE\s0 \s-1PERL\s0 \s-1MODULE\s0 \s-1LIBRARY\s0" 0
.IX Item "\s-1THE\s0 \s-1PERL\s0 \s-1MODULE\s0 \s-1LIBRARY\s0"
.Ip "Pragmatic Modules" 5
.IX Item "Pragmatic Modules"
diagnostics, integer, less, overload, sigtrap, strict, subs
.Ip "Standard Modules" 5
.IX Item "Standard Modules"
AnyDBM_File, AutoLoader, AutoSplit, Benchmark, Carp, Config, Cwd,
DB_File, Devel::SelfStubber, DynaLoader, English, Env, Exporter,
ExtUtils::Liblist, ExtUtils::MakeMaker, ExtUtils::Manifest,
ExtUtils::Mkbootstrap, ExtUtils::Miniperl, Fcntl, File::Basename,
File::CheckTree, File::Find, FileHandle, File::Path, Getopt::Long,
Getopt::Std, I18N::Collate, \s-1IPC::\s0Open2, \s-1IPC::\s0Open3, Net::Ping, \s-1POSIX\s0,
SelfLoader, Safe, Socket, Test::Harness, Text::Abbrev
.Ip "Extension Modules" 5
.IX Item "Extension Modules"
.Ip "\s-1CPAN\s0" 0
.IX Item "\s-1CPAN\s0"
Language Extensions and Documentation Tools, Development Support,
Operating System Interfaces, Networking, Device Control (modems) and
InterProcess Communication, Data Types and Data Type Utilities,
Database Interfaces, User Interfaces, Interfaces to / Emulations of
Other Programming Languages, File Names, File Systems and File Locking
(see also File Handles), String Processing, Language Text Processing,
Parsing and Searching, Option, Argument, Parameter and Configuration
File Processing, Internationalization and Locale, Authentication,
Security and Encryption, World Wide Web, \s-1HTML\s0, \s-1HTTP\s0, \s-1CGI\s0, \s-1MIME\s0, Server
and Daemon Utilities, Archiving and Compression, Images, Pixmap and
Bitmap Manipulation, Drawing and Graphing, Mail and Usenet News,
Control Flow Utilities (callbacks and exceptions etc), File Handle and
Input/Output Stream Utilities, Miscellaneous Modules
.Ip "Modules: Creation, Use and Abuse" 0
.IX Item "Modules: Creation, Use and Abuse"
.Ip "Guidelines for Module Creation" 5
.IX Item "Guidelines for Module Creation"
Do similar modules already exist in some form?, Try to design the new
module to be easy to extend and reuse, Some simple style guidelines,
Select what to export, Select a name for the module, Have you got it
right?, \s-1README\s0 and other Additional Files, A description of the
module/package/extension etc, A copyright notice \- see below,
Prerequisites \- what else you may need to have, How to build it \-
possible changes to Makefile.\s-1PL\s0 etc, How to install it, Recent changes
in this release, especially incompatibilities, Changes / enhancements
you plan to make in the future, Adding a Copyright Notice, Give the
module a version/issue/release number, How to release and distribute a
module, Take care when changing a released module
.Ip "Guidelines for Converting Perl 4 Library Scripts into Modules" 5
.IX Item "Guidelines for Converting Perl 4 Library Scripts into Modules"
There is no requirement to convert anything, Consider the implications,
Make the most of the opportunity, The pl2pm utility will get you
started, Adds the standard Module prologue lines, Converts package
specifiers from \*(L' to ::, Converts \fIdie\fR\|(...) to \fIcroak\fR\|(...), Several other
minor changes
.Ip "Guidelines for Reusing Application Code" 5
.IX Item "Guidelines for Reusing Application Code"
Complete applications rarely belong in the Perl Module Library, Many
applications contain some perl code which could be reused, Break-out
the reusable code into one or more separate module files, Take the
opportunity to reconsider and redesign the interfaces, In some cases
the \*(L'application\*(R' can then be reduced to a small
.Sh "perlref \- Perl references and nested data structures"
.IX Subsection "perlref \- Perl references and nested data structures"
.Ip "\s-1DESCRIPTION\s0" 0
.IX Item "\s-1DESCRIPTION\s0"
.Ip "Symbolic references" 5
.IX Item "Symbolic references"
.Ip "Not-so-symbolic references" 5
.IX Item "Not-so-symbolic references"
.Ip "\s-1WARNING\s0" 0
.IX Item "\s-1WARNING\s0"
.Ip "\s-1SEE\s0 \s-1ALSO\s0" 0
.IX Item "\s-1SEE\s0 \s-1ALSO\s0"
.Sh "perldsc \- Perl Data Structures Cookbook"
.IX Subsection "perldsc \- Perl Data Structures Cookbook"
.Ip "\s-1DESCRIPTION\s0" 0
.IX Item "\s-1DESCRIPTION\s0"
arrays of arrays, hashes of arrays, arrays of hashes, hashes of hashes,
more elaborate constructs, recursive and self-referential data
structures, objects
.Ip "\s-1REFERENCES\s0" 0
.IX Item "\s-1REFERENCES\s0"
.Ip "\s-1COMMON\s0 \s-1MISTAKES\s0" 0
.IX Item "\s-1COMMON\s0 \s-1MISTAKES\s0"
.Ip "\s-1CAVEAT\s0 \s-1ON\s0 \s-1PRECEDENCE\s0" 0
.IX Item "\s-1CAVEAT\s0 \s-1ON\s0 \s-1PRECEDENCE\s0"
.Ip "\s-1WHY\s0 \s-1YOU\s0 \s-1SHOULD\s0 \s-1ALWAYS\s0 \f(CWuse strict\fR" 0
.IX Item "\s-1WHY\s0 \s-1YOU\s0 \s-1SHOULD\s0 \s-1ALWAYS\s0 \f(CWuse strict\fR"
.Ip "\s-1DEBUGGING\s0" 0
.IX Item "\s-1DEBUGGING\s0"
.Ip "\s-1CODE\s0 \s-1EXAMPLES\s0" 0
.IX Item "\s-1CODE\s0 \s-1EXAMPLES\s0"
.Ip "\s-1LISTS\s0 \s-1OF\s0 \s-1LISTS\s0" 0
.IX Item "\s-1LISTS\s0 \s-1OF\s0 \s-1LISTS\s0"
.Ip "Declaration of a \s-1LIST\s0 \s-1OF\s0 \s-1LISTS\s0" 5
.IX Item "Declaration of a \s-1LIST\s0 \s-1OF\s0 \s-1LISTS\s0"
.Ip "Generation of a \s-1LIST\s0 \s-1OF\s0 \s-1LISTS\s0" 5
.IX Item "Generation of a \s-1LIST\s0 \s-1OF\s0 \s-1LISTS\s0"
.Ip "Access and Printing of a \s-1LIST\s0 \s-1OF\s0 \s-1LISTS\s0" 5
.IX Item "Access and Printing of a \s-1LIST\s0 \s-1OF\s0 \s-1LISTS\s0"
.Ip "\s-1HASHES\s0 \s-1OF\s0 \s-1LISTS\s0" 0
.IX Item "\s-1HASHES\s0 \s-1OF\s0 \s-1LISTS\s0"
.Ip "Declaration of a \s-1HASH\s0 \s-1OF\s0 \s-1LISTS\s0" 5
.IX Item "Declaration of a \s-1HASH\s0 \s-1OF\s0 \s-1LISTS\s0"
.Ip "Generation of a \s-1HASH\s0 \s-1OF\s0 \s-1LISTS\s0" 5
.IX Item "Generation of a \s-1HASH\s0 \s-1OF\s0 \s-1LISTS\s0"
.Ip "Access and Printing of a \s-1HASH\s0 \s-1OF\s0 \s-1LISTS\s0" 5
.IX Item "Access and Printing of a \s-1HASH\s0 \s-1OF\s0 \s-1LISTS\s0"
.Ip "\s-1LISTS\s0 \s-1OF\s0 \s-1HASHES\s0" 0
.IX Item "\s-1LISTS\s0 \s-1OF\s0 \s-1HASHES\s0"
.Ip "Declaration of a \s-1LIST\s0 \s-1OF\s0 \s-1HASHES\s0" 5
.IX Item "Declaration of a \s-1LIST\s0 \s-1OF\s0 \s-1HASHES\s0"
.Ip "Generation of a \s-1LIST\s0 \s-1OF\s0 \s-1HASHES\s0" 5
.IX Item "Generation of a \s-1LIST\s0 \s-1OF\s0 \s-1HASHES\s0"
.Ip "Access and Printing of a \s-1LIST\s0 \s-1OF\s0 \s-1HASHES\s0" 5
.IX Item "Access and Printing of a \s-1LIST\s0 \s-1OF\s0 \s-1HASHES\s0"
.Ip "\s-1HASHES\s0 \s-1OF\s0 \s-1HASHES\s0" 0
.IX Item "\s-1HASHES\s0 \s-1OF\s0 \s-1HASHES\s0"
.Ip "Declaration of a \s-1HASH\s0 \s-1OF\s0 \s-1HASHES\s0" 5
.IX Item "Declaration of a \s-1HASH\s0 \s-1OF\s0 \s-1HASHES\s0"
.Ip "Generation of a \s-1HASH\s0 \s-1OF\s0 \s-1HASHES\s0" 5
.IX Item "Generation of a \s-1HASH\s0 \s-1OF\s0 \s-1HASHES\s0"
.Ip "Access and Printing of a \s-1HASH\s0 \s-1OF\s0 \s-1HASHES\s0" 5
.IX Item "Access and Printing of a \s-1HASH\s0 \s-1OF\s0 \s-1HASHES\s0"
.Ip "\s-1MORE\s0 \s-1ELABORATE\s0 \s-1RECORDS\s0" 0
.IX Item "\s-1MORE\s0 \s-1ELABORATE\s0 \s-1RECORDS\s0"
.Ip "Declaration of \s-1MORE\s0 \s-1ELABORATE\s0 \s-1RECORDS\s0" 5
.IX Item "Declaration of \s-1MORE\s0 \s-1ELABORATE\s0 \s-1RECORDS\s0"
.Ip "Declaration of a \s-1HASH\s0 \s-1OF\s0 \s-1COMPLEX\s0 \s-1RECORDS\s0" 5
.IX Item "Declaration of a \s-1HASH\s0 \s-1OF\s0 \s-1COMPLEX\s0 \s-1RECORDS\s0"
.Ip "Generation of a \s-1HASH\s0 \s-1OF\s0 \s-1COMPLEX\s0 \s-1RECORDS\s0" 5
.IX Item "Generation of a \s-1HASH\s0 \s-1OF\s0 \s-1COMPLEX\s0 \s-1RECORDS\s0"
.Ip "Database Ties" 0
.IX Item "Database Ties"
.Ip "\s-1SEE\s0 \s-1ALSO\s0" 0
.IX Item "\s-1SEE\s0 \s-1ALSO\s0"
.Ip "\s-1AUTHOR\s0" 0
.IX Item "\s-1AUTHOR\s0"
.Sh "perllol, perlLoL \- Manipulating Lists of Lists in Perl"
.IX Subsection "perllol, perlLoL \- Manipulating Lists of Lists in Perl"
.Ip "\s-1DESCRIPTION\s0" 0
.IX Item "\s-1DESCRIPTION\s0"
.Ip "Declaration and Access of Lists of Lists" 0
.IX Item "Declaration and Access of Lists of Lists"
.Ip "Growing Your Own" 0
.IX Item "Growing Your Own"
.Ip "Access and Printing" 0
.IX Item "Access and Printing"
.Ip "Slices" 0
.IX Item "Slices"
.Ip "\s-1SEE\s0 \s-1ALSO\s0" 0
.IX Item "\s-1SEE\s0 \s-1ALSO\s0"
.Ip "\s-1AUTHOR\s0" 0
.IX Item "\s-1AUTHOR\s0"
.Sh "perlobj \- Perl objects"
.IX Subsection "perlobj \- Perl objects"
.Ip "\s-1DESCRIPTION\s0" 0
.IX Item "\s-1DESCRIPTION\s0"
.Ip "An Object is Simply a Reference" 5
.IX Item "An Object is Simply a Reference"
.Ip "A Class is Simply a Package" 5
.IX Item "A Class is Simply a Package"
.Ip "A Method is Simply a Subroutine" 5
.IX Item "A Method is Simply a Subroutine"
.Ip "Method Invocation" 5
.IX Item "Method Invocation"
.Ip "Destructors" 5
.IX Item "Destructors"
.Ip "\s-1WARNING\s0" 5
.IX Item "\s-1WARNING\s0"
.Ip "Summary" 5
.IX Item "Summary"
.Ip "Two-Phased Garbage Collection" 5
.IX Item "Two-Phased Garbage Collection"
.Ip "\s-1SEE\s0 \s-1ALSO\s0" 0
.IX Item "\s-1SEE\s0 \s-1ALSO\s0"
.Sh "perltie \- how to hide an object class in a simple variable"
.IX Subsection "perltie \- how to hide an object class in a simple variable"
.Ip "\s-1SYNOPSIS\s0" 0
.IX Item "\s-1SYNOPSIS\s0"
.Ip "\s-1DESCRIPTION\s0" 0
.IX Item "\s-1DESCRIPTION\s0"
.Ip "Tying Scalars" 5
.IX Item "Tying Scalars"
\s-1TIESCALAR\s0 classname, \s-1LIST\s0, \s-1FETCH\s0 this, \s-1STORE\s0 this, value, \s-1DESTROY\s0 this
.Ip "Tying Arrays" 5
.IX Item "Tying Arrays"
\s-1TIEARRAY\s0 classname, \s-1LIST\s0, \s-1FETCH\s0 this, index, \s-1STORE\s0 this, index, value,
\s-1DESTROY\s0 this
.Ip "Tying Hashes" 5
.IX Item "Tying Hashes"
\s-1USER\s0, \s-1HOME\s0, \s-1CLOBBER\s0, \s-1LIST\s0, \s-1TIEHASH\s0 classname, \s-1LIST\s0, \s-1FETCH\s0 this, key,
\s-1STORE\s0 this, key, value, \s-1DELETE\s0 this, key, \s-1CLEAR\s0 this, \s-1EXISTS\s0 this, key,
\s-1FIRSTKEY\s0 this, \s-1NEXTKEY\s0 this, lastkey, \s-1DESTROY\s0 this
.Ip "Tying FileHandles" 5
.IX Item "Tying FileHandles"
.Ip "\s-1SEE\s0 \s-1ALSO\s0" 0
.IX Item "\s-1SEE\s0 \s-1ALSO\s0"
.Ip "\s-1BUGS\s0" 0
.IX Item "\s-1BUGS\s0"
.Ip "\s-1AUTHOR\s0" 0
.IX Item "\s-1AUTHOR\s0"
.Sh "perlbot \- Bag'o Object Tricks (the \s-1BOT\s0)"
.IX Subsection "perlbot \- Bag'o Object Tricks (the \s-1BOT\s0)"
.Ip "\s-1DESCRIPTION\s0" 0
.IX Item "\s-1DESCRIPTION\s0"
.Ip "\s-1OO\s0 \s-1SCALING\s0 \s-1TIPS\s0" 0
.IX Item "\s-1OO\s0 \s-1SCALING\s0 \s-1TIPS\s0"
.Ip "\s-1INSTANCE\s0 \s-1VARIABLES\s0" 0
.IX Item "\s-1INSTANCE\s0 \s-1VARIABLES\s0"
.Ip "\s-1SCALAR\s0 \s-1INSTANCE\s0 \s-1VARIABLES\s0" 0
.IX Item "\s-1SCALAR\s0 \s-1INSTANCE\s0 \s-1VARIABLES\s0"
.Ip "\s-1INSTANCE\s0 \s-1VARIABLE\s0 \s-1INHERITANCE\s0" 0
.IX Item "\s-1INSTANCE\s0 \s-1VARIABLE\s0 \s-1INHERITANCE\s0"
.Ip "\s-1OBJECT\s0 \s-1RELATIONSHIPS\s0" 0
.IX Item "\s-1OBJECT\s0 \s-1RELATIONSHIPS\s0"
.Ip "\s-1OVERRIDING\s0 \s-1SUPERCLASS\s0 \s-1METHODS\s0" 0
.IX Item "\s-1OVERRIDING\s0 \s-1SUPERCLASS\s0 \s-1METHODS\s0"
.Ip "\s-1USING\s0 \s-1RELATIONSHIP\s0 \s-1WITH\s0 \s-1SDBM\s0" 0
.IX Item "\s-1USING\s0 \s-1RELATIONSHIP\s0 \s-1WITH\s0 \s-1SDBM\s0"
.Ip "\s-1THINKING\s0 \s-1OF\s0 \s-1CODE\s0 \s-1REUSE\s0" 0
.IX Item "\s-1THINKING\s0 \s-1OF\s0 \s-1CODE\s0 \s-1REUSE\s0"
.Ip "\s-1CLASS\s0 \s-1CONTEXT\s0 \s-1AND\s0 \s-1THE\s0 \s-1OBJECT\s0" 0
.IX Item "\s-1CLASS\s0 \s-1CONTEXT\s0 \s-1AND\s0 \s-1THE\s0 \s-1OBJECT\s0"
.Ip "\s-1INHERITING\s0 A \s-1CONSTRUCTOR\s0" 0
.IX Item "\s-1INHERITING\s0 A \s-1CONSTRUCTOR\s0"
.Ip "\s-1DELEGATION\s0" 0
.IX Item "\s-1DELEGATION\s0"
.Sh "perldebug \- Perl debugging"
.IX Subsection "perldebug \- Perl debugging"
.Ip "\s-1DESCRIPTION\s0" 0
.IX Item "\s-1DESCRIPTION\s0"
.Ip "Debugging" 5
.IX Item "Debugging"
h, T, s, n, f, c, c line, <\s-1CR\s0>, l min+incr, l min-max, l line, l, \-, w
line, l subname, /pattern/, ?pattern?, L, S, t, b line [ condition ], b
subname [ condition ], d line, D, a line command, A, < command, >
command, V package [symbols], X [symbols], ! number, ! \-number, H
\-number, q or ^D, command, p expr
.Ip "Customization" 5
.IX Item "Customization"
.Ip "Other resources" 5
.IX Item "Other resources"
.Ip "\s-1BUGS\s0" 0
.IX Item "\s-1BUGS\s0"
.Sh "perldiag \- various Perl diagnostics"
.IX Subsection "perldiag \- various Perl diagnostics"
.Ip "\s-1DESCRIPTION\s0" 0
.IX Item "\s-1DESCRIPTION\s0"
.Sh "perlform \- Perl formats"
.IX Subsection "perlform \- Perl formats"
.Ip "\s-1DESCRIPTION\s0" 0
.IX Item "\s-1DESCRIPTION\s0"
.Ip "Format Variables" 5
.IX Item "Format Variables"
.Ip "\s-1NOTES\s0" 0
.IX Item "\s-1NOTES\s0"
.Ip "Footers" 5
.IX Item "Footers"
.Ip "Accessing Formatting Internals" 5
.IX Item "Accessing Formatting Internals"
.Ip "\s-1WARNING\s0" 0
.IX Item "\s-1WARNING\s0"
.Sh "perlipc \- Perl interprocess communication (signals, fifos, pipes, safe subprocceses, sockets, and semaphores)"
.IX Subsection "perlipc \- Perl interprocess communication (signals, fifos, pipes, safe subprocceses, sockets, and semaphores)"
.Ip "\s-1DESCRIPTION\s0" 0
.IX Item "\s-1DESCRIPTION\s0"
.Ip "Signals" 0
.IX Item "Signals"
.Ip "Named Pipes" 0
.IX Item "Named Pipes"
.Ip "Using open() for \s-1IPC\s0" 0
.IX Item "Using open() for \s-1IPC\s0"
.Ip "Safe Pipe Opens" 5
.IX Item "Safe Pipe Opens"
.Ip "Bidirectional Communication" 5
.IX Item "Bidirectional Communication"
.Ip "Sockets: Client/Server Communication" 0
.IX Item "Sockets: Client/Server Communication"
.Ip "Internet \s-1TCP\s0 Clients and Servers" 5
.IX Item "Internet \s-1TCP\s0 Clients and Servers"
.Ip "Unix-Domain \s-1TCP\s0 Clients and Servers" 5
.IX Item "Unix-Domain \s-1TCP\s0 Clients and Servers"
.Ip "\s-1UDP\s0: Message Passing" 5
.IX Item "\s-1UDP\s0: Message Passing"
.Ip "SysV \s-1IPC\s0" 0
.IX Item "SysV \s-1IPC\s0"
.Ip "\s-1WARNING\s0" 0
.IX Item "\s-1WARNING\s0"
.Ip "\s-1NOTES\s0" 0
.IX Item "\s-1NOTES\s0"
.Ip "\s-1BUGS\s0" 0
.IX Item "\s-1BUGS\s0"
.Ip "\s-1AUTHOR\s0" 0
.IX Item "\s-1AUTHOR\s0"
.Ip "\s-1SEE\s0 \s-1ALSO\s0" 0
.IX Item "\s-1SEE\s0 \s-1ALSO\s0"
.Sh "perlsec \- Perl security"
.IX Subsection "perlsec \- Perl security"
.Ip "\s-1DESCRIPTION\s0" 0
.IX Item "\s-1DESCRIPTION\s0"
.Sh "perltrap \- Perl traps for the unwary"
.IX Subsection "perltrap \- Perl traps for the unwary"
.Ip "\s-1DESCRIPTION\s0" 0
.IX Item "\s-1DESCRIPTION\s0"
.Ip "Awk Traps" 5
.IX Item "Awk Traps"
.Ip "C Traps" 5
.IX Item "C Traps"
.Ip "Sed Traps" 5
.IX Item "Sed Traps"
.Ip "Shell Traps" 5
.IX Item "Shell Traps"
.Ip "Perl Traps" 5
.IX Item "Perl Traps"
.Ip "Perl4 Traps" 5
.IX Item "Perl4 Traps"
.Sh "perlstyle \- Perl style guide"
.IX Subsection "perlstyle \- Perl style guide"
.Ip "\s-1DESCRIPTION\s0" 0
.IX Item "\s-1DESCRIPTION\s0"
.Sh "perlxs \- \s-1XS\s0 language reference manual"
.IX Subsection "perlxs \- \s-1XS\s0 language reference manual"
.Ip "\s-1DESCRIPTION\s0" 0
.IX Item "\s-1DESCRIPTION\s0"
.Ip "Introduction" 5
.IX Item "Introduction"
.Ip "On The Road" 5
.IX Item "On The Road"
.Ip "The Anatomy of an \s-1XSUB\s0" 5
.IX Item "The Anatomy of an \s-1XSUB\s0"
.Ip "The Argument Stack" 5
.IX Item "The Argument Stack"
.Ip "The \s-1RETVAL\s0 Variable" 5
.IX Item "The \s-1RETVAL\s0 Variable"
.Ip "The \s-1MODULE\s0 Keyword" 5
.IX Item "The \s-1MODULE\s0 Keyword"
.Ip "The \s-1PACKAGE\s0 Keyword" 5
.IX Item "The \s-1PACKAGE\s0 Keyword"
.Ip "The \s-1PREFIX\s0 Keyword" 5
.IX Item "The \s-1PREFIX\s0 Keyword"
.Ip "The \s-1OUTPUT\s0: Keyword" 5
.IX Item "The \s-1OUTPUT\s0: Keyword"
.Ip "The \s-1CODE\s0: Keyword" 5
.IX Item "The \s-1CODE\s0: Keyword"
.Ip "The \s-1INIT\s0: Keyword" 5
.IX Item "The \s-1INIT\s0: Keyword"
.Ip "The \s-1NO_INIT\s0 Keyword" 5
.IX Item "The \s-1NO_INIT\s0 Keyword"
.Ip "Initializing Function Parameters" 5
.IX Item "Initializing Function Parameters"
.Ip "Default Parameter Values" 5
.IX Item "Default Parameter Values"
.Ip "The \s-1PREINIT\s0: Keyword" 5
.IX Item "The \s-1PREINIT\s0: Keyword"
.Ip "The \s-1INPUT\s0: Keyword" 5
.IX Item "The \s-1INPUT\s0: Keyword"
.Ip "Variable-length Parameter Lists" 5
.IX Item "Variable-length Parameter Lists"
.Ip "The \s-1PPCODE\s0: Keyword" 5
.IX Item "The \s-1PPCODE\s0: Keyword"
.Ip "Returning Undef And Empty Lists" 5
.IX Item "Returning Undef And Empty Lists"
.Ip "The \s-1REQUIRE\s0: Keyword" 5
.IX Item "The \s-1REQUIRE\s0: Keyword"
.Ip "The \s-1CLEANUP\s0: Keyword" 5
.IX Item "The \s-1CLEANUP\s0: Keyword"
.Ip "The \s-1BOOT\s0: Keyword" 5
.IX Item "The \s-1BOOT\s0: Keyword"
.Ip "The \s-1VERSIONCHECK\s0: Keyword" 5
.IX Item "The \s-1VERSIONCHECK\s0: Keyword"
.Ip "The \s-1PROTOTYPES\s0: Keyword" 5
.IX Item "The \s-1PROTOTYPES\s0: Keyword"
.Ip "The \s-1PROTOTYPE\s0: Keyword" 5
.IX Item "The \s-1PROTOTYPE\s0: Keyword"
.Ip "The \s-1ALIAS\s0: Keyword" 5
.IX Item "The \s-1ALIAS\s0: Keyword"
.Ip "The \s-1INCLUDE\s0: Keyword" 5
.IX Item "The \s-1INCLUDE\s0: Keyword"
.Ip "The \s-1CASE\s0: Keyword" 5
.IX Item "The \s-1CASE\s0: Keyword"
.Ip "The & Unary Operator" 5
.IX Item "The & Unary Operator"
.Ip "Inserting Comments and C Preprocessor Directives" 5
.IX Item "Inserting Comments and C Preprocessor Directives"
.Ip "Using \s-1XS\s0 With \*(C+" 5
.IX Item "Using \s-1XS\s0 With \*(C+"
.Ip "Interface Strategy" 5
.IX Item "Interface Strategy"
.Ip "Perl Objects And C Structures" 5
.IX Item "Perl Objects And C Structures"
.Ip "The Typemap" 5
.IX Item "The Typemap"
.Ip "\s-1EXAMPLES\s0" 0
.IX Item "\s-1EXAMPLES\s0"
.Ip "\s-1XS\s0 \s-1VERSION\s0" 0
.IX Item "\s-1XS\s0 \s-1VERSION\s0"
.Ip "\s-1AUTHOR\s0" 0
.IX Item "\s-1AUTHOR\s0"
.Sh "perlxstut, perlXStut \- Tutorial for \s-1XSUB\s0's"
.IX Subsection "perlxstut, perlXStut \- Tutorial for \s-1XSUB\s0's"
.Ip "\s-1DESCRIPTION\s0" 0
.IX Item "\s-1DESCRIPTION\s0"
.Ip "\s-1VERSION\s0 \s-1CAVEAT\s0" 5
.IX Item "\s-1VERSION\s0 \s-1CAVEAT\s0"
.Ip "\s-1DYNAMIC\s0 \s-1VERSUS\s0 \s-1STATIC\s0" 5
.IX Item "\s-1DYNAMIC\s0 \s-1VERSUS\s0 \s-1STATIC\s0"
.Ip "\s-1EXAMPLE\s0 1" 5
.IX Item "\s-1EXAMPLE\s0 1"
.Ip "\s-1EXAMPLE\s0 2" 5
.IX Item "\s-1EXAMPLE\s0 2"
.Ip "\s-1WHAT\s0 \s-1HAS\s0 \s-1GONE\s0 \s-1ON\s0?" 5
.IX Item "\s-1WHAT\s0 \s-1HAS\s0 \s-1GONE\s0 \s-1ON\s0?"
.Ip "\s-1EXAMPLE\s0 3" 5
.IX Item "\s-1EXAMPLE\s0 3"
.Ip "\s-1WHAT\s0'S \s-1NEW\s0 \s-1HERE\s0?" 5
.IX Item "\s-1WHAT\s0'S \s-1NEW\s0 \s-1HERE\s0?"
.Ip "\s-1INPUT\s0 \s-1AND\s0 \s-1OUTPUT\s0 \s-1PARAMETERS\s0" 5
.IX Item "\s-1INPUT\s0 \s-1AND\s0 \s-1OUTPUT\s0 \s-1PARAMETERS\s0"
.Ip "\s-1THE\s0 \s-1XSUBPP\s0 \s-1COMPILER\s0" 5
.IX Item "\s-1THE\s0 \s-1XSUBPP\s0 \s-1COMPILER\s0"
.Ip "\s-1THE\s0 \s-1TYPEMAP\s0 \s-1FILE\s0" 5
.IX Item "\s-1THE\s0 \s-1TYPEMAP\s0 \s-1FILE\s0"
.Ip "\s-1WARNING\s0" 5
.IX Item "\s-1WARNING\s0"
.Ip "\s-1SPECIFYING\s0 \s-1ARGUMENTS\s0 \s-1TO\s0 \s-1XSUBPP\s0" 5
.IX Item "\s-1SPECIFYING\s0 \s-1ARGUMENTS\s0 \s-1TO\s0 \s-1XSUBPP\s0"
.Ip "\s-1THE\s0 \s-1ARGUMENT\s0 \s-1STACK\s0" 5
.IX Item "\s-1THE\s0 \s-1ARGUMENT\s0 \s-1STACK\s0"
.Ip "\s-1EXTENDING\s0 \s-1YOUR\s0 \s-1EXTENSION\s0" 5
.IX Item "\s-1EXTENDING\s0 \s-1YOUR\s0 \s-1EXTENSION\s0"
.Ip "\s-1DOCUMENTING\s0 \s-1YOUR\s0 \s-1EXTENSION\s0" 5
.IX Item "\s-1DOCUMENTING\s0 \s-1YOUR\s0 \s-1EXTENSION\s0"
.Ip "\s-1INSTALLING\s0 \s-1YOUR\s0 \s-1EXTENSION\s0" 5
.IX Item "\s-1INSTALLING\s0 \s-1YOUR\s0 \s-1EXTENSION\s0"
.Ip "\s-1SEE\s0 \s-1ALSO\s0" 5
.IX Item "\s-1SEE\s0 \s-1ALSO\s0"
.Ip "Author" 5
.IX Item "Author"
.Ip "Last Changed" 5
.IX Item "Last Changed"
.Sh "perlguts \- Perl's Internal Functions"
.IX Subsection "perlguts \- Perl's Internal Functions"
.Ip "\s-1DESCRIPTION\s0" 0
.IX Item "\s-1DESCRIPTION\s0"
.Ip "Datatypes" 0
.IX Item "Datatypes"
.Ip "What is an \*(L"\s-1IV\s0\*(R"?" 5
.IX Item "What is an \*(L"\s-1IV\s0\*(R"?"
.Ip "Working with \s-1SV\s0's" 5
.IX Item "Working with \s-1SV\s0's"
.Ip "What's Really Stored in an \s-1SV\s0?" 5
.IX Item "What's Really Stored in an \s-1SV\s0?"
.Ip "Working with \s-1AV\s0's" 5
.IX Item "Working with \s-1AV\s0's"
.Ip "Working with \s-1HV\s0's" 5
.IX Item "Working with \s-1HV\s0's"
.Ip "References" 5
.IX Item "References"
.Ip "Blessed References and Class Objects" 5
.IX Item "Blessed References and Class Objects"
.Ip "Creating New Variables" 0
.IX Item "Creating New Variables"
.Ip "\s-1XSUB\s0's and the Argument Stack" 0
.IX Item "\s-1XSUB\s0's and the Argument Stack"
.Ip "Mortality" 0
.IX Item "Mortality"
.Ip "Stashes" 0
.IX Item "Stashes"
.Ip "Magic" 0
.IX Item "Magic"
.Ip "Assigning Magic" 5
.IX Item "Assigning Magic"
.Ip "Magic Virtual Tables" 5
.IX Item "Magic Virtual Tables"
.Ip "Finding Magic" 5
.IX Item "Finding Magic"
.Ip "Double-Typed \s-1SV\s0's" 0
.IX Item "Double-Typed \s-1SV\s0's"
.Ip "Calling Perl Routines from within C Programs" 0
.IX Item "Calling Perl Routines from within C Programs"
.Ip "Memory Allocation" 0
.IX Item "Memory Allocation"
.Ip "\s-1API\s0 \s-1LISTING\s0" 0
.IX Item "\s-1API\s0 \s-1LISTING\s0"
AvFILL, av_clear, av_extend, av_fetch, av_len, av_make, av_pop,
av_push, av_shift, av_store, av_undef, av_unshift, \s-1CLASS\s0, Copy, croak,
CvSTASH, DBsingle, DBsub, dMARK, dORIGMARK, dSP, dXSARGS, \s-1ENTER\s0,
\s-1EXTEND\s0, \s-1FREETMPS\s0, G_ARRAY, G_DISCARD, G_EVAL, \s-1GIMME\s0, G_NOARGS,
G_SCALAR, gv_stashpv, gv_stashsv, GvSV, he_free, hv_clear, hv_delete,
hv_exists, hv_fetch, hv_iterinit, hv_iterkey, hv_iternext,
hv_iternextsv, hv_iterval, hv_magic, HvNAME, hv_store, hv_undef,
isALNUM, isALPHA, isDIGIT, isLOWER, isSPACE, isUPPER, items, \s-1LEAVE\s0,
\s-1MARK\s0, mg_clear, mg_copy, mg_find, mg_free, mg_get, mg_len, mg_magical,
mg_set, Move, na, New, Newc, Newz, newAV, newHV, newRV, newSV, newSViv,
newSVnv, newSVpv, newSVrv, newSVsv, newXS, newXSproto, Nullav, Nullch,
Nullcv, Nullhv, Nullsv, \s-1ORIGMARK\s0, perl_alloc, perl_call_argv,
perl_call_method, perl_call_pv, perl_call_sv, perl_construct,
perl_destruct, perl_eval_sv, perl_free, perl_get_av, perl_get_cv,
perl_get_hv, perl_get_sv, perl_parse, perl_require_pv, perl_run, POPi,
POPl, POPp, POPn, POPs,
.Ip "\s-1AUTHOR\s0" 0
.IX Item "\s-1AUTHOR\s0"
.Ip "\s-1DATE\s0" 0
.IX Item "\s-1DATE\s0"
.Sh "perlcall \- Perl calling conventions from C"
.IX Subsection "perlcall \- Perl calling conventions from C"
.Ip "\s-1DESCRIPTION\s0" 0
.IX Item "\s-1DESCRIPTION\s0"
An Error Handler, An Event Driven Program
.Ip "\s-1THE\s0 \s-1PERL_CALL\s0 \s-1FUNCTIONS\s0" 0
.IX Item "\s-1THE\s0 \s-1PERL_CALL\s0 \s-1FUNCTIONS\s0"
\fBperl_call_sv\fR, \fBperl_call_pv\fR, \fBperl_call_method\fR,
\fBperl_call_argv\fR
.Ip "\s-1FLAG\s0 \s-1VALUES\s0" 0
.IX Item "\s-1FLAG\s0 \s-1VALUES\s0"
.Ip "G_SCALAR" 5
.IX Item "G_SCALAR"
.Ip "G_ARRAY" 5
.IX Item "G_ARRAY"
.Ip "G_DISCARD" 5
.IX Item "G_DISCARD"
.Ip "G_NOARGS" 5
.IX Item "G_NOARGS"
.Ip "G_EVAL" 5
.IX Item "G_EVAL"
.Ip "G_KEEPERR" 5
.IX Item "G_KEEPERR"
.Ip "Determining the Context" 5
.IX Item "Determining the Context"
.Ip "\s-1KNOWN\s0 \s-1PROBLEMS\s0" 0
.IX Item "\s-1KNOWN\s0 \s-1PROBLEMS\s0"
.Ip "\s-1EXAMPLES\s0" 0
.IX Item "\s-1EXAMPLES\s0"
.Ip "No Parameters, Nothing returned" 5
.IX Item "No Parameters, Nothing returned"
.Ip "Passing Parameters" 5
.IX Item "Passing Parameters"
.Ip "Returning a Scalar" 5
.IX Item "Returning a Scalar"
.Ip "Returning a list of values" 5
.IX Item "Returning a list of values"
.Ip "Returning a list in a scalar context" 5
.IX Item "Returning a list in a scalar context"
.Ip "Returning Data from Perl via the parameter list" 5
.IX Item "Returning Data from Perl via the parameter list"
.Ip "Using G_EVAL" 5
.IX Item "Using G_EVAL"
.Ip "Using G_KEEPERR" 5
.IX Item "Using G_KEEPERR"
.Ip "Using perl_call_sv" 5
.IX Item "Using perl_call_sv"
.Ip "Using perl_call_argv" 5
.IX Item "Using perl_call_argv"
.Ip "Using perl_call_method" 5
.IX Item "Using perl_call_method"
.Ip "Using \s-1GIMME\s0" 5
.IX Item "Using \s-1GIMME\s0"
.Ip "Using Perl to dispose of temporaries" 5
.IX Item "Using Perl to dispose of temporaries"
.Ip "Strategies for storing Callback Context Information" 5
.IX Item "Strategies for storing Callback Context Information"
1. Ignore the problem \- Allow only 1 callback, 2. Create a sequence of
callbacks \- hard wired limit, 3. Use a parameter to map to the Perl
callback
.Ip "Alternate Stack Manipulation" 5
.IX Item "Alternate Stack Manipulation"
.Ip "\s-1SEE\s0 \s-1ALSO\s0" 0
.IX Item "\s-1SEE\s0 \s-1ALSO\s0"
.Ip "\s-1AUTHOR\s0" 0
.IX Item "\s-1AUTHOR\s0"
.Ip "\s-1DATE\s0" 0
.IX Item "\s-1DATE\s0"
.Sh "perlembed \- how to embed perl in your C program"
.IX Subsection "perlembed \- how to embed perl in your C program"
.Ip "\s-1DESCRIPTION\s0" 0
.IX Item "\s-1DESCRIPTION\s0"
.Ip "\s-1PREAMBLE\s0" 5
.IX Item "\s-1PREAMBLE\s0"
\fBUse C from Perl?\fR, \fBUse a \s-1UNIX\s0 program from Perl?\fR, \fBUse Perl from
Perl?\fR, \fBUse C from C?\fR, \fBUse Perl from C?\fR
.Ip "\s-1ROADMAP\s0" 5
.IX Item "\s-1ROADMAP\s0"
.Ip "Compiling your C program" 5
.IX Item "Compiling your C program"
.Ip "Adding a Perl interpreter to your C program" 5
.IX Item "Adding a Perl interpreter to your C program"
.Ip "Calling a Perl subroutine from your C program" 5
.IX Item "Calling a Perl subroutine from your C program"
.Ip "Evaluating a Perl statement from your C program" 5
.IX Item "Evaluating a Perl statement from your C program"
.Ip "Performing Perl pattern matches and substitutions from your C program" 5
.IX Item "Performing Perl pattern matches and substitutions from your C program"
.Ip "\s-1MORAL\s0" 0
.IX Item "\s-1MORAL\s0"
.Ip "\s-1AUTHOR\s0" 0
.IX Item "\s-1AUTHOR\s0"
.Sh "perlpod \- plain old documentation"
.IX Subsection "perlpod \- plain old documentation"
.Ip "\s-1DESCRIPTION\s0" 0
.IX Item "\s-1DESCRIPTION\s0"
.Ip "Embedding Pods in Perl Modules" 0
.IX Item "Embedding Pods in Perl Modules"
.Ip "\s-1SEE\s0 \s-1ALSO\s0" 0
.IX Item "\s-1SEE\s0 \s-1ALSO\s0"
.Ip "\s-1AUTHOR\s0" 0
.IX Item "\s-1AUTHOR\s0"
.Sh "perlbook \- Perl book information"
.IX Subsection "perlbook \- Perl book information"
.Ip "\s-1DESCRIPTION\s0" 0
.IX Item "\s-1DESCRIPTION\s0"
.SH "PRAGMA DOCUMENTATION"
.IX Header "PRAGMA DOCUMENTATION"
.Sh "diagnostics \- Perl compiler pragma to force verbose warning diagnostics"
.IX Subsection "diagnostics \- Perl compiler pragma to force verbose warning diagnostics"
.Ip "\s-1SYNOPSIS\s0" 0
.IX Item "\s-1SYNOPSIS\s0"
.Ip "\s-1DESCRIPTION\s0" 0
.IX Item "\s-1DESCRIPTION\s0"
.Ip "The \f(CWdiagnostics\fR Pragma" 5
.IX Item "The \f(CWdiagnostics\fR Pragma"
.Ip "The \fIsplain\fR Program" 5
.IX Item "The \fIsplain\fR Program"
.Ip "\s-1EXAMPLES\s0" 0
.IX Item "\s-1EXAMPLES\s0"
.Ip "\s-1INTERNALS\s0" 0
.IX Item "\s-1INTERNALS\s0"
.Ip "\s-1BUGS\s0" 0
.IX Item "\s-1BUGS\s0"
.Ip "\s-1AUTHOR\s0" 0
.IX Item "\s-1AUTHOR\s0"
.Sh "integer \- Perl pragma to compute arithmetic in integer instead of double"
.IX Subsection "integer \- Perl pragma to compute arithmetic in integer instead of double"
.Ip "\s-1SYNOPSIS\s0" 0
.IX Item "\s-1SYNOPSIS\s0"
.Ip "\s-1DESCRIPTION\s0" 0
.IX Item "\s-1DESCRIPTION\s0"
.Sh "less \- perl pragma to request less of something from the compiler"
.IX Subsection "less \- perl pragma to request less of something from the compiler"
.Ip "\s-1SYNOPSIS\s0" 0
.IX Item "\s-1SYNOPSIS\s0"
.Ip "\s-1DESCRIPTION\s0" 0
.IX Item "\s-1DESCRIPTION\s0"
.Sh "lib \- manipulate \f(CW@INC\fR at compile time"
.IX Subsection "lib \- manipulate \f(CW@INC\fR at compile time"
.Ip "\s-1SYNOPSIS\s0" 0
.IX Item "\s-1SYNOPSIS\s0"
.Ip "\s-1DESCRIPTION\s0" 0
.IX Item "\s-1DESCRIPTION\s0"
.Ip "\s-1ADDING\s0 \s-1DIRECTORIES\s0 \s-1TO\s0 @\s-1INC\s0" 5
.IX Item "\s-1ADDING\s0 \s-1DIRECTORIES\s0 \s-1TO\s0 @\s-1INC\s0"
.Ip "\s-1DELETING\s0 \s-1DIRECTORIES\s0 \s-1FROM\s0 @\s-1INC\s0" 5
.IX Item "\s-1DELETING\s0 \s-1DIRECTORIES\s0 \s-1FROM\s0 @\s-1INC\s0"
.Ip "\s-1RESTORING\s0 \s-1ORIGINAL\s0 @\s-1INC\s0" 5
.IX Item "\s-1RESTORING\s0 \s-1ORIGINAL\s0 @\s-1INC\s0"
.Ip "\s-1SEE\s0 \s-1ALSO\s0" 0
.IX Item "\s-1SEE\s0 \s-1ALSO\s0"
.Ip "\s-1AUTHOR\s0" 0
.IX Item "\s-1AUTHOR\s0"
.Sh "overload \- Package for overloading perl operations"
.IX Subsection "overload \- Package for overloading perl operations"
.Ip "\s-1SYNOPSIS\s0" 0
.IX Item "\s-1SYNOPSIS\s0"
.Ip "\s-1CAVEAT\s0 \s-1SCRIPTOR\s0" 0
.IX Item "\s-1CAVEAT\s0 \s-1SCRIPTOR\s0"
.Ip "\s-1DESCRIPTION\s0" 0
.IX Item "\s-1DESCRIPTION\s0"
.Ip "Declaration of overloaded functions" 5
.IX Item "Declaration of overloaded functions"
.Ip "Calling Conventions for Binary Operations" 5
.IX Item "Calling Conventions for Binary Operations"
\s-1FALSE\s0, \s-1TRUE\s0, \f(CWundef\fR
.Ip "Calling Conventions for Unary Operations" 5
.IX Item "Calling Conventions for Unary Operations"
.Ip "Overloadable Operations" 5
.IX Item "Overloadable Operations"
\fIArithmetic operations\fR, \fIComparison operations\fR, \fIBit operations\fR,
\fIIncrement and decrement\fR, \fITranscendental functions\fR, \fIBoolean,
string and numeric conversion\fR, \fISpecial\fR
.Ip "\s-1SPECIAL\s0 \s-1SYMBOLS\s0 \s-1FOR\s0 \f(CWuse overload\fR" 0
.IX Item "\s-1SPECIAL\s0 \s-1SYMBOLS\s0 \s-1FOR\s0 \f(CWuse overload\fR"
.Ip "Last Resort" 5
.IX Item "Last Resort"
.Ip "Fallback" 5
.IX Item "Fallback"
\f(CWundef\fR, \s-1TRUE\s0, defined, but \s-1FALSE\s0
.Ip "Copy Constructor" 5
.IX Item "Copy Constructor"
\fBExample\fR
.Ip "\s-1MAGIC\s0 \s-1AUTOGENERATION\s0" 0
.IX Item "\s-1MAGIC\s0 \s-1AUTOGENERATION\s0"
\fIAssignment forms of arithmetic operations\fR, \fIConversion operations\fR,
\fIIncrement and decrement\fR, \f(CWabs($a)\fR, \fIUnary minus\fR,
\fIConcatenation\fR, \fIComparison operations\fR, \fICopy operator\fR
.Ip "\s-1WARNING\s0" 0
.IX Item "\s-1WARNING\s0"
.Ip "Run-time Overloading" 0
.IX Item "Run-time Overloading"
.Ip "Public functions" 0
.IX Item "Public functions"
overload::\fIStrVal\fR\|(arg), overload::\fIOverloaded\fR\|(arg),
\f(CWoverload::Method(obj,op)\fR
.Ip "\s-1IMPLEMENTATION\s0" 0
.IX Item "\s-1IMPLEMENTATION\s0"
.Ip "\s-1AUTHOR\s0" 0
.IX Item "\s-1AUTHOR\s0"
.Ip "\s-1DIAGNOSTICS\s0" 0
.IX Item "\s-1DIAGNOSTICS\s0"
.Ip "\s-1BUGS\s0" 0
.IX Item "\s-1BUGS\s0"
.Sh "sigtrap \- Perl pragma to enable stack backtrace on unexpected signals"
.IX Subsection "sigtrap \- Perl pragma to enable stack backtrace on unexpected signals"
.Ip "\s-1SYNOPSIS\s0" 0
.IX Item "\s-1SYNOPSIS\s0"
.Ip "\s-1DESCRIPTION\s0" 0
.IX Item "\s-1DESCRIPTION\s0"
.Sh "strict \- Perl pragma to restrict unsafe constructs"
.IX Subsection "strict \- Perl pragma to restrict unsafe constructs"
.Ip "\s-1SYNOPSIS\s0" 0
.IX Item "\s-1SYNOPSIS\s0"
.Ip "\s-1DESCRIPTION\s0" 0
.IX Item "\s-1DESCRIPTION\s0"
\f(CWstrict refs\fR, \f(CWstrict vars\fR, \f(CWstrict subs\fR
.Sh "subs \- Perl pragma to predeclare sub names"
.IX Subsection "subs \- Perl pragma to predeclare sub names"
.Ip "\s-1SYNOPSIS\s0" 0
.IX Item "\s-1SYNOPSIS\s0"
.Ip "\s-1DESCRIPTION\s0" 0
.IX Item "\s-1DESCRIPTION\s0"
.Sh "vars \- Perl pragma to predeclare global variable names"
.IX Subsection "vars \- Perl pragma to predeclare global variable names"
.Ip "\s-1SYNOPSIS\s0" 0
.IX Item "\s-1SYNOPSIS\s0"
.Ip "\s-1DESCRIPTION\s0" 0
.IX Item "\s-1DESCRIPTION\s0"
.SH "MODULE DOCUMENTATION"
.IX Header "MODULE DOCUMENTATION"
.Sh "AnyDBM_File \- provide framework for multiple DBMs"
.IX Subsection "AnyDBM_File \- provide framework for multiple DBMs"
.Ip "\s-1SYNOPSIS\s0" 0
.IX Item "\s-1SYNOPSIS\s0"
.Ip "\s-1DESCRIPTION\s0" 0
.IX Item "\s-1DESCRIPTION\s0"
.Ip "\s-1DBM\s0 Comparisons" 5
.IX Item "\s-1DBM\s0 Comparisons"
[0], [1], [2], [3]
.Ip "\s-1SEE\s0 \s-1ALSO\s0" 0
.IX Item "\s-1SEE\s0 \s-1ALSO\s0"
.Sh "AutoLoader \- load functions only on demand"
.IX Subsection "AutoLoader \- load functions only on demand"
.Ip "\s-1SYNOPSIS\s0" 0
.IX Item "\s-1SYNOPSIS\s0"
.Ip "\s-1DESCRIPTION\s0" 0
.IX Item "\s-1DESCRIPTION\s0"
.Sh "AutoSplit \- split a package for autoloading"
.IX Subsection "AutoSplit \- split a package for autoloading"
.Ip "\s-1SYNOPSIS\s0" 0
.IX Item "\s-1SYNOPSIS\s0"
.Ip "\s-1DESCRIPTION\s0" 0
.IX Item "\s-1DESCRIPTION\s0"
.Sh "Benchmark \- benchmark running times of code"
.IX Subsection "Benchmark \- benchmark running times of code"
.Ip "\s-1SYNOPSIS\s0" 0
.IX Item "\s-1SYNOPSIS\s0"
.Ip "\s-1DESCRIPTION\s0" 0
.IX Item "\s-1DESCRIPTION\s0"
.Ip "Methods" 5
.IX Item "Methods"
new, debug
.Ip "Standard Exports" 5
.IX Item "Standard Exports"
\f(CWtimeit(COUNT, CODE)\fR, timethis, timethese, timediff, timestr
.Ip "Optional Exports" 5
.IX Item "Optional Exports"
.Ip "\s-1NOTES\s0" 0
.IX Item "\s-1NOTES\s0"
.Ip "\s-1INHERITANCE\s0" 0
.IX Item "\s-1INHERITANCE\s0"
.Ip "\s-1CAVEATS\s0" 0
.IX Item "\s-1CAVEATS\s0"
.Ip "\s-1AUTHORS\s0" 0
.IX Item "\s-1AUTHORS\s0"
.Ip "\s-1MODIFICATION\s0 \s-1HISTORY\s0" 0
.IX Item "\s-1MODIFICATION\s0 \s-1HISTORY\s0"
.Sh "Carp, carp \- warn of errors (from perspective of caller)"
.IX Subsection "Carp, carp \- warn of errors (from perspective of caller)"
.Ip "\s-1SYNOPSIS\s0" 0
.IX Item "\s-1SYNOPSIS\s0"
.Ip "\s-1DESCRIPTION\s0" 0
.IX Item "\s-1DESCRIPTION\s0"
.Sh "Cwd, getcwd \- get pathname of current working directory"
.IX Subsection "Cwd, getcwd \- get pathname of current working directory"
.Ip "\s-1SYNOPSIS\s0" 0
.IX Item "\s-1SYNOPSIS\s0"
.Ip "\s-1DESCRIPTION\s0" 0
.IX Item "\s-1DESCRIPTION\s0"
.Sh "DB_File \- Perl5 access to Berkeley \s-1DB\s0"
.IX Subsection "DB_File \- Perl5 access to Berkeley \s-1DB\s0"
.Ip "\s-1SYNOPSIS\s0" 0
.IX Item "\s-1SYNOPSIS\s0"
.Ip "\s-1DESCRIPTION\s0" 0
.IX Item "\s-1DESCRIPTION\s0"
\s-1DB_HASH\s0, \s-1DB_BTREE\s0, \s-1DB_RECNO\s0
.Ip "How does DB_File interface to Berkeley \s-1DB\s0?" 5
.IX Item "How does DB_File interface to Berkeley \s-1DB\s0?"
.Ip "Differences with Berkeley \s-1DB\s0" 5
.IX Item "Differences with Berkeley \s-1DB\s0"
.Ip "\s-1RECNO\s0" 5
.IX Item "\s-1RECNO\s0"
.Ip "In Memory Databases" 5
.IX Item "In Memory Databases"
.Ip "Using the Berkeley \s-1DB\s0 Interface Directly" 5
.IX Item "Using the Berkeley \s-1DB\s0 Interface Directly"
get, put, del, fd, seq, sync
.Ip "\s-1EXAMPLES\s0" 0
.IX Item "\s-1EXAMPLES\s0"
.Ip "Using \s-1HASH\s0" 5
.IX Item "Using \s-1HASH\s0"
.Ip "Using \s-1BTREE\s0" 5
.IX Item "Using \s-1BTREE\s0"
.Ip "Using \s-1RECNO\s0" 5
.IX Item "Using \s-1RECNO\s0"
.Ip "Locking Databases" 5
.IX Item "Locking Databases"
.Ip "\s-1HISTORY\s0" 0
.IX Item "\s-1HISTORY\s0"
.Ip "\s-1WARNINGS\s0" 0
.IX Item "\s-1WARNINGS\s0"
.Ip "\s-1BUGS\s0" 0
.IX Item "\s-1BUGS\s0"
.Ip "\s-1AVAILABILITY\s0" 0
.IX Item "\s-1AVAILABILITY\s0"
.Ip "\s-1SEE\s0 \s-1ALSO\s0" 0
.IX Item "\s-1SEE\s0 \s-1ALSO\s0"
.Ip "\s-1AUTHOR\s0" 0
.IX Item "\s-1AUTHOR\s0"
.Sh "Devel::SelfStubber \- generate stubs for a SelfLoading module"
.IX Subsection "Devel::SelfStubber \- generate stubs for a SelfLoading module"
.Ip "\s-1SYNOPSIS\s0" 0
.IX Item "\s-1SYNOPSIS\s0"
.Ip "\s-1DESCRIPTION\s0" 0
.IX Item "\s-1DESCRIPTION\s0"
.Sh "DirHandle \- supply object methods for directory handles"
.IX Subsection "DirHandle \- supply object methods for directory handles"
.Ip "\s-1SYNOPSIS\s0" 0
.IX Item "\s-1SYNOPSIS\s0"
.Ip "\s-1DESCRIPTION\s0" 0
.IX Item "\s-1DESCRIPTION\s0"
.Sh "DynaLoader \- Dynamically load C libraries into Perl code"
.IX Subsection "DynaLoader \- Dynamically load C libraries into Perl code"
.Ip "\s-1SYNOPSIS\s0" 0
.IX Item "\s-1SYNOPSIS\s0"
.Ip "\s-1DESCRIPTION\s0" 0
.IX Item "\s-1DESCRIPTION\s0"
@dl_library_path, \f(CW@dl_resolve_using\fR, \f(CW@dl_require_symbols\fR, \fIdl_error()\fR,
\f(CW$dl_debug\fR, \fIdl_findfile()\fR, \fIdl_expandspec()\fR, \fIdl_load_file()\fR,
\fIdl_find_symbol()\fR, \fIdl_undef_symbols()\fR, \fIdl_install_xsub()\fR, \fIboostrap()\fR
.Ip "\s-1AUTHOR\s0" 0
.IX Item "\s-1AUTHOR\s0"
.Sh "English \- use nice English (or awk) names for ugly punctuation variables"
.IX Subsection "English \- use nice English (or awk) names for ugly punctuation variables"
.Ip "\s-1SYNOPSIS\s0" 0
.IX Item "\s-1SYNOPSIS\s0"
.Ip "\s-1DESCRIPTION\s0" 0
.IX Item "\s-1DESCRIPTION\s0"
.Sh "Env \- perl module that imports environment variables"
.IX Subsection "Env \- perl module that imports environment variables"
.Ip "\s-1SYNOPSIS\s0" 0
.IX Item "\s-1SYNOPSIS\s0"
.Ip "\s-1DESCRIPTION\s0" 0
.IX Item "\s-1DESCRIPTION\s0"
.Ip "\s-1AUTHOR\s0" 0
.IX Item "\s-1AUTHOR\s0"
.Sh "Exporter \- Implements default import method for modules"
.IX Subsection "Exporter \- Implements default import method for modules"
.Ip "\s-1SYNOPSIS\s0" 0
.IX Item "\s-1SYNOPSIS\s0"
.Ip "\s-1DESCRIPTION\s0" 0
.IX Item "\s-1DESCRIPTION\s0"
.Ip "Selecting What To Export" 5
.IX Item "Selecting What To Export"
.Ip "Specialised Import Lists" 5
.IX Item "Specialised Import Lists"
.Ip "Module Version Checking" 5
.IX Item "Module Version Checking"
.Ip "Managing Unknown Symbols" 5
.IX Item "Managing Unknown Symbols"
.Ip "Tag Handling Utility Functions" 5
.IX Item "Tag Handling Utility Functions"
.Sh "ExtUtils::Install \- install files from here to there"
.IX Subsection "ExtUtils::Install \- install files from here to there"
.Ip "\s-1SYNOPSIS\s0" 0
.IX Item "\s-1SYNOPSIS\s0"
.Ip "\s-1DESCRIPTION\s0" 0
.IX Item "\s-1DESCRIPTION\s0"
.Sh "ExtUtils::Liblist \- determine libraries to use and how to use them"
.IX Subsection "ExtUtils::Liblist \- determine libraries to use and how to use them"
.Ip "\s-1SYNOPSIS\s0" 0
.IX Item "\s-1SYNOPSIS\s0"
.Ip "\s-1DESCRIPTION\s0" 0
.IX Item "\s-1DESCRIPTION\s0"
For static extensions, For dynamic extensions, For dynamic extensions
.Ip "\s-1EXTRALIBS\s0" 5
.IX Item "\s-1EXTRALIBS\s0"
.Ip "\s-1LDLOADLIBS\s0 and \s-1LD_RUN_PATH\s0" 5
.IX Item "\s-1LDLOADLIBS\s0 and \s-1LD_RUN_PATH\s0"
.Ip "\s-1BSLOADLIBS\s0" 5
.IX Item "\s-1BSLOADLIBS\s0"
.Ip "\s-1PORTABILITY\s0" 0
.IX Item "\s-1PORTABILITY\s0"
.Ip "\s-1SEE\s0 \s-1ALSO\s0" 0
.IX Item "\s-1SEE\s0 \s-1ALSO\s0"
.Sh "ExtUtils::\s-1MM_OS2\s0 \- methods to override \s-1UN\s0*X behaviour in ExtUtils::MakeMaker"
.IX Subsection "ExtUtils::\s-1MM_OS2\s0 \- methods to override \s-1UN\s0*X behaviour in ExtUtils::MakeMaker"
.Ip "\s-1DESCRIPTION\s0" 0
.IX Item "\s-1DESCRIPTION\s0"
.Sh "ExtUtils::MM_Unix \- methods used by ExtUtils::MakeMaker"
.IX Subsection "ExtUtils::MM_Unix \- methods used by ExtUtils::MakeMaker"
.Ip "\s-1SYNOPSIS\s0" 0
.IX Item "\s-1SYNOPSIS\s0"
.Ip "\s-1DESCRIPTION\s0" 0
.IX Item "\s-1DESCRIPTION\s0"
.Ip "\s-1METHODS\s0" 0
.IX Item "\s-1METHODS\s0"
.Ip "Preloaded methods" 5
.IX Item "Preloaded methods"
catdir, catfile, nicetext, libscan, exescan, lsdir, path,
replace_manpage_separator, file_name_is_absolute, prefixify,
maybe_command_in_dirs, maybe_command, perl_script
.Ip "SelfLoaded methods" 5
.IX Item "SelfLoaded methods"
guess_name, init_main, init_dirscan, init_others, find_perl
.Ip "Methods to actually produce chunks of text for the Makefile" 5
.IX Item "Methods to actually produce chunks of text for the Makefile"
post_initialize, const_config, constants, const_loadlibs, const_cccmd,
tool_autosplit, tool_xsubpp, tools_other, dist, macro, depend,
post_constants, pasthru, c_o, xs_c, xs_o, top_targets, linkext, dlsyms,
dynamic, dynamic_bs, dynamic_lib, static, static_lib, installpm,
installpm_x, manifypods, processPL, installbin, subdirs, subdir_x,
clean, realclean, dist_basics, dist_core, dist_dir, dist_test, dist_ci,
install, force, perldepend, makefile, staticmake, test,
test_via_harness, test_via_script, postamble, makeaperl, extliblist,
dir_target, needs_linking, has_link_code, writedoc
.Ip "\s-1SEE\s0 \s-1ALSO\s0" 0
.IX Item "\s-1SEE\s0 \s-1ALSO\s0"
.Sh "ExtUtils::\s-1MM_VMS\s0 \- methods to override \s-1UN\s0*X behaviour in ExtUtils::MakeMaker"
.IX Subsection "ExtUtils::\s-1MM_VMS\s0 \- methods to override \s-1UN\s0*X behaviour in ExtUtils::MakeMaker"
.Ip "\s-1DESCRIPTION\s0" 0
.IX Item "\s-1DESCRIPTION\s0"
.Sh "ExtUtils::MakeMaker \- create an extension Makefile"
.IX Subsection "ExtUtils::MakeMaker \- create an extension Makefile"
.Ip "\s-1SYNOPSIS\s0" 0
.IX Item "\s-1SYNOPSIS\s0"
.Ip "\s-1DESCRIPTION\s0" 0
.IX Item "\s-1DESCRIPTION\s0"
.Ip "Hintsfile support" 5
.IX Item "Hintsfile support"
.Ip "What's new in version 5 of MakeMaker" 5
.IX Item "What's new in version 5 of MakeMaker"
.Ip "Incompatibilities between MakeMaker 5.00 and 4.23" 5
.IX Item "Incompatibilities between MakeMaker 5.00 and 4.23"
.Ip "Default Makefile Behaviour" 5
.IX Item "Default Makefile Behaviour"
.Ip "make test" 5
.IX Item "make test"
.Ip "make install" 5
.IX Item "make install"
.Ip "\s-1PREFIX\s0 attribute" 5
.IX Item "\s-1PREFIX\s0 attribute"
.Ip "\s-1AFS\s0 users" 5
.IX Item "\s-1AFS\s0 users"
.Ip "Static Linking of a new Perl Binary" 5
.IX Item "Static Linking of a new Perl Binary"
.Ip "Determination of Perl Library and Installation Locations" 5
.IX Item "Determination of Perl Library and Installation Locations"
.Ip "Useful Default Makefile Macros" 5
.IX Item "Useful Default Makefile Macros"
.Ip "Using Attributes and Parameters" 5
.IX Item "Using Attributes and Parameters"
C, \s-1CONFIG\s0, \s-1CONFIGURE\s0, \s-1DEFINE\s0, \s-1DIR\s0, \s-1DISTNAME\s0, \s-1DL_FUNCS\s0, \s-1DL_VARS\s0,
\s-1EXE_FILES\s0, \s-1FIRST_MAKEFILE\s0, \s-1FULLPERL\s0, H, \s-1INC\s0, \s-1INSTALLARCHLIB\s0,
\s-1INSTALLBIN\s0, \s-1INSTALLDIRS\s0, \s-1INSTALLMAN1DIR\s0, \s-1INSTALLMAN3DIR\s0,
\s-1INSTALLPRIVLIB\s0, \s-1INSTALLSITELIB\s0, \s-1INSTALLSITEARCH\s0, \s-1INST_ARCHLIB\s0,
\s-1INST_EXE\s0, \s-1INST_LIB\s0, \s-1INST_MAN1DIR\s0, \s-1INST_MAN3DIR\s0, \s-1LDFROM\s0, \s-1LIBPERL_A\s0,
\s-1LIBS\s0, \s-1LINKTYPE\s0, \s-1MAKEAPERL\s0, \s-1MAKEFILE\s0, \s-1MAN1PODS\s0, \s-1MAN3PODS\s0, \s-1MAP_TARGET\s0,
\s-1MYEXTLIB\s0, \s-1NAME\s0, \s-1NEEDS_LINKING\s0, \s-1NOECHO\s0, \s-1NORECURS\s0, \s-1OBJECT\s0, \s-1PERL\s0,
\s-1PERLMAINCC\s0, \s-1PERL_ARCHLIB\s0, \s-1PERL_LIB\s0, \s-1PERL_SRC\s0, \s-1PL_FILES\s0, \s-1PM\s0, \s-1PMLIBDIRS\s0,
\s-1PREFIX\s0, \s-1PREREQ\s0, \s-1SKIP\s0, \s-1TYPEMAPS\s0, \s-1VERSION\s0, \s-1VERSION_FROM\s0, \s-1XS\s0, \s-1XSOPT\s0,
\s-1XSPROTOARG\s0, \s-1XS_VERSION\s0
.Ip "Additional lowercase attributes" 5
.IX Item "Additional lowercase attributes"
clean, depend, dist, dynamic_lib, installpm, linkext, macro, realclean,
tool_autosplit
.Ip "Overriding MakeMaker Methods" 5
.IX Item "Overriding MakeMaker Methods"
.Ip "Distribution Support" 5
.IX Item "Distribution Support"
.Sp
.Vb 3
\&   make distcheck,    make skipcheck,    make distclean,    make
\&   manifest,    make distdir,    make tardist,    make dist,    make
\&   uutardist,    make shdist,    make ci
.Ve
.Ip "\s-1AUTHORS\s0" 0
.IX Item "\s-1AUTHORS\s0"
.Ip "\s-1MODIFICATION\s0 \s-1HISTORY\s0" 0
.IX Item "\s-1MODIFICATION\s0 \s-1HISTORY\s0"
.Ip "\s-1TODO\s0" 0
.IX Item "\s-1TODO\s0"
.Sh "ExtUtils::Manifest \- utilities to write and check a \s-1MANIFEST\s0 file"
.IX Subsection "ExtUtils::Manifest \- utilities to write and check a \s-1MANIFEST\s0 file"
.Ip "\s-1SYNOPSIS\s0" 0
.IX Item "\s-1SYNOPSIS\s0"
.Ip "\s-1DESCRIPTION\s0" 0
.IX Item "\s-1DESCRIPTION\s0"
.Ip "\s-1MANIFEST\s0.\s-1SKIP\s0" 0
.IX Item "\s-1MANIFEST\s0.\s-1SKIP\s0"
.Ip "\s-1EXPORT_OK\s0" 0
.IX Item "\s-1EXPORT_OK\s0"
.Ip "\s-1GLOBAL\s0 \s-1VARIABLES\s0" 0
.IX Item "\s-1GLOBAL\s0 \s-1VARIABLES\s0"
.Ip "\s-1DIAGNOSTICS\s0" 0
.IX Item "\s-1DIAGNOSTICS\s0"
\f(CWNot in MANIFEST:\fR \fIfile\fR, \f(CWNo such file:\fR \fIfile\fR, \f(CWMANIFEST:\fR
\fI$!\fR, \f(CWAdded to MANIFEST:\fR \fIfile\fR
.Ip "\s-1SEE\s0 \s-1ALSO\s0" 0
.IX Item "\s-1SEE\s0 \s-1ALSO\s0"
.Ip "\s-1AUTHOR\s0" 0
.IX Item "\s-1AUTHOR\s0"
.Sh "ExtUtils::Mkbootstrap \- make a bootstrap file for use by DynaLoader"
.IX Subsection "ExtUtils::Mkbootstrap \- make a bootstrap file for use by DynaLoader"
.Ip "\s-1SYNOPSIS\s0" 0
.IX Item "\s-1SYNOPSIS\s0"
.Ip "\s-1DESCRIPTION\s0" 0
.IX Item "\s-1DESCRIPTION\s0"
.Sh "ExtUtils::Mksymlists \- write linker options files for dynamic extension"
.IX Subsection "ExtUtils::Mksymlists \- write linker options files for dynamic extension"
.Ip "\s-1SYNOPSIS\s0" 0
.IX Item "\s-1SYNOPSIS\s0"
.Ip "\s-1DESCRIPTION\s0" 0
.IX Item "\s-1DESCRIPTION\s0"
\s-1NAME\s0, \s-1DL_FUNCS\s0, \s-1DL_VARS\s0, \s-1FILE\s0, \s-1FUNCLIST\s0, \s-1DLBASE\s0
.Ip "\s-1AUTHOR\s0" 0
.IX Item "\s-1AUTHOR\s0"
.Ip "\s-1REVISION\s0" 0
.IX Item "\s-1REVISION\s0"
.Sh "Fcntl \- load the C Fcntl.h defines"
.IX Subsection "Fcntl \- load the C Fcntl.h defines"
.Ip "\s-1SYNOPSIS\s0" 0
.IX Item "\s-1SYNOPSIS\s0"
.Ip "\s-1DESCRIPTION\s0" 0
.IX Item "\s-1DESCRIPTION\s0"
.Ip "\s-1NOTE\s0" 0
.IX Item "\s-1NOTE\s0"
.Sh "File::Basename, Basename \- parse file specifications"
.IX Subsection "File::Basename, Basename \- parse file specifications"
.Ip "\s-1SYNOPSIS\s0" 0
.IX Item "\s-1SYNOPSIS\s0"
.Ip "\s-1DESCRIPTION\s0" 0
.IX Item "\s-1DESCRIPTION\s0"
fileparse_set_fstype, fileparse
.Ip "\s-1EXAMPLES\s0" 0
.IX Item "\s-1EXAMPLES\s0"
\f(CWbasename\fR, \f(CWdirname\fR
.Sh "File::CheckTree, validate \- run many filetest checks on a tree"
.IX Subsection "File::CheckTree, validate \- run many filetest checks on a tree"
.Ip "\s-1SYNOPSIS\s0" 0
.IX Item "\s-1SYNOPSIS\s0"
.Ip "\s-1DESCRIPTION\s0" 0
.IX Item "\s-1DESCRIPTION\s0"
.Sh "File::Find, find \- traverse a file tree"
.IX Subsection "File::Find, find \- traverse a file tree"
.Ip "\s-1SYNOPSIS\s0" 0
.IX Item "\s-1SYNOPSIS\s0"
.Ip "\s-1DESCRIPTION\s0" 0
.IX Item "\s-1DESCRIPTION\s0"
.Sh "File::Path \- create or remove a series of directories"
.IX Subsection "File::Path \- create or remove a series of directories"
.Ip "\s-1SYNOPSIS\s0" 0
.IX Item "\s-1SYNOPSIS\s0"
.Ip "\s-1DESCRIPTION\s0" 0
.IX Item "\s-1DESCRIPTION\s0"
.Ip "\s-1AUTHORS\s0" 0
.IX Item "\s-1AUTHORS\s0"
.Ip "\s-1REVISION\s0" 0
.IX Item "\s-1REVISION\s0"
.Sh "FileCache \- keep more files open than the system permits"
.IX Subsection "FileCache \- keep more files open than the system permits"
.Ip "\s-1SYNOPSIS\s0" 0
.IX Item "\s-1SYNOPSIS\s0"
.Ip "\s-1DESCRIPTION\s0" 0
.IX Item "\s-1DESCRIPTION\s0"
.Ip "\s-1BUGS\s0" 0
.IX Item "\s-1BUGS\s0"
.Sh "FileHandle \- supply object methods for filehandles"
.IX Subsection "FileHandle \- supply object methods for filehandles"
.Ip "\s-1SYNOPSIS\s0" 0
.IX Item "\s-1SYNOPSIS\s0"
.Ip "\s-1DESCRIPTION\s0" 0
.IX Item "\s-1DESCRIPTION\s0"
.PP
.Vb 1
\&  $fh->print, $fh->printf, $fh->getline, $fh->getlines
.Ve
.Ip "\s-1SEE\s0 \s-1ALSO\s0" 0
.IX Item "\s-1SEE\s0 \s-1ALSO\s0"
.Ip "\s-1BUGS\s0" 0
.IX Item "\s-1BUGS\s0"
.Sh "GDBM_File \- Perl5 access to the gdbm library."
.IX Subsection "GDBM_File \- Perl5 access to the gdbm library."
.Ip "\s-1SYNOPSIS\s0" 0
.IX Item "\s-1SYNOPSIS\s0"
.Ip "\s-1DESCRIPTION\s0" 0
.IX Item "\s-1DESCRIPTION\s0"
.Ip "\s-1AVAILABILITY\s0" 0
.IX Item "\s-1AVAILABILITY\s0"
.Ip "\s-1BUGS\s0" 0
.IX Item "\s-1BUGS\s0"
.Ip "\s-1SEE\s0 \s-1ALSO\s0" 0
.IX Item "\s-1SEE\s0 \s-1ALSO\s0"
.Sh "Getopt::Long, GetOptions \- extended processing of command line options"
.IX Subsection "Getopt::Long, GetOptions \- extended processing of command line options"
.Ip "\s-1SYNOPSIS\s0" 0
.IX Item "\s-1SYNOPSIS\s0"
.Ip "\s-1DESCRIPTION\s0" 0
.IX Item "\s-1DESCRIPTION\s0"
<none>, !, =s, :s, =i, :i, =f, :f
.Ip "Linkage specification" 5
.IX Item "Linkage specification"
.Ip "Aliases and abbreviations" 5
.IX Item "Aliases and abbreviations"
.Ip "Non-option call-back routine" 5
.IX Item "Non-option call-back routine"
.Ip "Option starters" 5
.IX Item "Option starters"
.Ip "Return value" 5
.IX Item "Return value"
.Ip "\s-1COMPATIBILITY\s0" 0
.IX Item "\s-1COMPATIBILITY\s0"
.Ip "\s-1EXAMPLES\s0" 0
.IX Item "\s-1EXAMPLES\s0"
.Ip "\s-1CONFIGURATION\s0 \s-1VARIABLES\s0" 0
.IX Item "\s-1CONFIGURATION\s0 \s-1VARIABLES\s0"
$Getopt::Long::autoabbrev, \f(CW$Getopt::Long::getopt_compat\fR,
\f(CW$Getopt::Long::order\fR, \f(CW$Getopt::Long::ignorecase\fR,
\f(CW$Getopt::Long::VERSION\fR, \f(CW$Getopt::Long::error\fR, \f(CW$Getopt::Long::debug\fR
.Sh "Getopt::Std, getopt \- Process single-character switches with switch clustering"
.IX Subsection "Getopt::Std, getopt \- Process single-character switches with switch clustering"
.Ip "\s-1SYNOPSIS\s0" 0
.IX Item "\s-1SYNOPSIS\s0"
.Ip "\s-1DESCRIPTION\s0" 0
.IX Item "\s-1DESCRIPTION\s0"
.Sh "I18N::Collate \- compare 8-bit scalar data according to the current locale"
.IX Subsection "I18N::Collate \- compare 8-bit scalar data according to the current locale"
.Ip "\s-1SYNOPSIS\s0" 0
.IX Item "\s-1SYNOPSIS\s0"
.Ip "\s-1DESCRIPTION\s0" 0
.IX Item "\s-1DESCRIPTION\s0"
.Sh "\s-1IPC::\s0Open2, open2 \- open a process for both reading and writing"
.IX Subsection "\s-1IPC::\s0Open2, open2 \- open a process for both reading and writing"
.Ip "\s-1SYNOPSIS\s0" 0
.IX Item "\s-1SYNOPSIS\s0"
.Ip "\s-1DESCRIPTION\s0" 0
.IX Item "\s-1DESCRIPTION\s0"
.Ip "\s-1WARNING\s0" 0
.IX Item "\s-1WARNING\s0"
.Ip "\s-1SEE\s0 \s-1ALSO\s0" 0
.IX Item "\s-1SEE\s0 \s-1ALSO\s0"
.Sh "\s-1IPC::\s0Open3, open3 \- open a process for reading, writing, and error handling"
.IX Subsection "\s-1IPC::\s0Open3, open3 \- open a process for reading, writing, and error handling"
.Ip "\s-1SYNOPSIS\s0" 0
.IX Item "\s-1SYNOPSIS\s0"
.Ip "\s-1DESCRIPTION\s0" 0
.IX Item "\s-1DESCRIPTION\s0"
.Sh "Net::Ping, pingecho \- check a host for upness"
.IX Subsection "Net::Ping, pingecho \- check a host for upness"
.Ip "\s-1SYNOPSIS\s0" 0
.IX Item "\s-1SYNOPSIS\s0"
.Ip "\s-1DESCRIPTION\s0" 0
.IX Item "\s-1DESCRIPTION\s0"
.Ip "Parameters" 5
.IX Item "Parameters"
hostname, timeout
.Ip "\s-1WARNING\s0" 0
.IX Item "\s-1WARNING\s0"
.Sh "\s-1POSIX\s0 \- Perl interface to \s-1IEEE\s0 Std 1003.1"
.IX Subsection "\s-1POSIX\s0 \- Perl interface to \s-1IEEE\s0 Std 1003.1"
.Ip "\s-1SYNOPSIS\s0" 0
.IX Item "\s-1SYNOPSIS\s0"
.Ip "\s-1DESCRIPTION\s0" 0
.IX Item "\s-1DESCRIPTION\s0"
.Ip "\s-1NOTE\s0" 0
.IX Item "\s-1NOTE\s0"
.Ip "\s-1CAVEATS\s0" 0
.IX Item "\s-1CAVEATS\s0"
.Ip "\s-1FUNCTIONS\s0" 0
.IX Item "\s-1FUNCTIONS\s0"
_exit, abort, abs, access, acos, alarm, asctime, asin, assert, atan,
atan2, atexit, atof, atoi, atol, bsearch, calloc, ceil, chdir, chmod,
chown, clearerr, clock, close, closedir, cos, cosh, creat, ctermid,
ctime, cuserid, difftime, div, dup, dup2, errno, execl, execle, execlp,
execv, execve, execvp, exit, exp, fabs, fclose, fcntl, fdopen, feof,
ferror, fflush, fgetc, fgetpos, fgets, fileno, floor, fmod, fopen,
fork, fpathconf, fprintf, fputc, fputs, fread, free, freopen, frexp,
fscanf, fseek, fsetpos, fstat, ftell, fwrite, getc, getchar, getcwd,
getegid, getenv, geteuid, getgid, getgrgid, getgrnam, getgroups,
getlogin, getpgrp, getpid, getppid, getpwnam, getpwuid, gets, getuid,
gmtime, isalnum, isalpha, isatty, iscntrl, isdigit, isgraph, islower,
isprint, ispunct, isspace, isupper, isxdigit, kill, labs, ldexp, ldiv,
link, localeconv, localtime, log, log10, longjmp, lseek, malloc, mblen,
mbstowcs, mbtowc, memchr, memcmp, memcpy, memmove, memset, mkdir,
mkfifo, mktime, modf, nice, offsetof, open, opendir, pat
.Ip "\s-1CLASSES\s0" 0
.IX Item "\s-1CLASSES\s0"
.Ip "\s-1POSIX::\s0SigAction" 5
.IX Item "\s-1POSIX::\s0SigAction"
new
.Ip "\s-1POSIX::\s0SigSet" 5
.IX Item "\s-1POSIX::\s0SigSet"
new, addset, delset, emptyset, fillset, ismember
.Ip "\s-1POSIX::\s0Termios" 5
.IX Item "\s-1POSIX::\s0Termios"
new, getattr, getcc, getcflag, getiflag, getispeed, getlflag, getoflag,
getospeed, setattr, setcc, setcflag, setiflag, setispeed, setlflag,
setoflag, setospeed, Baud rate values, Terminal interface values, c_cc
field values, c_cflag field values, c_iflag field values, c_lflag field
values, c_oflag field values
.Ip "\s-1PATHNAME\s0 \s-1CONSTANTS\s0" 0
.IX Item "\s-1PATHNAME\s0 \s-1CONSTANTS\s0"
Constants
.Ip "\s-1POSIX\s0 \s-1CONSTANTS\s0" 0
.IX Item "\s-1POSIX\s0 \s-1CONSTANTS\s0"
Constants
.Ip "\s-1SYSTEM\s0 \s-1CONFIGURATION\s0" 0
.IX Item "\s-1SYSTEM\s0 \s-1CONFIGURATION\s0"
Constants
.Ip "\s-1ERRNO\s0" 0
.IX Item "\s-1ERRNO\s0"
Constants
.Ip "\s-1FCNTL\s0" 0
.IX Item "\s-1FCNTL\s0"
Constants
.Ip "\s-1FLOAT\s0" 0
.IX Item "\s-1FLOAT\s0"
Constants
.Ip "\s-1LIMITS\s0" 0
.IX Item "\s-1LIMITS\s0"
Constants
.Ip "\s-1LOCALE\s0" 0
.IX Item "\s-1LOCALE\s0"
Constants
.Ip "\s-1MATH\s0" 0
.IX Item "\s-1MATH\s0"
Constants
.Ip "\s-1SIGNAL\s0" 0
.IX Item "\s-1SIGNAL\s0"
Constants
.Ip "\s-1STAT\s0" 0
.IX Item "\s-1STAT\s0"
Constants, Macros
.Ip "\s-1STDLIB\s0" 0
.IX Item "\s-1STDLIB\s0"
Constants
.Ip "\s-1STDIO\s0" 0
.IX Item "\s-1STDIO\s0"
Constants
.Ip "\s-1TIME\s0" 0
.IX Item "\s-1TIME\s0"
Constants
.Ip "\s-1UNISTD\s0" 0
.IX Item "\s-1UNISTD\s0"
Constants
.Ip "\s-1WAIT\s0" 0
.IX Item "\s-1WAIT\s0"
Constants, Macros
.Ip "\s-1CREATION\s0" 0
.IX Item "\s-1CREATION\s0"
.Sh "Pod::Text \- convert \s-1POD\s0 data to formatted \s-1ASCII\s0 text"
.IX Subsection "Pod::Text \- convert \s-1POD\s0 data to formatted \s-1ASCII\s0 text"
.Ip "\s-1SYNOPSIS\s0" 0
.IX Item "\s-1SYNOPSIS\s0"
.Ip "\s-1DESCRIPTION\s0" 0
.IX Item "\s-1DESCRIPTION\s0"
.Ip "\s-1AUTHOR\s0" 0
.IX Item "\s-1AUTHOR\s0"
.Ip "\s-1TODO\s0" 0
.IX Item "\s-1TODO\s0"
.Sh "Safe \- Safe extension module for Perl"
.IX Subsection "Safe \- Safe extension module for Perl"
.Ip "\s-1DESCRIPTION\s0" 0
.IX Item "\s-1DESCRIPTION\s0"
a new namespace, an operator mask
.Ip "Operator masks" 5
.IX Item "Operator masks"
.Ip "Methods in class Safe" 5
.IX Item "Methods in class Safe"
\s-1NAMESPACE\s0, \s-1MASK\s0, root (\s-1NAMESPACE\s0), mask (\s-1MASK\s0), trap (\s-1OP\s0, ...), untrap
(\s-1OP\s0, ...), share (\s-1VARNAME\s0, ...), varglob (\s-1VARNAME\s0), reval (\s-1STRING\s0), rdo
(\s-1FILENAME\s0)
.Ip "Subroutines in package Safe" 5
.IX Item "Subroutines in package Safe"
ops_to_mask (\s-1OP\s0, ...), mask_to_ops (\s-1MASK\s0), opcode (\s-1OP\s0, ...), opname
(\s-1OP\s0, ...), fullmask, emptymask, \s-1MAXO\s0, op_mask
.Ip "\s-1AUTHOR\s0" 5
.IX Item "\s-1AUTHOR\s0"
.Sh "Search::Dict, look \- search for key in dictionary file"
.IX Subsection "Search::Dict, look \- search for key in dictionary file"
.Ip "\s-1SYNOPSIS\s0" 0
.IX Item "\s-1SYNOPSIS\s0"
.Ip "\s-1DESCRIPTION\s0" 0
.IX Item "\s-1DESCRIPTION\s0"
.Sh "SelectSaver \- save and restore selected file handle"
.IX Subsection "SelectSaver \- save and restore selected file handle"
.Ip "\s-1SYNOPSIS\s0" 0
.IX Item "\s-1SYNOPSIS\s0"
.Ip "\s-1DESCRIPTION\s0" 0
.IX Item "\s-1DESCRIPTION\s0"
.Sh "SelfLoader \- load functions only on demand"
.IX Subsection "SelfLoader \- load functions only on demand"
.Ip "\s-1SYNOPSIS\s0" 0
.IX Item "\s-1SYNOPSIS\s0"
.Ip "\s-1DESCRIPTION\s0" 0
.IX Item "\s-1DESCRIPTION\s0"
.Ip "The _\|_DATA_\|_ token" 5
.IX Item "The _\|_DATA_\|_ token"
.Ip "SelfLoader autoloading" 5
.IX Item "SelfLoader autoloading"
.Ip "Autoloading and package lexicals" 5
.IX Item "Autoloading and package lexicals"
.Ip "SelfLoader and AutoLoader" 5
.IX Item "SelfLoader and AutoLoader"
.Ip "_\|_DATA_\|_, _\|_END_\|_, and the \s-1FOOBAR::DATA\s0 filehandle." 5
.IX Item "_\|_DATA_\|_, _\|_END_\|_, and the \s-1FOOBAR::DATA\s0 filehandle."
.Ip "Classes and inherited methods." 5
.IX Item "Classes and inherited methods."
.Ip "Multiple packages and fully qualified subroutine names" 0
.IX Item "Multiple packages and fully qualified subroutine names"
.Sh "Socket, sockaddr_in, sockaddr_un, inet_aton, inet_ntoa \- load the C socket.h defines and structure manipulators"
.IX Subsection "Socket, sockaddr_in, sockaddr_un, inet_aton, inet_ntoa \- load the C socket.h defines and structure manipulators"
.Ip "\s-1SYNOPSIS\s0" 0
.IX Item "\s-1SYNOPSIS\s0"
.Ip "\s-1DESCRIPTION\s0" 0
.IX Item "\s-1DESCRIPTION\s0"
inet_aton \s-1HOSTNAME\s0, inet_ntoa \s-1IP_ADDRESS\s0, \s-1INADDR_ANY\s0, \s-1INADDR_LOOPBACK\s0,
\s-1INADDR_NONE\s0, sockaddr_in \s-1PORT\s0, \s-1ADDRESS\s0, sockaddr_in \s-1SOCKADDR_IN\s0,
pack_sockaddr_in \s-1PORT\s0, \s-1IP_ADDRESS\s0, unpack_sockaddr_in \s-1SOCKADDR_IN\s0,
sockaddr_un \s-1PATHNAME\s0, sockaddr_un \s-1SOCKADDR_UN\s0, pack_sockaddr_un \s-1PATH\s0,
unpack_sockaddr_un \s-1SOCKADDR_UN\s0
.Sh "Symbol \- manipulate Perl symbols and their names"
.IX Subsection "Symbol \- manipulate Perl symbols and their names"
.Ip "\s-1SYNOPSIS\s0" 0
.IX Item "\s-1SYNOPSIS\s0"
.Ip "\s-1DESCRIPTION\s0" 0
.IX Item "\s-1DESCRIPTION\s0"
.Sh "Sys::Hostname \- Try every conceivable way to get hostname"
.IX Subsection "Sys::Hostname \- Try every conceivable way to get hostname"
.Ip "\s-1SYNOPSIS\s0" 0
.IX Item "\s-1SYNOPSIS\s0"
.Ip "\s-1DESCRIPTION\s0" 0
.IX Item "\s-1DESCRIPTION\s0"
.Ip "\s-1AUTHOR\s0" 0
.IX Item "\s-1AUTHOR\s0"
.Sh "Syslog, Sys::Syslog, openlog, closelog, setlogmask, syslog \- Perl interface to the \s-1UNIX\s0 \fIsyslog\fR\|(3) calls"
.IX Subsection "Syslog, Sys::Syslog, openlog, closelog, setlogmask, syslog \- Perl interface to the \s-1UNIX\s0 \fIsyslog\fR\|(3) calls"
.Ip "\s-1SYNOPSIS\s0" 0
.IX Item "\s-1SYNOPSIS\s0"
.Ip "\s-1DESCRIPTION\s0" 0
.IX Item "\s-1DESCRIPTION\s0"
openlog \f(CW$ident\fR, \f(CW$logopt\fR, \f(CW$facility\fR, syslog \f(CW$priority\fR, \f(CW$mask\fR, \f(CW$format\fR,
\f(CW@args\fR, setlogmask \f(CW$mask_priority\fR, closelog
.Ip "\s-1EXAMPLES\s0" 0
.IX Item "\s-1EXAMPLES\s0"
.Ip "\s-1DEPENDENCIES\s0" 0
.IX Item "\s-1DEPENDENCIES\s0"
.Ip "\s-1SEE\s0 \s-1ALSO\s0" 0
.IX Item "\s-1SEE\s0 \s-1ALSO\s0"
.Ip "\s-1AUTHOR\s0" 0
.IX Item "\s-1AUTHOR\s0"
.Sh "Term::Cap \- Perl termcap interface"
.IX Subsection "Term::Cap \- Perl termcap interface"
.Ip "\s-1SYNOPSIS\s0" 0
.IX Item "\s-1SYNOPSIS\s0"
.Ip "\s-1DESCRIPTION\s0" 0
.IX Item "\s-1DESCRIPTION\s0"
.Ip "\s-1EXAMPLES\s0" 0
.IX Item "\s-1EXAMPLES\s0"
.Sh "Term::Complete \- Perl word completion module"
.IX Subsection "Term::Complete \- Perl word completion module"
.Ip "\s-1SYNOPSIS\s0" 0
.IX Item "\s-1SYNOPSIS\s0"
.Ip "\s-1DESCRIPTION\s0" 0
.IX Item "\s-1DESCRIPTION\s0"
<tab>Attempts word completion.  Cannot be changed, ^D, ^U, <del>, <bs>
.Ip "\s-1DIAGNOSTICS\s0" 0
.IX Item "\s-1DIAGNOSTICS\s0"
.Ip "\s-1BUGS\s0" 0
.IX Item "\s-1BUGS\s0"
.Ip "\s-1AUTHOR\s0" 0
.IX Item "\s-1AUTHOR\s0"
.Sh "Term::ReadLine \- Perl interface to various \f(CWreadline\fR packages. If no real package is found, substitutes stubs instead of basic functions."
.IX Subsection "Term::ReadLine \- Perl interface to various \f(CWreadline\fR packages. If no real package is found, substitutes stubs instead of basic functions."
.Ip "\s-1SYNOPSIS\s0" 0
.IX Item "\s-1SYNOPSIS\s0"
.Ip "\s-1DESCRIPTION\s0" 0
.IX Item "\s-1DESCRIPTION\s0"
.Ip "Minimal set of supported functions" 0
.IX Item "Minimal set of supported functions"
\f(CWReadLine\fR, \f(CWnew\fR, \f(CWreadline\fR, \f(CWaddhistory\fR, \f(CWIN\fR, $\f(CWOUT\fR,
\f(CWMinLine\fR, \f(CWfindConsole\fR, \f(CWFeatures\fR
.Ip "\s-1EXPORTS\s0" 0
.IX Item "\s-1EXPORTS\s0"
.Sh "Test::Harness \- run perl standard test scripts with statistics"
.IX Subsection "Test::Harness \- run perl standard test scripts with statistics"
.Ip "\s-1SYNOPSIS\s0" 0
.IX Item "\s-1SYNOPSIS\s0"
.Ip "\s-1DESCRIPTION\s0" 0
.IX Item "\s-1DESCRIPTION\s0"
.Ip "The test script output" 5
.IX Item "The test script output"
.Ip "\s-1EXPORT\s0" 0
.IX Item "\s-1EXPORT\s0"
.Ip "\s-1DIAGNOSTICS\s0" 0
.IX Item "\s-1DIAGNOSTICS\s0"
\f(CWAll tests successful.\enFiles=%d,  Tests=%d, %s\fR, \f(CWFAILED tests
%s\en\etFailed %d/%d tests, %.2f%% okay.\fR, \f(CWTest returned status %d
(wstat %d)\fR, \f(CWFailed 1 test, %.2f%% okay. %s\fR, \f(CWFailed %d/%d tests,
%.2f%% okay. %s\fR
.Ip "\s-1SEE\s0 \s-1ALSO\s0" 0
.IX Item "\s-1SEE\s0 \s-1ALSO\s0"
.Ip "\s-1AUTHORS\s0" 0
.IX Item "\s-1AUTHORS\s0"
.Ip "\s-1BUGS\s0" 0
.IX Item "\s-1BUGS\s0"
.Sh "Text::Abbrev, abbrev \- create an abbreviation table from a list"
.IX Subsection "Text::Abbrev, abbrev \- create an abbreviation table from a list"
.Ip "\s-1SYNOPSIS\s0" 0
.IX Item "\s-1SYNOPSIS\s0"
.Ip "\s-1DESCRIPTION\s0" 0
.IX Item "\s-1DESCRIPTION\s0"
.Ip "\s-1EXAMPLE\s0" 0
.IX Item "\s-1EXAMPLE\s0"
.Sh "Text::Soundex \- Implementation of the Soundex Algorithm as Described by Knuth"
.IX Subsection "Text::Soundex \- Implementation of the Soundex Algorithm as Described by Knuth"
.Ip "\s-1SYNOPSIS\s0" 0
.IX Item "\s-1SYNOPSIS\s0"
.Ip "\s-1DESCRIPTION\s0" 0
.IX Item "\s-1DESCRIPTION\s0"
.Ip "\s-1EXAMPLES\s0" 0
.IX Item "\s-1EXAMPLES\s0"
.Ip "\s-1LIMITATIONS\s0" 0
.IX Item "\s-1LIMITATIONS\s0"
.Ip "\s-1AUTHOR\s0" 0
.IX Item "\s-1AUTHOR\s0"
.Sh "Text::Tabs -- expand and unexpand tabs"
.IX Subsection "Text::Tabs -- expand and unexpand tabs"
.Ip "\s-1SYNOPSIS\s0" 0
.IX Item "\s-1SYNOPSIS\s0"
.Ip "\s-1DESCRIPTION\s0" 0
.IX Item "\s-1DESCRIPTION\s0"
.Ip "\s-1AUTHOR\s0" 0
.IX Item "\s-1AUTHOR\s0"
.Sh "Text::Wrap -- wrap text into a paragraph"
.IX Subsection "Text::Wrap -- wrap text into a paragraph"
.Ip "\s-1SYNOPSIS\s0" 0
.IX Item "\s-1SYNOPSIS\s0"
.Ip "\s-1DESCRIPTION\s0" 0
.IX Item "\s-1DESCRIPTION\s0"
.Ip "\s-1AUTHOR\s0" 0
.IX Item "\s-1AUTHOR\s0"
.Sh "Tie::Hash, Tie::StdHash \- base class definitions for tied hashes"
.IX Subsection "Tie::Hash, Tie::StdHash \- base class definitions for tied hashes"
.Ip "\s-1SYNOPSIS\s0" 0
.IX Item "\s-1SYNOPSIS\s0"
.Ip "\s-1DESCRIPTION\s0" 0
.IX Item "\s-1DESCRIPTION\s0"
\s-1TIEHASH\s0 classname, \s-1LIST\s0, \s-1STORE\s0 this, key, value, \s-1FETCH\s0 this, key,
\s-1FIRSTKEY\s0 this, \s-1NEXTKEY\s0 this, lastkey, \s-1EXISTS\s0 this, key, \s-1DELETE\s0 this,
key, \s-1CLEAR\s0 this
.Ip "\s-1CAVEATS\s0" 0
.IX Item "\s-1CAVEATS\s0"
.Ip "\s-1MORE\s0 \s-1INFORMATION\s0" 0
.IX Item "\s-1MORE\s0 \s-1INFORMATION\s0"
.Sh "Tie::Scalar, Tie::StdScalar \- base class definitions for tied scalars"
.IX Subsection "Tie::Scalar, Tie::StdScalar \- base class definitions for tied scalars"
.Ip "\s-1SYNOPSIS\s0" 0
.IX Item "\s-1SYNOPSIS\s0"
.Ip "\s-1DESCRIPTION\s0" 0
.IX Item "\s-1DESCRIPTION\s0"
\s-1TIESCALAR\s0 classname, \s-1LIST\s0, \s-1FETCH\s0 this, \s-1STORE\s0 this, value, \s-1DESTROY\s0 this
.Ip "\s-1MORE\s0 \s-1INFORMATION\s0" 0
.IX Item "\s-1MORE\s0 \s-1INFORMATION\s0"
.Sh "Tie::SubstrHash \- Fixed-table-size, fixed-key-length hashing"
.IX Subsection "Tie::SubstrHash \- Fixed-table-size, fixed-key-length hashing"
.Ip "\s-1SYNOPSIS\s0" 0
.IX Item "\s-1SYNOPSIS\s0"
.Ip "\s-1DESCRIPTION\s0" 0
.IX Item "\s-1DESCRIPTION\s0"
.Ip "\s-1CAVEATS\s0" 0
.IX Item "\s-1CAVEATS\s0"
.Sh "Time::Local \- efficiently compute tome from local and \s-1GMT\s0 time"
.IX Subsection "Time::Local \- efficiently compute tome from local and \s-1GMT\s0 time"
.Ip "\s-1SYNOPSIS\s0" 0
.IX Item "\s-1SYNOPSIS\s0"
.Ip "\s-1DESCRIPTION\s0" 0
.IX Item "\s-1DESCRIPTION\s0"
.SH "AUXILIARY DOCUMENTATION"
.IX Header "AUXILIARY DOCUMENTATION"
Here should be listed all the extra program's docs, but they don't all
have man pages yet:
.Ip "a2p" 0
.IX Item "a2p"
.Ip "s2p" 0
.IX Item "s2p"
.Ip "find2perl" 0
.IX Item "find2perl"
.Ip "h2ph" 0
.IX Item "h2ph"
.Ip "c2ph" 0
.IX Item "c2ph"
.Ip "h2xs" 0
.IX Item "h2xs"
.Ip "xsubpp" 0
.IX Item "xsubpp"
.Ip "pod2man" 0
.IX Item "pod2man"
.Ip "wrapsuid" 0
.IX Item "wrapsuid"
.SH "AUTHOR"
.IX Header "AUTHOR"
Larry Wall <<\fIlwall@sems.com\fR>, with the help of oodles of
other folks.

.rn }` ''
