.rn '' }`
''' $RCSfile$$Revision$$Date$
'''
''' $Log$
'''
.de Sh
.br
.if t .Sp
.ne 5
.PP
\fB\\$1\fR
.PP
..
.de Sp
.if t .sp .5v
.if n .sp
..
.de Ip
.br
.ie \\n(.$>=3 .ne \\$3
.el .ne 3
.IP "\\$1" \\$2
..
.de Vb
.ft CW
.nf
.ne \\$1
..
.de Ve
.ft R

.fi
..
'''
'''
'''     Set up \*(-- to give an unbreakable dash;
'''     string Tr holds user defined translation string.
'''     Bell System Logo is used as a dummy character.
'''
.tr \(*W-|\(bv\*(Tr
.ie n \{\
.ds -- \(*W-
.ds PI pi
.if (\n(.H=4u)&(1m=24u) .ds -- \(*W\h'-12u'\(*W\h'-12u'-\" diablo 10 pitch
.if (\n(.H=4u)&(1m=20u) .ds -- \(*W\h'-12u'\(*W\h'-8u'-\" diablo 12 pitch
.ds L" ""
.ds R" ""
'''   \*(M", \*(S", \*(N" and \*(T" are the equivalent of
'''   \*(L" and \*(R", except that they are used on ".xx" lines,
'''   such as .IP and .SH, which do another additional levels of
'''   double-quote interpretation
.ds M" """
.ds S" """
.ds N" """""
.ds T" """""
.ds L' '
.ds R' '
.ds M' '
.ds S' '
.ds N' '
.ds T' '
'br\}
.el\{\
.ds -- \(em\|
.tr \*(Tr
.ds L" ``
.ds R" ''
.ds M" ``
.ds S" ''
.ds N" ``
.ds T" ''
.ds L' `
.ds R' '
.ds M' `
.ds S' '
.ds N' `
.ds T' '
.ds PI \(*p
'br\}
.\"	If the F register is turned on, we'll generate
.\"	index entries out stderr for the following things:
.\"		TH	Title 
.\"		SH	Header
.\"		Sh	Subsection 
.\"		Ip	Item
.\"		X<>	Xref  (embedded
.\"	Of course, you have to process the output yourself
.\"	in some meaninful fashion.
.if \nF \{
.de IX
.tm Index:\\$1\t\\n%\t"\\$2"
..
.nr % 0
.rr F
.\}
.TH POD2MAN 1 "perl 5.004, patch 55" "26/Nov/97" "Perl Programmers Reference Guide"
.UC
.if n .hy 0
.if n .na
.ds C+ C\v'-.1v'\h'-1p'\s-2+\h'-1p'+\s0\v'.1v'\h'-1p'
.de CQ          \" put $1 in typewriter font
.ft CW
'if n "\c
'if t \\&\\$1\c
'if n \\&\\$1\c
'if n \&"
\\&\\$2 \\$3 \\$4 \\$5 \\$6 \\$7
'.ft R
..
.\" @(#)ms.acc 1.5 88/02/08 SMI; from UCB 4.2
.	\" AM - accent mark definitions
.bd B 3
.	\" fudge factors for nroff and troff
.if n \{\
.	ds #H 0
.	ds #V .8m
.	ds #F .3m
.	ds #[ \f1
.	ds #] \fP
.\}
.if t \{\
.	ds #H ((1u-(\\\\n(.fu%2u))*.13m)
.	ds #V .6m
.	ds #F 0
.	ds #[ \&
.	ds #] \&
.\}
.	\" simple accents for nroff and troff
.if n \{\
.	ds ' \&
.	ds ` \&
.	ds ^ \&
.	ds , \&
.	ds ~ ~
.	ds ? ?
.	ds ! !
.	ds /
.	ds q
.\}
.if t \{\
.	ds ' \\k:\h'-(\\n(.wu*8/10-\*(#H)'\'\h"|\\n:u"
.	ds ` \\k:\h'-(\\n(.wu*8/10-\*(#H)'\`\h'|\\n:u'
.	ds ^ \\k:\h'-(\\n(.wu*10/11-\*(#H)'^\h'|\\n:u'
.	ds , \\k:\h'-(\\n(.wu*8/10)',\h'|\\n:u'
.	ds ~ \\k:\h'-(\\n(.wu-\*(#H-.1m)'~\h'|\\n:u'
.	ds ? \s-2c\h'-\w'c'u*7/10'\u\h'\*(#H'\zi\d\s+2\h'\w'c'u*8/10'
.	ds ! \s-2\(or\s+2\h'-\w'\(or'u'\v'-.8m'.\v'.8m'
.	ds / \\k:\h'-(\\n(.wu*8/10-\*(#H)'\z\(sl\h'|\\n:u'
.	ds q o\h'-\w'o'u*8/10'\s-4\v'.4m'\z\(*i\v'-.4m'\s+4\h'\w'o'u*8/10'
.\}
.	\" troff and (daisy-wheel) nroff accents
.ds : \\k:\h'-(\\n(.wu*8/10-\*(#H+.1m+\*(#F)'\v'-\*(#V'\z.\h'.2m+\*(#F'.\h'|\\n:u'\v'\*(#V'
.ds 8 \h'\*(#H'\(*b\h'-\*(#H'
.ds v \\k:\h'-(\\n(.wu*9/10-\*(#H)'\v'-\*(#V'\*(#[\s-4v\s0\v'\*(#V'\h'|\\n:u'\*(#]
.ds _ \\k:\h'-(\\n(.wu*9/10-\*(#H+(\*(#F*2/3))'\v'-.4m'\z\(hy\v'.4m'\h'|\\n:u'
.ds . \\k:\h'-(\\n(.wu*8/10)'\v'\*(#V*4/10'\z.\v'-\*(#V*4/10'\h'|\\n:u'
.ds 3 \*(#[\v'.2m'\s-2\&3\s0\v'-.2m'\*(#]
.ds o \\k:\h'-(\\n(.wu+\w'\(de'u-\*(#H)/2u'\v'-.3n'\*(#[\z\(de\v'.3n'\h'|\\n:u'\*(#]
.ds d- \h'\*(#H'\(pd\h'-\w'~'u'\v'-.25m'\f2\(hy\fP\v'.25m'\h'-\*(#H'
.ds D- D\\k:\h'-\w'D'u'\v'-.11m'\z\(hy\v'.11m'\h'|\\n:u'
.ds th \*(#[\v'.3m'\s+1I\s-1\v'-.3m'\h'-(\w'I'u*2/3)'\s-1o\s+1\*(#]
.ds Th \*(#[\s+2I\s-2\h'-\w'I'u*3/5'\v'-.3m'o\v'.3m'\*(#]
.ds ae a\h'-(\w'a'u*4/10)'e
.ds Ae A\h'-(\w'A'u*4/10)'E
.ds oe o\h'-(\w'o'u*4/10)'e
.ds Oe O\h'-(\w'O'u*4/10)'E
.	\" corrections for vroff
.if v .ds ~ \\k:\h'-(\\n(.wu*9/10-\*(#H)'\s-2\u~\d\s+2\h'|\\n:u'
.if v .ds ^ \\k:\h'-(\\n(.wu*10/11-\*(#H)'\v'-.4m'^\v'.4m'\h'|\\n:u'
.	\" for low resolution devices (crt and lpr)
.if \n(.H>23 .if \n(.V>19 \
\{\
.	ds : e
.	ds 8 ss
.	ds v \h'-1'\o'\(aa\(ga'
.	ds _ \h'-1'^
.	ds . \h'-1'.
.	ds 3 3
.	ds o a
.	ds d- d\h'-1'\(ga
.	ds D- D\h'-1'\(hy
.	ds th \o'bp'
.	ds Th \o'LP'
.	ds ae ae
.	ds Ae AE
.	ds oe oe
.	ds Oe OE
.\}
.rm #[ #] #H #V #F C
.SH "NAME"
pod2man \- translate embedded Perl pod directives into man pages
.SH "SYNOPSIS"
\fBpod2man\fR
[ \fB--section=\fR\fImanext\fR ]
[ \fB--release=\fR\fIrelpatch\fR ]
[ \fB--center=\fR\fIstring\fR ]
[ \fB--date=\fR\fIstring\fR ]
[ \fB--fixed=\fR\fIfont\fR ]
[ \fB--official\fR ]
[ \fB--lax\fR ]
\fIinputfile\fR
.SH "DESCRIPTION"
\fBpod2man\fR converts its input file containing embedded pod directives (see
the \fIperlpod\fR manpage) into nroff source suitable for viewing with \fInroff\fR\|(1) or
\fItroff\fR\|(1) using the \fIman\fR\|(7) macro set.
.PP
Besides the obvious pod conversions, \fBpod2man\fR also takes care of
\fIfunc()\fR, \fIfunc\fR\|(n), and simple variable references like \f(CW$foo\fR or \f(CW@bar\fR so
you don't have to use code escapes for them; complex expressions like
\f(CW$fred{'stuff'}\fR will still need to be escaped, though.  Other nagging
little roffish things that it catches include translating the minus in
something like foo-bar, making a long dash\*(--like this\*(--into a real em
dash, fixing up \*(L"paired quotes\*(R", putting a little space after the
parens in something like \fIfunc()\fR, making \*(C+ and \*(PI look right, making
double underbars have a little tiny space between them, making ALLCAPS
a teeny bit smaller in \fItroff\fR\|(1), and escaping backslashes so you don't
have to.
.SH "OPTIONS"
.Ip "center" 8
Set the centered header to a specific string.  The default is
\*(L"User Contributed Perl Documentation\*(R", unless the \f(CW--official\fR flag is
given, in which case the default is \*(L"Perl Programmers Reference Guide\*(R".
.Ip "date" 8
Set the left-hand footer string to this value.  By default,
the modification date of the input file will be used.
.Ip "fixed" 8
The fixed font to use for code refs.  Defaults to \s-1CW\s0.
.Ip "official" 8
Set the default header to indicate that this page is of
the standard release in case \f(CW--center\fR is not given.
.Ip "release" 8
Set the centered footer.  By default, this is the current
perl release.
.Ip "section" 8
Set the section for the \f(CW.TH\fR macro.  The standard conventions on
sections are to use 1 for user commands,  2 for system calls, 3 for
functions, 4 for devices, 5 for file formats, 6 for games, 7 for
miscellaneous information, and 8 for administrator commands.  This works
best if you put your Perl man pages in a separate tree, like
\fI/usr/local/perl/man/\fR.  By default, section 1 will be used
unless the file ends in \fI.pm\fR in which case section 3 will be selected.
.Ip "lax" 8
Don't complain when required sections aren't present.
.SH "Anatomy of a Proper Man Page"
For those not sure of the proper layout of a man page, here's
an example of the skeleton of a proper man page.  Head of the
major headers should be setout as a \f(CW=head1\fR directive, and
are historically written in the rather startling ALL UPPER CASE
format, although this is not mandatory.
Minor headers may be included using \f(CW=head2\fR, and are
typically in mixed case.
.Ip "\s-1NAME\s0" 10
Mandatory section; should be a comma-separated list of programs or
functions documented by this podpage, such as:
.Sp
.Vb 1
\&    foo, bar - programs to do something
.Ve
.Ip "\s-1SYNOPSIS\s0" 10
A short usage summary for programs and functions, which
may someday be deemed mandatory.
.Ip "\s-1DESCRIPTION\s0" 10
Long drawn out discussion of the program.  It's a good idea to break this
up into subsections using the \f(CW=head2\fR directives, like
.Sp
.Vb 1
\&    =head2 A Sample Subection
.Ve
.Vb 1
\&    =head2 Yet Another Sample Subection
.Ve
.Ip "\s-1OPTIONS\s0" 10
Some people make this separate from the description.
.Ip "\s-1RETURN\s0 \s-1VALUE\s0" 10
What the program or function returns if successful.
.Ip "\s-1ERRORS\s0" 10
Exceptions, return codes, exit stati, and errno settings.
.Ip "\s-1EXAMPLES\s0" 10
Give some example uses of the program.
.Ip "\s-1ENVIRONMENT\s0" 10
Envariables this program might care about.
.Ip "\s-1FILES\s0" 10
All files used by the program.  You should probably use the F<>
for these.
.Ip "\s-1SEE\s0 \s-1ALSO\s0" 10
Other man pages to check out, like \fIman\fR\|(1), \fIman\fR\|(7), \fImakewhatis\fR\|(8), or \fIcatman\fR\|(8).
.Ip "\s-1NOTES\s0" 10
Miscellaneous commentary.
.Ip "\s-1CAVEATS\s0" 10
Things to take special care with; sometimes called \s-1WARNINGS\s0.
.Ip "\s-1DIAGNOSTICS\s0" 10
All possible messages the program can print out\*(--and
what they mean.
.Ip "\s-1BUGS\s0" 10
Things that are broken or just don't work quite right.
.Ip "\s-1RESTRICTIONS\s0" 10
Bugs you don't plan to fix :\-)
.Ip "\s-1AUTHOR\s0" 10
Who wrote it (or \s-1AUTHORS\s0 if multiple).
.Ip "\s-1HISTORY\s0" 10
Programs derived from other sources sometimes have this, or
you might keep a modification log here.
.SH "EXAMPLES"
.PP
.Vb 3
\&    pod2man program > program.1
\&    pod2man some_module.pm > /usr/perl/man/man3/some_module.3
\&    pod2man --section=7 note.pod > note.7
.Ve
.SH "DIAGNOSTICS"
The following diagnostics are generated by \fBpod2man\fR.  Items
marked \*(L"(W)\*(R" are non-fatal, whereas the \*(L"(F)\*(R" errors will cause
\fBpod2man\fR to immediately exit with a non-zero status.
.Ip "bad option in paragraph %d of %s: ``%s'\*(T' should be [%s]<%s>" 4
(W) If you start include an option, you should set it off
as bold, italic, or code.
.Ip "can't open %s: %s" 4
(F) The input file wasn't available for the given reason.
.Ip "Improper man page \- no dash in \s-1NAME\s0 header in paragraph %d of %s" 4
(W) The \s-1NAME\s0 header did not have an isolated dash in it.  This is
considered important.
.Ip "Invalid man page \- no \s-1NAME\s0 line in %s" 4
(F) You did not include a \s-1NAME\s0 header, which is essential.
.Ip "roff font should be 1 or 2 chars, not `%s\*(T'  (F)" 4
(F) The font specified with the \f(CW--fixed\fR option was not
a one- or two-digit roff font.
.Ip "%s is missing required section: %s" 4
(W) Required sections include \s-1NAME\s0, \s-1DESCRIPTION\s0, and if you're
using a section starting with a 3, also a \s-1SYNOPSIS\s0.  Actually,
not having a \s-1NAME\s0 is a fatal.
.Ip "Unknown escape: %s in %s" 4
(W) An unknown \s-1HTML\s0 entity (probably for an 8-bit character) was given via
a \f(CWE<>\fR directive.  Besides amp, lt, gt, and quot, recognized
entities are Aacute, aacute, Acirc, acirc, AElig, aelig, Agrave, agrave,
Aring, aring, Atilde, atilde, Auml, auml, Ccedil, ccedil, Eacute, eacute,
Ecirc, ecirc, Egrave, egrave, \s-1ETH\s0, eth, Euml, euml, Iacute, iacute, Icirc,
icirc, Igrave, igrave, Iuml, iuml, Ntilde, ntilde, Oacute, oacute, Ocirc,
ocirc, Ograve, ograve, Oslash, oslash, Otilde, otilde, Ouml, ouml, szlig,
\s-1THORN\s0, thorn, Uacute, uacute, Ucirc, ucirc, Ugrave, ugrave, Uuml, uuml,
Yacute, yacute, and yuml.
.Ip "Unmatched =back" 4
(W) You have a \f(CW=back\fR without a corresponding \f(CW=over\fR.
.Ip "Unrecognized pod directive: %s" 4
(W) You specified a pod directive that isn't in the known list of
\f(CW=head1\fR, \f(CW=head2\fR, \f(CW=item\fR, \f(CW=over\fR, \f(CW=back\fR, or \f(CW=cut\fR.
.SH "NOTES"
If you would like to print out a lot of man page continuously, you
probably want to set the C and D registers to set contiguous page
numbering and even/odd paging, at least on some versions of \fIman\fR\|(7).
Settting the F register will get you some additional experimental
indexing:
.PP
.Vb 1
\&    troff -man -rC1 -rD1 -rF1 perl.1 perldata.1 perlsyn.1 ...
.Ve
The indexing merely outputs messages via \f(CW.tm\fR for each
major page, section, subsection, item, and any \f(CWX<>\fR
directives.
.SH "RESTRICTIONS"
None at this time.
.SH "BUGS"
The =over and =back directives don't really work right.  They
take absolute positions instead of offsets, don't nest well, and
making people count is suboptimal in any event.
.SH "AUTHORS"
Original prototype by Larry Wall, but so massively hacked over by
Tom Christiansen such that Larry probably doesn't recognize it anymore.

.rn }` ''
.IX Title "POD2MAN 1"
.IX Name "pod2man - translate embedded Perl pod directives into man pages"

.IX Header "NAME"

.IX Header "SYNOPSIS"

.IX Header "DESCRIPTION"

.IX Header "OPTIONS"

.IX Item "center"

.IX Item "date"

.IX Item "fixed"

.IX Item "official"

.IX Item "release"

.IX Item "section"

.IX Item "lax"

.IX Header "Anatomy of a Proper Man Page"

.IX Item "\s-1NAME\s0"

.IX Item "\s-1SYNOPSIS\s0"

.IX Item "\s-1DESCRIPTION\s0"

.IX Item "\s-1OPTIONS\s0"

.IX Item "\s-1RETURN\s0 \s-1VALUE\s0"

.IX Item "\s-1ERRORS\s0"

.IX Item "\s-1EXAMPLES\s0"

.IX Item "\s-1ENVIRONMENT\s0"

.IX Item "\s-1FILES\s0"

.IX Item "\s-1SEE\s0 \s-1ALSO\s0"

.IX Item "\s-1NOTES\s0"

.IX Item "\s-1CAVEATS\s0"

.IX Item "\s-1DIAGNOSTICS\s0"

.IX Item "\s-1BUGS\s0"

.IX Item "\s-1RESTRICTIONS\s0"

.IX Item "\s-1AUTHOR\s0"

.IX Item "\s-1HISTORY\s0"

.IX Header "EXAMPLES"

.IX Header "DIAGNOSTICS"

.IX Item "bad option in paragraph %d of %s: ``%s'\*(T' should be [%s]<%s>"

.IX Item "can't open %s: %s"

.IX Item "Improper man page \- no dash in \s-1NAME\s0 header in paragraph %d of %s"

.IX Item "Invalid man page \- no \s-1NAME\s0 line in %s"

.IX Item "roff font should be 1 or 2 chars, not `%s\*(T'  (F)"

.IX Item "%s is missing required section: %s"

.IX Item "Unknown escape: %s in %s"

.IX Item "Unmatched =back"

.IX Item "Unrecognized pod directive: %s"

.IX Header "NOTES"

.IX Header "RESTRICTIONS"

.IX Header "BUGS"

.IX Header "AUTHORS"

