.rn '' }`
''' $RCSfile$$Revision$$Date$
'''
''' $Log$
'''
.de Sh
.br
.if t .Sp
.ne 5
.PP
\fB\\$1\fR
.PP
..
.de Sp
.if t .sp .5v
.if n .sp
..
.de Ip
.br
.ie \\n(.$>=3 .ne \\$3
.el .ne 3
.IP "\\$1" \\$2
..
.de Vb
.ft CW
.nf
.ne \\$1
..
.de Ve
.ft R

.fi
..
'''
'''
'''     Set up \*(-- to give an unbreakable dash;
'''     string Tr holds user defined translation string.
'''     Bell System Logo is used as a dummy character.
'''
.tr \(*W-|\(bv\*(Tr
.ie n \{\
.ds -- \(*W-
.ds PI pi
.if (\n(.H=4u)&(1m=24u) .ds -- \(*W\h'-12u'\(*W\h'-12u'-\" diablo 10 pitch
.if (\n(.H=4u)&(1m=20u) .ds -- \(*W\h'-12u'\(*W\h'-8u'-\" diablo 12 pitch
.ds L" ""
.ds R" ""
'''   \*(M", \*(S", \*(N" and \*(T" are the equivalent of
'''   \*(L" and \*(R", except that they are used on ".xx" lines,
'''   such as .IP and .SH, which do another additional levels of
'''   double-quote interpretation
.ds M" """
.ds S" """
.ds N" """""
.ds T" """""
.ds L' '
.ds R' '
.ds M' '
.ds S' '
.ds N' '
.ds T' '
'br\}
.el\{\
.ds -- \(em\|
.tr \*(Tr
.ds L" ``
.ds R" ''
.ds M" ``
.ds S" ''
.ds N" ``
.ds T" ''
.ds L' `
.ds R' '
.ds M' `
.ds S' '
.ds N' `
.ds T' '
.ds PI \(*p
'br\}
.\"	If the F register is turned on, we'll generate
.\"	index entries out stderr for the following things:
.\"		TH	Title 
.\"		SH	Header
.\"		Sh	Subsection 
.\"		Ip	Item
.\"		X<>	Xref  (embedded
.\"	Of course, you have to process the output yourself
.\"	in some meaninful fashion.
.if \nF \{
.de IX
.tm Index:\\$1\t\\n%\t"\\$2"
..
.nr % 0
.rr F
.\}
.TH POD2HTML 1 "perl 5.004, patch 01" "16/Jun/97" "Perl Programmers Reference Guide"
.IX Title "POD2HTML 1"
.UC
.IX Name "pod2html - convert .pod files to .html files"
.if n .hy 0
.if n .na
.ds C+ C\v'-.1v'\h'-1p'\s-2+\h'-1p'+\s0\v'.1v'\h'-1p'
.de CQ          \" put $1 in typewriter font
.ft CW
'if n "\c
'if t \\&\\$1\c
'if n \\&\\$1\c
'if n \&"
\\&\\$2 \\$3 \\$4 \\$5 \\$6 \\$7
'.ft R
..
.\" @(#)ms.acc 1.5 88/02/08 SMI; from UCB 4.2
.	\" AM - accent mark definitions
.bd B 3
.	\" fudge factors for nroff and troff
.if n \{\
.	ds #H 0
.	ds #V .8m
.	ds #F .3m
.	ds #[ \f1
.	ds #] \fP
.\}
.if t \{\
.	ds #H ((1u-(\\\\n(.fu%2u))*.13m)
.	ds #V .6m
.	ds #F 0
.	ds #[ \&
.	ds #] \&
.\}
.	\" simple accents for nroff and troff
.if n \{\
.	ds ' \&
.	ds ` \&
.	ds ^ \&
.	ds , \&
.	ds ~ ~
.	ds ? ?
.	ds ! !
.	ds /
.	ds q
.\}
.if t \{\
.	ds ' \\k:\h'-(\\n(.wu*8/10-\*(#H)'\'\h"|\\n:u"
.	ds ` \\k:\h'-(\\n(.wu*8/10-\*(#H)'\`\h'|\\n:u'
.	ds ^ \\k:\h'-(\\n(.wu*10/11-\*(#H)'^\h'|\\n:u'
.	ds , \\k:\h'-(\\n(.wu*8/10)',\h'|\\n:u'
.	ds ~ \\k:\h'-(\\n(.wu-\*(#H-.1m)'~\h'|\\n:u'
.	ds ? \s-2c\h'-\w'c'u*7/10'\u\h'\*(#H'\zi\d\s+2\h'\w'c'u*8/10'
.	ds ! \s-2\(or\s+2\h'-\w'\(or'u'\v'-.8m'.\v'.8m'
.	ds / \\k:\h'-(\\n(.wu*8/10-\*(#H)'\z\(sl\h'|\\n:u'
.	ds q o\h'-\w'o'u*8/10'\s-4\v'.4m'\z\(*i\v'-.4m'\s+4\h'\w'o'u*8/10'
.\}
.	\" troff and (daisy-wheel) nroff accents
.ds : \\k:\h'-(\\n(.wu*8/10-\*(#H+.1m+\*(#F)'\v'-\*(#V'\z.\h'.2m+\*(#F'.\h'|\\n:u'\v'\*(#V'
.ds 8 \h'\*(#H'\(*b\h'-\*(#H'
.ds v \\k:\h'-(\\n(.wu*9/10-\*(#H)'\v'-\*(#V'\*(#[\s-4v\s0\v'\*(#V'\h'|\\n:u'\*(#]
.ds _ \\k:\h'-(\\n(.wu*9/10-\*(#H+(\*(#F*2/3))'\v'-.4m'\z\(hy\v'.4m'\h'|\\n:u'
.ds . \\k:\h'-(\\n(.wu*8/10)'\v'\*(#V*4/10'\z.\v'-\*(#V*4/10'\h'|\\n:u'
.ds 3 \*(#[\v'.2m'\s-2\&3\s0\v'-.2m'\*(#]
.ds o \\k:\h'-(\\n(.wu+\w'\(de'u-\*(#H)/2u'\v'-.3n'\*(#[\z\(de\v'.3n'\h'|\\n:u'\*(#]
.ds d- \h'\*(#H'\(pd\h'-\w'~'u'\v'-.25m'\f2\(hy\fP\v'.25m'\h'-\*(#H'
.ds D- D\\k:\h'-\w'D'u'\v'-.11m'\z\(hy\v'.11m'\h'|\\n:u'
.ds th \*(#[\v'.3m'\s+1I\s-1\v'-.3m'\h'-(\w'I'u*2/3)'\s-1o\s+1\*(#]
.ds Th \*(#[\s+2I\s-2\h'-\w'I'u*3/5'\v'-.3m'o\v'.3m'\*(#]
.ds ae a\h'-(\w'a'u*4/10)'e
.ds Ae A\h'-(\w'A'u*4/10)'E
.ds oe o\h'-(\w'o'u*4/10)'e
.ds Oe O\h'-(\w'O'u*4/10)'E
.	\" corrections for vroff
.if v .ds ~ \\k:\h'-(\\n(.wu*9/10-\*(#H)'\s-2\u~\d\s+2\h'|\\n:u'
.if v .ds ^ \\k:\h'-(\\n(.wu*10/11-\*(#H)'\v'-.4m'^\v'.4m'\h'|\\n:u'
.	\" for low resolution devices (crt and lpr)
.if \n(.H>23 .if \n(.V>19 \
\{\
.	ds : e
.	ds 8 ss
.	ds v \h'-1'\o'\(aa\(ga'
.	ds _ \h'-1'^
.	ds . \h'-1'.
.	ds 3 3
.	ds o a
.	ds d- d\h'-1'\(ga
.	ds D- D\h'-1'\(hy
.	ds th \o'bp'
.	ds Th \o'LP'
.	ds ae ae
.	ds Ae AE
.	ds oe oe
.	ds Oe OE
.\}
.rm #[ #] #H #V #F C
.SH "NAME"
.IX Header "NAME"
pod2html \- convert .pod files to .html files
.SH "SYNOPSIS"
.IX Header "SYNOPSIS"
.PP
.Vb 4
\&    pod2html --help --htmlroot=<name> --infile=<name> --outfile=<name>
\&             --podpath=<name>:...:<name> --podroot=<name>
\&             --libpods=<name>:...:<name> --recurse --norecurse --verbose
\&             --index --noindex --title=<name>
.Ve
.SH "DESCRIPTION"
.IX Header "DESCRIPTION"
Converts files from pod format (see the \fIperlpod\fR manpage) to HTML format.
.SH "ARGUMENTS"
.IX Header "ARGUMENTS"
pod2html takes the following arguments:
.Ip "help" 4
.IX Item "help"
.Sp
.Vb 1
\&  --help
.Ve
Displays the usage message.
.Ip "htmlroot" 4
.IX Item "htmlroot"
.Sp
.Vb 1
\&  --htmlroot=name
.Ve
Sets the base \s-1URL\s0 for the \s-1HTML\s0 files.  When cross-references are made,
the \s-1HTML\s0 root is prepended to the \s-1URL\s0.
.Ip "infile" 4
.IX Item "infile"
.Sp
.Vb 1
\&  --infile=name
.Ve
Specify the pod file to convert.  Input is taken from \s-1STDIN\s0 if no
infile is specified.
.Ip "outfile" 4
.IX Item "outfile"
.Sp
.Vb 1
\&  --outfile=name
.Ve
Specify the \s-1HTML\s0 file to create.  Output goes to \s-1STDOUT\s0 if no outfile
is specified.
.Ip "podroot" 4
.IX Item "podroot"
.Sp
.Vb 1
\&  --podroot=name
.Ve
Specify the base directory for finding library pods.
.Ip "podpath" 4
.IX Item "podpath"
.Sp
.Vb 1
\&  --podpath=name:...:name
.Ve
Specify which subdirectories of the podroot contain pod files whose
\s-1HTML\s0 converted forms can be linked-to in cross-references.
.Ip "libpods" 4
.IX Item "libpods"
.Sp
.Vb 1
\&  --libpods=name:...:name
.Ve
List of page names (eg, \*(L"perlfunc") which contain linkable \f(CW=item\fRs.
.Ip "netscape" 4
.IX Item "netscape"
.Sp
.Vb 1
\&  --netscape
.Ve
Use Netscape \s-1HTML\s0 directives when applicable.
.Ip "nonetscape" 4
.IX Item "nonetscape"
.Sp
.Vb 1
\&  --nonetscape
.Ve
Do not use Netscape \s-1HTML\s0 directives (default).
.Ip "index" 4
.IX Item "index"
.Sp
.Vb 1
\&  --index
.Ve
Generate an index at the top of the \s-1HTML\s0 file (default behaviour).
.Ip "noindex" 4
.IX Item "noindex"
.Sp
.Vb 1
\&  --noindex
.Ve
Do not generate an index at the top of the \s-1HTML\s0 file.
.Ip "recurse" 4
.IX Item "recurse"
.Sp
.Vb 1
\&  --recurse
.Ve
Recurse into subdirectories specified in podpath (default behaviour).
.Ip "norecurse" 4
.IX Item "norecurse"
.Sp
.Vb 1
\&  --norecurse
.Ve
Do not recurse into subdirectories specified in podpath.
.Ip "title" 4
.IX Item "title"
.Sp
.Vb 1
\&  --title=title
.Ve
Specify the title of the resulting \s-1HTML\s0 file.
.Ip "verbose" 4
.IX Item "verbose"
.Sp
.Vb 1
\&  --verbose
.Ve
Display progress messages.
.SH "AUTHOR"
.IX Header "AUTHOR"
Tom Christiansen, <tchrist@perl.com>.
.SH "BUGS"
.IX Header "BUGS"
See the \fIPod::Html\fR manpage for a list of known bugs in the translator.
.SH "SEE ALSO"
.IX Header "SEE ALSO"
the \fIperlpod\fR manpage, the \fIPod::HTML\fR manpage
.SH "COPYRIGHT"
.IX Header "COPYRIGHT"
This program is distributed under the Artistic License.

.rn }` ''
